# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pat.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_pat(object):
    def setupUi(self, pat):
        pat.setObjectName("pat")
        pat.resize(1366, 768)
        self.page_pat_home = QtWidgets.QWidget()
        self.page_pat_home.setObjectName("page_pat_home")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_pat_home)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 9, 5, 1, 1)
        self.page_pat_home_button_proceed = QtWidgets.QPushButton(self.page_pat_home)
        self.page_pat_home_button_proceed.setEnabled(False)
        self.page_pat_home_button_proceed.setMinimumSize(QtCore.QSize(100, 0))
        self.page_pat_home_button_proceed.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_pat_home_button_proceed.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.page_pat_home_button_proceed.setObjectName("page_pat_home_button_proceed")
        self.gridLayout_2.addWidget(self.page_pat_home_button_proceed, 9, 6, 1, 1)
        self.page_pat_home_logout = QtWidgets.QPushButton(self.page_pat_home)
        self.page_pat_home_logout.setMinimumSize(QtCore.QSize(100, 0))
        self.page_pat_home_logout.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_pat_home_logout.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.page_pat_home_logout.setObjectName("page_pat_home_logout")
        self.gridLayout_2.addWidget(self.page_pat_home_logout, 3, 7, 1, 1)
        self.page_pat_home_textEdit_search = QtWidgets.QTextEdit(self.page_pat_home)
        self.page_pat_home_textEdit_search.setMaximumSize(QtCore.QSize(16777215, 25))
        self.page_pat_home_textEdit_search.setObjectName("page_pat_home_textEdit_search")
        self.gridLayout_2.addWidget(self.page_pat_home_textEdit_search, 6, 6, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 7, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 6, 7, 1, 1)
        self.page_pat_home_treeWidget_treatment_list = QtWidgets.QTreeWidget(self.page_pat_home)
        self.page_pat_home_treeWidget_treatment_list.setObjectName("page_pat_home_treeWidget_treatment_list")
        self.gridLayout_2.addWidget(self.page_pat_home_treeWidget_treatment_list, 7, 1, 1, 6)
        self.page_pat_home_button_my_profile = QtWidgets.QToolButton(self.page_pat_home)
        self.page_pat_home_button_my_profile.setMinimumSize(QtCore.QSize(100, 0))
        self.page_pat_home_button_my_profile.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_pat_home_button_my_profile.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.page_pat_home_button_my_profile.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/account.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_pat_home_button_my_profile.setIcon(icon)
        self.page_pat_home_button_my_profile.setCheckable(False)
        self.page_pat_home_button_my_profile.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_pat_home_button_my_profile.setObjectName("page_pat_home_button_my_profile")
        self.gridLayout_2.addWidget(self.page_pat_home_button_my_profile, 3, 0, 1, 1)
        pat.addWidget(self.page_pat_home)
        self.page_pat_errand = QtWidgets.QWidget()
        self.page_pat_errand.setObjectName("page_pat_errand")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_pat_errand)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.page_pat_errand_treeWidget_errand_list = QtWidgets.QTreeWidget(self.page_pat_errand)
        self.page_pat_errand_treeWidget_errand_list.setMinimumSize(QtCore.QSize(300, 0))
        self.page_pat_errand_treeWidget_errand_list.setObjectName("page_pat_errand_treeWidget_errand_list")
        self.page_pat_errand_treeWidget_errand_list.headerItem().setTextAlignment(0, QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.gridLayout_5.addWidget(self.page_pat_errand_treeWidget_errand_list, 2, 3, 1, 6)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 2, 2, 1, 1)
        self.page_pat_errand_label_errands = QtWidgets.QLabel(self.page_pat_errand)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.page_pat_errand_label_errands.setFont(font)
        self.page_pat_errand_label_errands.setStyleSheet("font-size: 20pt;")
        self.page_pat_errand_label_errands.setObjectName("page_pat_errand_label_errands")
        self.gridLayout_5.addWidget(self.page_pat_errand_label_errands, 1, 3, 1, 3)
        self.page_pat_errand_button_view_status = QtWidgets.QToolButton(self.page_pat_errand)
        self.page_pat_errand_button_view_status.setMinimumSize(QtCore.QSize(100, 0))
        self.page_pat_errand_button_view_status.setMaximumSize(QtCore.QSize(100, 16777215))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/status.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_pat_errand_button_view_status.setIcon(icon1)
        self.page_pat_errand_button_view_status.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_pat_errand_button_view_status.setObjectName("page_pat_errand_button_view_status")
        self.gridLayout_5.addWidget(self.page_pat_errand_button_view_status, 3, 7, 1, 1)
        self.page_pat_errand_button_share = QtWidgets.QToolButton(self.page_pat_errand)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/share.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_pat_errand_button_share.setIcon(icon2)
        self.page_pat_errand_button_share.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_pat_errand_button_share.setObjectName("page_pat_errand_button_share")
        self.gridLayout_5.addWidget(self.page_pat_errand_button_share, 3, 5, 1, 1)
        self.page_pat_errand_logout = QtWidgets.QToolButton(self.page_pat_errand)
        self.page_pat_errand_logout.setMinimumSize(QtCore.QSize(100, 0))
        self.page_pat_errand_logout.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_pat_errand_logout.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_pat_errand_logout.setIcon(icon3)
        self.page_pat_errand_logout.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_pat_errand_logout.setObjectName("page_pat_errand_logout")
        self.gridLayout_5.addWidget(self.page_pat_errand_logout, 0, 8, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem4, 3, 6, 1, 1)
        self.page_pat_errand_label_company_name = QtWidgets.QLabel(self.page_pat_errand)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.page_pat_errand_label_company_name.setFont(font)
        self.page_pat_errand_label_company_name.setStyleSheet("color: rgb(253, 147, 50);\n"
"font: 30pt;")
        self.page_pat_errand_label_company_name.setObjectName("page_pat_errand_label_company_name")
        self.gridLayout_5.addWidget(self.page_pat_errand_label_company_name, 0, 1, 1, 1)
        self.page_pat_errand_button_download = QtWidgets.QToolButton(self.page_pat_errand)
        self.page_pat_errand_button_download.setMinimumSize(QtCore.QSize(100, 0))
        self.page_pat_errand_button_download.setMaximumSize(QtCore.QSize(100, 16777215))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_pat_errand_button_download.setIcon(icon4)
        self.page_pat_errand_button_download.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_pat_errand_button_download.setObjectName("page_pat_errand_button_download")
        self.gridLayout_5.addWidget(self.page_pat_errand_button_download, 3, 3, 1, 2)
        self.page_pat_errand_report = QtWidgets.QTextBrowser(self.page_pat_errand)
        self.page_pat_errand_report.setMinimumSize(QtCore.QSize(300, 0))
        self.page_pat_errand_report.setObjectName("page_pat_errand_report")
        self.gridLayout_5.addWidget(self.page_pat_errand_report, 2, 1, 2, 1)
        self.page_pat_errand_button_view = QtWidgets.QToolButton(self.page_pat_errand)
        self.page_pat_errand_button_view.setEnabled(False)
        self.page_pat_errand_button_view.setMinimumSize(QtCore.QSize(100, 0))
        self.page_pat_errand_button_view.setMaximumSize(QtCore.QSize(100, 16777215))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/view.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_pat_errand_button_view.setIcon(icon5)
        self.page_pat_errand_button_view.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_pat_errand_button_view.setObjectName("page_pat_errand_button_view")
        self.gridLayout_5.addWidget(self.page_pat_errand_button_view, 3, 8, 1, 1)
        self.page_pat_errand_label_report = QtWidgets.QLabel(self.page_pat_errand)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.page_pat_errand_label_report.setFont(font)
        self.page_pat_errand_label_report.setStyleSheet("font-size: 20pt;")
        self.page_pat_errand_label_report.setObjectName("page_pat_errand_label_report")
        self.gridLayout_5.addWidget(self.page_pat_errand_label_report, 1, 1, 1, 1)
        self.page_pat_errand_button_back = QtWidgets.QToolButton(self.page_pat_errand)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_pat_errand_button_back.sizePolicy().hasHeightForWidth())
        self.page_pat_errand_button_back.setSizePolicy(sizePolicy)
        self.page_pat_errand_button_back.setMinimumSize(QtCore.QSize(100, 0))
        self.page_pat_errand_button_back.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_pat_errand_button_back.setIcon(icon)
        self.page_pat_errand_button_back.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_pat_errand_button_back.setObjectName("page_pat_errand_button_back")
        self.gridLayout_5.addWidget(self.page_pat_errand_button_back, 0, 7, 1, 1)
        self.page_pat_errand_report_textEdit_search = QtWidgets.QPlainTextEdit(self.page_pat_errand)
        self.page_pat_errand_report_textEdit_search.setMaximumSize(QtCore.QSize(16777215, 25))
        self.page_pat_errand_report_textEdit_search.setPlainText("")
        self.page_pat_errand_report_textEdit_search.setObjectName("page_pat_errand_report_textEdit_search")
        self.gridLayout_5.addWidget(self.page_pat_errand_report_textEdit_search, 1, 7, 1, 2)
        pat.addWidget(self.page_pat_errand)
        self.page_pat_my_profile = QtWidgets.QWidget()
        self.page_pat_my_profile.setObjectName("page_pat_my_profile")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_pat_my_profile)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.page_pat_my_profile_textBrowser = QtWidgets.QTextBrowser(self.page_pat_my_profile)
        self.page_pat_my_profile_textBrowser.setObjectName("page_pat_my_profile_textBrowser")
        self.gridLayout_6.addWidget(self.page_pat_my_profile_textBrowser, 0, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem5, 0, 1, 1, 1)
        self.page_pat_my_profile_button_back = QtWidgets.QPushButton(self.page_pat_my_profile)
        self.page_pat_my_profile_button_back.setMinimumSize(QtCore.QSize(100, 0))
        self.page_pat_my_profile_button_back.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_pat_my_profile_button_back.setObjectName("page_pat_my_profile_button_back")
        self.gridLayout_6.addWidget(self.page_pat_my_profile_button_back, 1, 1, 1, 1)
        pat.addWidget(self.page_pat_my_profile)
        self.page_pat_image_status = QtWidgets.QWidget()
        self.page_pat_image_status.setObjectName("page_pat_image_status")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_pat_image_status)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.page_pat_image_status_button_back = QtWidgets.QPushButton(self.page_pat_image_status)
        self.page_pat_image_status_button_back.setObjectName("page_pat_image_status_button_back")
        self.gridLayout_7.addWidget(self.page_pat_image_status_button_back, 4, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem6, 1, 0, 1, 1)
        self.page_pat_image_status_button_request_notification = QtWidgets.QPushButton(self.page_pat_image_status)
        self.page_pat_image_status_button_request_notification.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_pat_image_status_button_request_notification.setObjectName("page_pat_image_status_button_request_notification")
        self.gridLayout_7.addWidget(self.page_pat_image_status_button_request_notification, 2, 0, 1, 1)
        self.page_pat_image_status_journey_image = QtWidgets.QOpenGLWidget(self.page_pat_image_status)
        self.page_pat_image_status_journey_image.setObjectName("page_pat_image_status_journey_image")
        self.gridLayout_7.addWidget(self.page_pat_image_status_journey_image, 0, 1, 1, 1)
        self.page_pat_image_status_textBrowser_detailed_information = QtWidgets.QTextBrowser(self.page_pat_image_status)
        self.page_pat_image_status_textBrowser_detailed_information.setMaximumSize(QtCore.QSize(500, 500))
        self.page_pat_image_status_textBrowser_detailed_information.setObjectName("page_pat_image_status_textBrowser_detailed_information")
        self.gridLayout_7.addWidget(self.page_pat_image_status_textBrowser_detailed_information, 1, 1, 3, 1)
        self.page_pat_image_status_button_logout = QtWidgets.QPushButton(self.page_pat_image_status)
        self.page_pat_image_status_button_logout.setMinimumSize(QtCore.QSize(100, 0))
        self.page_pat_image_status_button_logout.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_pat_image_status_button_logout.setObjectName("page_pat_image_status_button_logout")
        self.gridLayout_7.addWidget(self.page_pat_image_status_button_logout, 0, 2, 1, 1)
        pat.addWidget(self.page_pat_image_status)
        self.page_pat_view_scan = QtWidgets.QWidget()
        self.page_pat_view_scan.setObjectName("page_pat_view_scan")
        self.gridLayout = QtWidgets.QGridLayout(self.page_pat_view_scan)
        self.gridLayout.setObjectName("gridLayout")
        self.page_pat_view_scan_2d_view_frame = QtWidgets.QFrame(self.page_pat_view_scan)
        self.page_pat_view_scan_2d_view_frame.setMinimumSize(QtCore.QSize(300, 300))
        self.page_pat_view_scan_2d_view_frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.page_pat_view_scan_2d_view_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.page_pat_view_scan_2d_view_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_pat_view_scan_2d_view_frame.setObjectName("page_pat_view_scan_2d_view_frame")
        self.page_pat_view_scan_2d_view_frame_grid = QtWidgets.QGridLayout(self.page_pat_view_scan_2d_view_frame)
        self.page_pat_view_scan_2d_view_frame_grid.setContentsMargins(0, 0, 0, 0)
        self.page_pat_view_scan_2d_view_frame_grid.setObjectName("page_pat_view_scan_2d_view_frame_grid")
        self.page_pat_view_scan_2d_view = QtWidgets.QWidget(self.page_pat_view_scan_2d_view_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_pat_view_scan_2d_view.sizePolicy().hasHeightForWidth())
        self.page_pat_view_scan_2d_view.setSizePolicy(sizePolicy)
        self.page_pat_view_scan_2d_view.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.page_pat_view_scan_2d_view.setObjectName("page_pat_view_scan_2d_view")
        self.page_pat_view_scan_2d_view_frame_grid.addWidget(self.page_pat_view_scan_2d_view, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.page_pat_view_scan_2d_view_frame, 3, 1, 2, 1)
        self.page_pat_view_scan_rad_annotations_frame = QtWidgets.QFrame(self.page_pat_view_scan)
        self.page_pat_view_scan_rad_annotations_frame.setMinimumSize(QtCore.QSize(0, 200))
        self.page_pat_view_scan_rad_annotations_frame.setMaximumSize(QtCore.QSize(16777215, 300))
        self.page_pat_view_scan_rad_annotations_frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.page_pat_view_scan_rad_annotations_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.page_pat_view_scan_rad_annotations_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_pat_view_scan_rad_annotations_frame.setLineWidth(1)
        self.page_pat_view_scan_rad_annotations_frame.setObjectName("page_pat_view_scan_rad_annotations_frame")
        self.page_pat_view_scan_rad_annotations_frame_grid = QtWidgets.QGridLayout(self.page_pat_view_scan_rad_annotations_frame)
        self.page_pat_view_scan_rad_annotations_frame_grid.setContentsMargins(0, 0, 0, 0)
        self.page_pat_view_scan_rad_annotations_frame_grid.setObjectName("page_pat_view_scan_rad_annotations_frame_grid")
        self.page_pat_view_scan_rad_annotations = QtWidgets.QWidget(self.page_pat_view_scan_rad_annotations_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_pat_view_scan_rad_annotations.sizePolicy().hasHeightForWidth())
        self.page_pat_view_scan_rad_annotations.setSizePolicy(sizePolicy)
        self.page_pat_view_scan_rad_annotations.setStyleSheet("background-color: rgb(0, 85, 127);")
        self.page_pat_view_scan_rad_annotations.setObjectName("page_pat_view_scan_rad_annotations")
        self.page_pat_view_scan_rad_annotations_frame_grid.addWidget(self.page_pat_view_scan_rad_annotations, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.page_pat_view_scan_rad_annotations_frame, 7, 1, 1, 1)
        self.page_pat_view_scan_tools = QtWidgets.QToolBox(self.page_pat_view_scan)
        self.page_pat_view_scan_tools.setObjectName("page_pat_view_scan_tools")
        self.page_pat_view_scan_tools_orientation = QtWidgets.QWidget()
        self.page_pat_view_scan_tools_orientation.setStyleSheet("background-color: #151a1e;\n"
"color: #4fa08b")
        self.page_pat_view_scan_tools_orientation.setObjectName("page_pat_view_scan_tools_orientation")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.page_pat_view_scan_tools_orientation)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton = QtWidgets.QRadioButton(self.page_pat_view_scan_tools_orientation)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.page_pat_view_scan_radio_group_orientation = QtWidgets.QButtonGroup(pat)
        self.page_pat_view_scan_radio_group_orientation.setObjectName("page_pat_view_scan_radio_group_orientation")
        self.page_pat_view_scan_radio_group_orientation.addButton(self.radioButton)
        self.horizontalLayout_3.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.page_pat_view_scan_tools_orientation)
        self.radioButton_2.setObjectName("radioButton_2")
        self.page_pat_view_scan_radio_group_orientation.addButton(self.radioButton_2)
        self.horizontalLayout_3.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.page_pat_view_scan_tools_orientation)
        self.radioButton_3.setObjectName("radioButton_3")
        self.page_pat_view_scan_radio_group_orientation.addButton(self.radioButton_3)
        self.horizontalLayout_3.addWidget(self.radioButton_3)
        self.page_pat_view_scan_tools.addItem(self.page_pat_view_scan_tools_orientation, "")
        self.page_pat_view_scan_tools_tissue = QtWidgets.QWidget()
        self.page_pat_view_scan_tools_tissue.setGeometry(QtCore.QRect(0, 0, 663, 69))
        self.page_pat_view_scan_tools_tissue.setStyleSheet("background-color: #151a1e;\n"
"color: #4fa08b")
        self.page_pat_view_scan_tools_tissue.setObjectName("page_pat_view_scan_tools_tissue")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.page_pat_view_scan_tools_tissue)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_All = QtWidgets.QCheckBox(self.page_pat_view_scan_tools_tissue)
        self.checkBox_All.setChecked(True)
        self.checkBox_All.setObjectName("checkBox_All")
        self.horizontalLayout_2.addWidget(self.checkBox_All)
        self.checkBox_Soft = QtWidgets.QCheckBox(self.page_pat_view_scan_tools_tissue)
        self.checkBox_Soft.setObjectName("checkBox_Soft")
        self.horizontalLayout_2.addWidget(self.checkBox_Soft)
        self.checkBox_Bone = QtWidgets.QCheckBox(self.page_pat_view_scan_tools_tissue)
        self.checkBox_Bone.setObjectName("checkBox_Bone")
        self.horizontalLayout_2.addWidget(self.checkBox_Bone)
        self.checkBox_Muscle = QtWidgets.QCheckBox(self.page_pat_view_scan_tools_tissue)
        self.checkBox_Muscle.setObjectName("checkBox_Muscle")
        self.horizontalLayout_2.addWidget(self.checkBox_Muscle)
        self.checkBox_Fat = QtWidgets.QCheckBox(self.page_pat_view_scan_tools_tissue)
        self.checkBox_Fat.setObjectName("checkBox_Fat")
        self.horizontalLayout_2.addWidget(self.checkBox_Fat)
        self.checkBox_Skin = QtWidgets.QCheckBox(self.page_pat_view_scan_tools_tissue)
        self.checkBox_Skin.setStyleSheet("c")
        self.checkBox_Skin.setObjectName("checkBox_Skin")
        self.horizontalLayout_2.addWidget(self.checkBox_Skin)
        self.page_pat_view_scan_tools.addItem(self.page_pat_view_scan_tools_tissue, "")
        self.page_pat_view_scan_tools_transparency = QtWidgets.QWidget()
        self.page_pat_view_scan_tools_transparency.setGeometry(QtCore.QRect(0, 0, 663, 89))
        self.page_pat_view_scan_tools_transparency.setStyleSheet("background-color: #151a1e;\n"
"color: #4fa08b;")
        self.page_pat_view_scan_tools_transparency.setObjectName("page_pat_view_scan_tools_transparency")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.page_pat_view_scan_tools_transparency)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.page_pat_view_scan_layout_transparency_volume = QtWidgets.QVBoxLayout()
        self.page_pat_view_scan_layout_transparency_volume.setObjectName("page_pat_view_scan_layout_transparency_volume")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.page_pat_view_scan_layout_transparency_volume.addItem(spacerItem7)
        self.page_pat_view_scan_slider_transparency_volume = QtWidgets.QSlider(self.page_pat_view_scan_tools_transparency)
        self.page_pat_view_scan_slider_transparency_volume.setMaximum(100)
        self.page_pat_view_scan_slider_transparency_volume.setSingleStep(1)
        self.page_pat_view_scan_slider_transparency_volume.setProperty("value", 20)
        self.page_pat_view_scan_slider_transparency_volume.setOrientation(QtCore.Qt.Horizontal)
        self.page_pat_view_scan_slider_transparency_volume.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.page_pat_view_scan_slider_transparency_volume.setObjectName("page_pat_view_scan_slider_transparency_volume")
        self.page_pat_view_scan_layout_transparency_volume.addWidget(self.page_pat_view_scan_slider_transparency_volume)
        self.page_pat_view_scan_label_transparency_volume = QtWidgets.QLabel(self.page_pat_view_scan_tools_transparency)
        self.page_pat_view_scan_label_transparency_volume.setStyleSheet("")
        self.page_pat_view_scan_label_transparency_volume.setAlignment(QtCore.Qt.AlignCenter)
        self.page_pat_view_scan_label_transparency_volume.setObjectName("page_pat_view_scan_label_transparency_volume")
        self.page_pat_view_scan_layout_transparency_volume.addWidget(self.page_pat_view_scan_label_transparency_volume)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.page_pat_view_scan_layout_transparency_volume.addItem(spacerItem8)
        self.horizontalLayout.addLayout(self.page_pat_view_scan_layout_transparency_volume)
        self.page_pat_view_scan_layout_transparency_segmentation = QtWidgets.QVBoxLayout()
        self.page_pat_view_scan_layout_transparency_segmentation.setObjectName("page_pat_view_scan_layout_transparency_segmentation")
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.page_pat_view_scan_layout_transparency_segmentation.addItem(spacerItem9)
        self.page_pat_view_scan_slider_transparency_segmentation = QtWidgets.QSlider(self.page_pat_view_scan_tools_transparency)
        self.page_pat_view_scan_slider_transparency_segmentation.setMaximum(100)
        self.page_pat_view_scan_slider_transparency_segmentation.setProperty("value", 33)
        self.page_pat_view_scan_slider_transparency_segmentation.setSliderPosition(33)
        self.page_pat_view_scan_slider_transparency_segmentation.setOrientation(QtCore.Qt.Horizontal)
        self.page_pat_view_scan_slider_transparency_segmentation.setObjectName("page_pat_view_scan_slider_transparency_segmentation")
        self.page_pat_view_scan_layout_transparency_segmentation.addWidget(self.page_pat_view_scan_slider_transparency_segmentation)
        self.page_pat_view_scan_label_transparency_segmentation = QtWidgets.QLabel(self.page_pat_view_scan_tools_transparency)
        self.page_pat_view_scan_label_transparency_segmentation.setStyleSheet("")
        self.page_pat_view_scan_label_transparency_segmentation.setAlignment(QtCore.Qt.AlignCenter)
        self.page_pat_view_scan_label_transparency_segmentation.setObjectName("page_pat_view_scan_label_transparency_segmentation")
        self.page_pat_view_scan_layout_transparency_segmentation.addWidget(self.page_pat_view_scan_label_transparency_segmentation)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.page_pat_view_scan_layout_transparency_segmentation.addItem(spacerItem10)
        self.horizontalLayout.addLayout(self.page_pat_view_scan_layout_transparency_segmentation)
        self.page_pat_view_scan_layout_transparency_active = QtWidgets.QVBoxLayout()
        self.page_pat_view_scan_layout_transparency_active.setObjectName("page_pat_view_scan_layout_transparency_active")
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.page_pat_view_scan_layout_transparency_active.addItem(spacerItem11)
        self.page_pat_view_scan_slider_transparency_active = QtWidgets.QSlider(self.page_pat_view_scan_tools_transparency)
        self.page_pat_view_scan_slider_transparency_active.setMaximum(100)
        self.page_pat_view_scan_slider_transparency_active.setProperty("value", 40)
        self.page_pat_view_scan_slider_transparency_active.setOrientation(QtCore.Qt.Horizontal)
        self.page_pat_view_scan_slider_transparency_active.setObjectName("page_pat_view_scan_slider_transparency_active")
        self.page_pat_view_scan_layout_transparency_active.addWidget(self.page_pat_view_scan_slider_transparency_active)
        self.page_pat_view_scan_label_transparency_active = QtWidgets.QLabel(self.page_pat_view_scan_tools_transparency)
        self.page_pat_view_scan_label_transparency_active.setStyleSheet("")
        self.page_pat_view_scan_label_transparency_active.setAlignment(QtCore.Qt.AlignCenter)
        self.page_pat_view_scan_label_transparency_active.setObjectName("page_pat_view_scan_label_transparency_active")
        self.page_pat_view_scan_layout_transparency_active.addWidget(self.page_pat_view_scan_label_transparency_active)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.page_pat_view_scan_layout_transparency_active.addItem(spacerItem12)
        self.horizontalLayout.addLayout(self.page_pat_view_scan_layout_transparency_active)
        self.page_pat_view_scan_tools.addItem(self.page_pat_view_scan_tools_transparency, "")
        self.page_pat_view_scan_tools_link = QtWidgets.QWidget()
        self.page_pat_view_scan_tools_link.setStyleSheet("background-color: #151a1e;\n"
"color: #4fa08b;")
        self.page_pat_view_scan_tools_link.setObjectName("page_pat_view_scan_tools_link")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.page_pat_view_scan_tools_link)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBox = QtWidgets.QCheckBox(self.page_pat_view_scan_tools_link)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_4.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.page_pat_view_scan_tools_link)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_4.addWidget(self.checkBox_2)
        self.page_pat_view_scan_tools.addItem(self.page_pat_view_scan_tools_link, "")
        self.gridLayout.addWidget(self.page_pat_view_scan_tools, 7, 2, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem13, 0, 7, 1, 1)
        self.page_pat_view_scan_button_zoom_out = QtWidgets.QToolButton(self.page_pat_view_scan)
        self.page_pat_view_scan_button_zoom_out.setMinimumSize(QtCore.QSize(100, 0))
        self.page_pat_view_scan_button_zoom_out.setMaximumSize(QtCore.QSize(100, 16777215))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/zoom_out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_pat_view_scan_button_zoom_out.setIcon(icon6)
        self.page_pat_view_scan_button_zoom_out.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_pat_view_scan_button_zoom_out.setObjectName("page_pat_view_scan_button_zoom_out")
        self.gridLayout_4.addWidget(self.page_pat_view_scan_button_zoom_out, 0, 11, 1, 1)
        self.page_pat_view_scan_button_logout = QtWidgets.QToolButton(self.page_pat_view_scan)
        self.page_pat_view_scan_button_logout.setMinimumSize(QtCore.QSize(100, 0))
        self.page_pat_view_scan_button_logout.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_pat_view_scan_button_logout.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.page_pat_view_scan_button_logout.setIcon(icon3)
        self.page_pat_view_scan_button_logout.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_pat_view_scan_button_logout.setObjectName("page_pat_view_scan_button_logout")
        self.gridLayout_4.addWidget(self.page_pat_view_scan_button_logout, 0, 15, 1, 1)
        self.page_pat_view_scan_button_3d_fullscreen = QtWidgets.QToolButton(self.page_pat_view_scan)
        self.page_pat_view_scan_button_3d_fullscreen.setMinimumSize(QtCore.QSize(100, 0))
        self.page_pat_view_scan_button_3d_fullscreen.setMaximumSize(QtCore.QSize(100, 16777215))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/full_screen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_pat_view_scan_button_3d_fullscreen.setIcon(icon7)
        self.page_pat_view_scan_button_3d_fullscreen.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_pat_view_scan_button_3d_fullscreen.setObjectName("page_pat_view_scan_button_3d_fullscreen")
        self.gridLayout_4.addWidget(self.page_pat_view_scan_button_3d_fullscreen, 0, 12, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem14, 0, 13, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem15, 0, 1, 1, 1)
        self.page_pat_view_scan_button_next_note = QtWidgets.QToolButton(self.page_pat_view_scan)
        self.page_pat_view_scan_button_next_note.setMinimumSize(QtCore.QSize(100, 0))
        self.page_pat_view_scan_button_next_note.setMaximumSize(QtCore.QSize(100, 16777215))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/next_note.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_pat_view_scan_button_next_note.setIcon(icon8)
        self.page_pat_view_scan_button_next_note.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_pat_view_scan_button_next_note.setObjectName("page_pat_view_scan_button_next_note")
        self.gridLayout_4.addWidget(self.page_pat_view_scan_button_next_note, 0, 5, 1, 1)
        self.page_pat_view_scan_button_back = QtWidgets.QToolButton(self.page_pat_view_scan)
        self.page_pat_view_scan_button_back.setMinimumSize(QtCore.QSize(100, 0))
        self.page_pat_view_scan_button_back.setMaximumSize(QtCore.QSize(100, 16777215))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_pat_view_scan_button_back.setIcon(icon9)
        self.page_pat_view_scan_button_back.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_pat_view_scan_button_back.setObjectName("page_pat_view_scan_button_back")
        self.gridLayout_4.addWidget(self.page_pat_view_scan_button_back, 0, 0, 1, 1)
        self.page_pat_view_scan_button_next_slice = QtWidgets.QToolButton(self.page_pat_view_scan)
        self.page_pat_view_scan_button_next_slice.setMinimumSize(QtCore.QSize(100, 0))
        self.page_pat_view_scan_button_next_slice.setMaximumSize(QtCore.QSize(100, 16777215))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icons/next_slice.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_pat_view_scan_button_next_slice.setIcon(icon10)
        self.page_pat_view_scan_button_next_slice.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_pat_view_scan_button_next_slice.setObjectName("page_pat_view_scan_button_next_slice")
        self.gridLayout_4.addWidget(self.page_pat_view_scan_button_next_slice, 0, 6, 1, 1)
        self.page_pat_view_scan_button_play_pause = QtWidgets.QToolButton(self.page_pat_view_scan)
        self.page_pat_view_scan_button_play_pause.setMinimumSize(QtCore.QSize(100, 0))
        self.page_pat_view_scan_button_play_pause.setMaximumSize(QtCore.QSize(100, 16777215))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("icons/play_pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_pat_view_scan_button_play_pause.setIcon(icon11)
        self.page_pat_view_scan_button_play_pause.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_pat_view_scan_button_play_pause.setObjectName("page_pat_view_scan_button_play_pause")
        self.gridLayout_4.addWidget(self.page_pat_view_scan_button_play_pause, 0, 4, 1, 1)
        self.page_pat_view_scan_button_zoom_in = QtWidgets.QToolButton(self.page_pat_view_scan)
        self.page_pat_view_scan_button_zoom_in.setMinimumSize(QtCore.QSize(100, 0))
        self.page_pat_view_scan_button_zoom_in.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.page_pat_view_scan_button_zoom_in.setFont(font)
        self.page_pat_view_scan_button_zoom_in.setStyleSheet("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("icons/zoom_in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_pat_view_scan_button_zoom_in.setIcon(icon12)
        self.page_pat_view_scan_button_zoom_in.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_pat_view_scan_button_zoom_in.setObjectName("page_pat_view_scan_button_zoom_in")
        self.gridLayout_4.addWidget(self.page_pat_view_scan_button_zoom_in, 0, 10, 1, 1)
        self.page_pat_view_scan_button_previous_slice = QtWidgets.QToolButton(self.page_pat_view_scan)
        self.page_pat_view_scan_button_previous_slice.setMinimumSize(QtCore.QSize(100, 0))
        self.page_pat_view_scan_button_previous_slice.setMaximumSize(QtCore.QSize(100, 16777215))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("icons/previous_slice.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_pat_view_scan_button_previous_slice.setIcon(icon13)
        self.page_pat_view_scan_button_previous_slice.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_pat_view_scan_button_previous_slice.setObjectName("page_pat_view_scan_button_previous_slice")
        self.gridLayout_4.addWidget(self.page_pat_view_scan_button_previous_slice, 0, 2, 1, 1)
        self.page_pat_view_scan_button_previous_note = QtWidgets.QToolButton(self.page_pat_view_scan)
        self.page_pat_view_scan_button_previous_note.setMinimumSize(QtCore.QSize(100, 0))
        self.page_pat_view_scan_button_previous_note.setMaximumSize(QtCore.QSize(100, 16777215))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("icons/previous_note.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_pat_view_scan_button_previous_note.setIcon(icon14)
        self.page_pat_view_scan_button_previous_note.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_pat_view_scan_button_previous_note.setObjectName("page_pat_view_scan_button_previous_note")
        self.gridLayout_4.addWidget(self.page_pat_view_scan_button_previous_note, 0, 3, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem16, 0, 9, 1, 1)
        self.page_pat_view_scan_button_link_windows = QtWidgets.QToolButton(self.page_pat_view_scan)
        self.page_pat_view_scan_button_link_windows.setMinimumSize(QtCore.QSize(100, 0))
        self.page_pat_view_scan_button_link_windows.setMaximumSize(QtCore.QSize(100, 16777215))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("icons/link.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_pat_view_scan_button_link_windows.setIcon(icon15)
        self.page_pat_view_scan_button_link_windows.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_pat_view_scan_button_link_windows.setObjectName("page_pat_view_scan_button_link_windows")
        self.gridLayout_4.addWidget(self.page_pat_view_scan_button_link_windows, 0, 8, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 0, 1, 1, 2)
        self.page_pat_view_scan_3d_view_frame = QtWidgets.QFrame(self.page_pat_view_scan)
        self.page_pat_view_scan_3d_view_frame.setMinimumSize(QtCore.QSize(300, 300))
        self.page_pat_view_scan_3d_view_frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.page_pat_view_scan_3d_view_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.page_pat_view_scan_3d_view_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_pat_view_scan_3d_view_frame.setObjectName("page_pat_view_scan_3d_view_frame")
        self.page_pat_view_scan_3d_view_frame_grid = QtWidgets.QGridLayout(self.page_pat_view_scan_3d_view_frame)
        self.page_pat_view_scan_3d_view_frame_grid.setContentsMargins(0, 0, 0, 0)
        self.page_pat_view_scan_3d_view_frame_grid.setObjectName("page_pat_view_scan_3d_view_frame_grid")
        self.page_pat_view_scan_3d_view = QtWidgets.QWidget(self.page_pat_view_scan_3d_view_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_pat_view_scan_3d_view.sizePolicy().hasHeightForWidth())
        self.page_pat_view_scan_3d_view.setSizePolicy(sizePolicy)
        self.page_pat_view_scan_3d_view.setStyleSheet("background-color: rgb(170, 85, 255);")
        self.page_pat_view_scan_3d_view.setObjectName("page_pat_view_scan_3d_view")
        self.page_pat_view_scan_3d_view_frame_grid.addWidget(self.page_pat_view_scan_3d_view, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.page_pat_view_scan_3d_view_frame, 3, 2, 2, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem17, 1, 0, 1, 1)
        self.page_pat_view_scan_button_left = QtWidgets.QPushButton(self.page_pat_view_scan)
        self.page_pat_view_scan_button_left.setMinimumSize(QtCore.QSize(100, 0))
        self.page_pat_view_scan_button_left.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_pat_view_scan_button_left.setObjectName("page_pat_view_scan_button_left")
        self.gridLayout_3.addWidget(self.page_pat_view_scan_button_left, 6, 1, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem18, 5, 5, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_3.addItem(spacerItem19, 0, 2, 1, 1)
        self.page_pat_view_scan_button_right = QtWidgets.QPushButton(self.page_pat_view_scan)
        self.page_pat_view_scan_button_right.setMinimumSize(QtCore.QSize(100, 0))
        self.page_pat_view_scan_button_right.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_pat_view_scan_button_right.setObjectName("page_pat_view_scan_button_right")
        self.gridLayout_3.addWidget(self.page_pat_view_scan_button_right, 6, 3, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_3.addItem(spacerItem20, 2, 2, 1, 1)
        self.page_pat_view_scan_button_down = QtWidgets.QPushButton(self.page_pat_view_scan)
        self.page_pat_view_scan_button_down.setMinimumSize(QtCore.QSize(100, 0))
        self.page_pat_view_scan_button_down.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_pat_view_scan_button_down.setObjectName("page_pat_view_scan_button_down")
        self.gridLayout_3.addWidget(self.page_pat_view_scan_button_down, 6, 2, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_3.addItem(spacerItem21, 7, 2, 1, 1)
        self.page_pat_view_scan_button_up = QtWidgets.QPushButton(self.page_pat_view_scan)
        self.page_pat_view_scan_button_up.setMinimumSize(QtCore.QSize(100, 0))
        self.page_pat_view_scan_button_up.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_pat_view_scan_button_up.setObjectName("page_pat_view_scan_button_up")
        self.gridLayout_3.addWidget(self.page_pat_view_scan_button_up, 5, 2, 1, 1)
        self.page_pat_view_scan_button_3d_bone_view = QtWidgets.QPushButton(self.page_pat_view_scan)
        self.page_pat_view_scan_button_3d_bone_view.setMinimumSize(QtCore.QSize(100, 0))
        self.page_pat_view_scan_button_3d_bone_view.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_pat_view_scan_button_3d_bone_view.setObjectName("page_pat_view_scan_button_3d_bone_view")
        self.gridLayout_3.addWidget(self.page_pat_view_scan_button_3d_bone_view, 1, 1, 1, 1)
        self.page_pat_view_scan_button_3d_tissue_view = QtWidgets.QPushButton(self.page_pat_view_scan)
        self.page_pat_view_scan_button_3d_tissue_view.setMinimumSize(QtCore.QSize(100, 0))
        self.page_pat_view_scan_button_3d_tissue_view.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_pat_view_scan_button_3d_tissue_view.setObjectName("page_pat_view_scan_button_3d_tissue_view")
        self.gridLayout_3.addWidget(self.page_pat_view_scan_button_3d_tissue_view, 1, 3, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 9, 1, 1, 1)
        pat.addWidget(self.page_pat_view_scan)

        self.retranslateUi(pat)
        pat.setCurrentIndex(4)
        self.page_pat_view_scan_tools.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(pat)
        pat.setTabOrder(self.page_pat_view_scan_button_logout, self.page_pat_home_textEdit_search)
        pat.setTabOrder(self.page_pat_home_textEdit_search, self.page_pat_home_treeWidget_treatment_list)
        pat.setTabOrder(self.page_pat_home_treeWidget_treatment_list, self.page_pat_home_button_proceed)
        pat.setTabOrder(self.page_pat_home_button_proceed, self.page_pat_errand_treeWidget_errand_list)
        pat.setTabOrder(self.page_pat_errand_treeWidget_errand_list, self.page_pat_errand_button_view_status)
        pat.setTabOrder(self.page_pat_errand_button_view_status, self.page_pat_errand_button_download)
        pat.setTabOrder(self.page_pat_errand_button_download, self.page_pat_errand_button_view)
        pat.setTabOrder(self.page_pat_errand_button_view, self.page_pat_errand_report)
        pat.setTabOrder(self.page_pat_errand_report, self.page_pat_errand_logout)
        pat.setTabOrder(self.page_pat_errand_logout, self.page_pat_errand_report_textEdit_search)
        pat.setTabOrder(self.page_pat_errand_report_textEdit_search, self.page_pat_my_profile_button_back)
        pat.setTabOrder(self.page_pat_my_profile_button_back, self.page_pat_my_profile_textBrowser)
        pat.setTabOrder(self.page_pat_my_profile_textBrowser, self.page_pat_image_status_textBrowser_detailed_information)
        pat.setTabOrder(self.page_pat_image_status_textBrowser_detailed_information, self.page_pat_image_status_button_back)
        pat.setTabOrder(self.page_pat_image_status_button_back, self.page_pat_image_status_button_request_notification)
        pat.setTabOrder(self.page_pat_image_status_button_request_notification, self.page_pat_image_status_button_logout)
        pat.setTabOrder(self.page_pat_image_status_button_logout, self.page_pat_view_scan_button_previous_note)
        pat.setTabOrder(self.page_pat_view_scan_button_previous_note, self.page_pat_view_scan_button_previous_slice)
        pat.setTabOrder(self.page_pat_view_scan_button_previous_slice, self.page_pat_view_scan_button_play_pause)
        pat.setTabOrder(self.page_pat_view_scan_button_play_pause, self.page_pat_view_scan_button_next_note)
        pat.setTabOrder(self.page_pat_view_scan_button_next_note, self.page_pat_view_scan_button_next_slice)
        pat.setTabOrder(self.page_pat_view_scan_button_next_slice, self.page_pat_view_scan_button_right)
        pat.setTabOrder(self.page_pat_view_scan_button_right, self.page_pat_view_scan_button_left)
        pat.setTabOrder(self.page_pat_view_scan_button_left, self.page_pat_view_scan_button_up)
        pat.setTabOrder(self.page_pat_view_scan_button_up, self.page_pat_view_scan_button_down)
        pat.setTabOrder(self.page_pat_view_scan_button_down, self.page_pat_view_scan_button_link_windows)

    def retranslateUi(self, pat):
        _translate = QtCore.QCoreApplication.translate
        pat.setWindowTitle(_translate("pat", "StackedWidget"))
        self.page_pat_home_button_proceed.setText(_translate("pat", "Proceed"))
        self.page_pat_home_logout.setText(_translate("pat", "Logout"))
        self.page_pat_home_textEdit_search.setHtml(_translate("pat", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">Search box</span></p></body></html>"))
        self.page_pat_home_treeWidget_treatment_list.setSortingEnabled(True)
        self.page_pat_home_treeWidget_treatment_list.headerItem().setText(0, _translate("pat", "Patient ID"))
        self.page_pat_home_treeWidget_treatment_list.headerItem().setText(1, _translate("pat", "Date ordered"))
        self.page_pat_home_treeWidget_treatment_list.headerItem().setText(2, _translate("pat", "Order ID"))
        self.page_pat_home_treeWidget_treatment_list.headerItem().setText(3, _translate("pat", "Status"))
        self.page_pat_home_button_my_profile.setText(_translate("pat", "Profile"))
        self.page_pat_errand_treeWidget_errand_list.setSortingEnabled(True)
        self.page_pat_errand_treeWidget_errand_list.headerItem().setText(0, _translate("pat", "Order ID"))
        self.page_pat_errand_treeWidget_errand_list.headerItem().setText(1, _translate("pat", "Date"))
        self.page_pat_errand_treeWidget_errand_list.headerItem().setText(2, _translate("pat", "Task"))
        self.page_pat_errand_treeWidget_errand_list.headerItem().setText(3, _translate("pat", "Scan"))
        self.page_pat_errand_treeWidget_errand_list.headerItem().setText(4, _translate("pat", "Status"))
        self.page_pat_errand_treeWidget_errand_list.headerItem().setText(5, _translate("pat", "Clinic"))
        self.page_pat_errand_label_errands.setText(_translate("pat", "Errands"))
        self.page_pat_errand_button_view_status.setText(_translate("pat", "View Status"))
        self.page_pat_errand_button_share.setText(_translate("pat", "Share"))
        self.page_pat_errand_logout.setText(_translate("pat", "Logout"))
        self.page_pat_errand_label_company_name.setText(_translate("pat", "CLARITY"))
        self.page_pat_errand_button_download.setText(_translate("pat", "Download"))
        self.page_pat_errand_report.setPlaceholderText(_translate("pat", "Select a completed errand to see radiology report"))
        self.page_pat_errand_button_view.setText(_translate("pat", "View"))
        self.page_pat_errand_label_report.setText(_translate("pat", "Report"))
        self.page_pat_errand_button_back.setText(_translate("pat", "Profile"))
        self.page_pat_errand_report_textEdit_search.setPlaceholderText(_translate("pat", "Search..."))
        self.page_pat_my_profile_button_back.setText(_translate("pat", "Back"))
        self.page_pat_image_status_button_back.setText(_translate("pat", "Back"))
        self.page_pat_image_status_button_request_notification.setText(_translate("pat", "Request\n"
"notifications"))
        self.page_pat_image_status_button_logout.setText(_translate("pat", "Logout"))
        self.radioButton.setText(_translate("pat", "Axial View"))
        self.radioButton_2.setText(_translate("pat", "Sagittal View"))
        self.radioButton_3.setText(_translate("pat", "Coronal View"))
        self.page_pat_view_scan_tools.setItemText(self.page_pat_view_scan_tools.indexOf(self.page_pat_view_scan_tools_orientation), _translate("pat", "2D Orientation"))
        self.checkBox_All.setText(_translate("pat", "All"))
        self.checkBox_Soft.setText(_translate("pat", "Soft"))
        self.checkBox_Bone.setText(_translate("pat", "Bone"))
        self.checkBox_Muscle.setText(_translate("pat", "Muscle"))
        self.checkBox_Fat.setText(_translate("pat", "Fat"))
        self.checkBox_Skin.setText(_translate("pat", "Skin"))
        self.page_pat_view_scan_tools.setItemText(self.page_pat_view_scan_tools.indexOf(self.page_pat_view_scan_tools_tissue), _translate("pat", "3D Tissues"))
        self.page_pat_view_scan_label_transparency_volume.setText(_translate("pat", "3D Volume"))
        self.page_pat_view_scan_label_transparency_segmentation.setText(_translate("pat", "Segmentations"))
        self.page_pat_view_scan_label_transparency_active.setText(_translate("pat", "Active Segment"))
        self.page_pat_view_scan_tools.setItemText(self.page_pat_view_scan_tools.indexOf(self.page_pat_view_scan_tools_transparency), _translate("pat", "3D Transparency"))
        self.checkBox.setText(_translate("pat", "Show 2D Image"))
        self.checkBox_2.setText(_translate("pat", "Show Full 3D Volume"))
        self.page_pat_view_scan_tools.setItemText(self.page_pat_view_scan_tools.indexOf(self.page_pat_view_scan_tools_link), _translate("pat", "3D Link "))
        self.page_pat_view_scan_button_zoom_out.setText(_translate("pat", "Zoom Out"))
        self.page_pat_view_scan_button_logout.setText(_translate("pat", "Logout"))
        self.page_pat_view_scan_button_3d_fullscreen.setText(_translate("pat", "Full Screen"))
        self.page_pat_view_scan_button_next_note.setText(_translate("pat", "Next Note"))
        self.page_pat_view_scan_button_back.setText(_translate("pat", "Back"))
        self.page_pat_view_scan_button_next_slice.setText(_translate("pat", "Next Slice"))
        self.page_pat_view_scan_button_play_pause.setText(_translate("pat", "Play/Pause"))
        self.page_pat_view_scan_button_zoom_in.setText(_translate("pat", "Zoom In"))
        self.page_pat_view_scan_button_previous_slice.setText(_translate("pat", "Previous Slice"))
        self.page_pat_view_scan_button_previous_note.setText(_translate("pat", "Previous Note"))
        self.page_pat_view_scan_button_link_windows.setText(_translate("pat", "Activate\n"
"2D-3D Link"))
        self.page_pat_view_scan_button_left.setText(_translate("pat", "Left"))
        self.page_pat_view_scan_button_right.setText(_translate("pat", "Right"))
        self.page_pat_view_scan_button_down.setText(_translate("pat", "Down"))
        self.page_pat_view_scan_button_up.setText(_translate("pat", "Up"))
        self.page_pat_view_scan_button_3d_bone_view.setText(_translate("pat", "Bone View"))
        self.page_pat_view_scan_button_3d_tissue_view.setText(_translate("pat", "Tissue View"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    pat = QtWidgets.QStackedWidget()
    ui = Ui_pat()
    ui.setupUi(pat)
    pat.show()
    sys.exit(app.exec_())

