# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rad.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_rad(object):
    def setupUi(self, rad):
        rad.setObjectName("rad")
        rad.resize(1045, 789)
        self.page_rad_home = QtWidgets.QWidget()
        self.page_rad_home.setObjectName("page_rad_home")
        self.gridLayout = QtWidgets.QGridLayout(self.page_rad_home)
        self.gridLayout.setObjectName("gridLayout")
        self.page_rad_home_button_colleagues = QtWidgets.QPushButton(self.page_rad_home)
        self.page_rad_home_button_colleagues.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_home_button_colleagues.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_home_button_colleagues.setObjectName("page_rad_home_button_colleagues")
        self.gridLayout.addWidget(self.page_rad_home_button_colleagues, 0, 1, 1, 1)
        self.page_rad_home_button_view_profile = QtWidgets.QPushButton(self.page_rad_home)
        self.page_rad_home_button_view_profile.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_home_button_view_profile.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_home_button_view_profile.setObjectName("page_rad_home_button_view_profile")
        self.gridLayout.addWidget(self.page_rad_home_button_view_profile, 0, 0, 1, 1)
        self.page_rad_home_search_bar = QtWidgets.QTextEdit(self.page_rad_home)
        self.page_rad_home_search_bar.setMaximumSize(QtCore.QSize(200, 25))
        self.page_rad_home_search_bar.setObjectName("page_rad_home_search_bar")
        self.gridLayout.addWidget(self.page_rad_home_search_bar, 1, 6, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 5, 2, 1, 4)
        self.page_rad_home_patient_information = QtWidgets.QTreeWidget(self.page_rad_home)
        self.page_rad_home_patient_information.setMinimumSize(QtCore.QSize(371, 0))
        self.page_rad_home_patient_information.setObjectName("page_rad_home_patient_information")
        self.gridLayout.addWidget(self.page_rad_home_patient_information, 3, 2, 1, 5)
        self.page_rad_home_button_logout = QtWidgets.QPushButton(self.page_rad_home)
        self.page_rad_home_button_logout.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_home_button_logout.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_home_button_logout.setObjectName("page_rad_home_button_logout")
        self.gridLayout.addWidget(self.page_rad_home_button_logout, 0, 8, 1, 1)
        self.page_rad_home_button_proceed = QtWidgets.QPushButton(self.page_rad_home)
        self.page_rad_home_button_proceed.setEnabled(False)
        self.page_rad_home_button_proceed.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_home_button_proceed.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_home_button_proceed.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.page_rad_home_button_proceed.setObjectName("page_rad_home_button_proceed")
        self.gridLayout.addWidget(self.page_rad_home_button_proceed, 5, 6, 1, 1)
        self.page_rad_home_button_lock_screen = QtWidgets.QPushButton(self.page_rad_home)
        self.page_rad_home_button_lock_screen.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_home_button_lock_screen.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_home_button_lock_screen.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.page_rad_home_button_lock_screen.setObjectName("page_rad_home_button_lock_screen")
        self.gridLayout.addWidget(self.page_rad_home_button_lock_screen, 0, 6, 1, 1)
        rad.addWidget(self.page_rad_home)
        self.page_rad_view_only = QtWidgets.QWidget()
        self.page_rad_view_only.setObjectName("page_rad_view_only")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_rad_view_only)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.page_rad_view_only_button_logout = QtWidgets.QPushButton(self.page_rad_view_only)
        self.page_rad_view_only_button_logout.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_view_only_button_logout.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_view_only_button_logout.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.page_rad_view_only_button_logout.setObjectName("page_rad_view_only_button_logout")
        self.horizontalLayout_3.addWidget(self.page_rad_view_only_button_logout)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 0, 2, 1, 1)
        self.page_rad_view_only_radiology_report_frame = QtWidgets.QFrame(self.page_rad_view_only)
        self.page_rad_view_only_radiology_report_frame.setMinimumSize(QtCore.QSize(200, 300))
        self.page_rad_view_only_radiology_report_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.page_rad_view_only_radiology_report_frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.page_rad_view_only_radiology_report_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.page_rad_view_only_radiology_report_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_rad_view_only_radiology_report_frame.setObjectName("page_rad_view_only_radiology_report_frame")
        self.label = QtWidgets.QLabel(self.page_rad_view_only_radiology_report_frame)
        self.label.setGeometry(QtCore.QRect(100, 100, 201, 101))
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.page_rad_view_only_radiology_report_frame, 3, 2, 1, 1)
        self.page_rad_view_only_3d_view_frame = QtWidgets.QFrame(self.page_rad_view_only)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_rad_view_only_3d_view_frame.sizePolicy().hasHeightForWidth())
        self.page_rad_view_only_3d_view_frame.setSizePolicy(sizePolicy)
        self.page_rad_view_only_3d_view_frame.setMinimumSize(QtCore.QSize(200, 200))
        self.page_rad_view_only_3d_view_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.page_rad_view_only_3d_view_frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.page_rad_view_only_3d_view_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.page_rad_view_only_3d_view_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_rad_view_only_3d_view_frame.setObjectName("page_rad_view_only_3d_view_frame")
        self.page_rad_view_only_3d_view_frame_grid = QtWidgets.QGridLayout(self.page_rad_view_only_3d_view_frame)
        self.page_rad_view_only_3d_view_frame_grid.setContentsMargins(0, 0, 0, 0)
        self.page_rad_view_only_3d_view_frame_grid.setObjectName("page_rad_view_only_3d_view_frame_grid")
        self.page_rad_view_only_3d_view = QtWidgets.QWidget(self.page_rad_view_only_3d_view_frame)
        self.page_rad_view_only_3d_view.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.page_rad_view_only_3d_view.setObjectName("page_rad_view_only_3d_view")
        self.page_rad_view_only_3d_view_frame_grid.addWidget(self.page_rad_view_only_3d_view, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.page_rad_view_only_3d_view_frame, 2, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.page_rad_view_only_button_hide_3d = QtWidgets.QPushButton(self.page_rad_view_only)
        self.page_rad_view_only_button_hide_3d.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_view_only_button_hide_3d.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_view_only_button_hide_3d.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.page_rad_view_only_button_hide_3d.setObjectName("page_rad_view_only_button_hide_3d")
        self.horizontalLayout.addWidget(self.page_rad_view_only_button_hide_3d)
        self.page_rad_view_only_button_3d_fullscreen = QtWidgets.QPushButton(self.page_rad_view_only)
        self.page_rad_view_only_button_3d_fullscreen.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_view_only_button_3d_fullscreen.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_view_only_button_3d_fullscreen.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.page_rad_view_only_button_3d_fullscreen.setObjectName("page_rad_view_only_button_3d_fullscreen")
        self.horizontalLayout.addWidget(self.page_rad_view_only_button_3d_fullscreen)
        self.gridLayout_4.addLayout(self.horizontalLayout, 1, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.page_rad_view_only_button_2d_fullscreen = QtWidgets.QPushButton(self.page_rad_view_only)
        self.page_rad_view_only_button_2d_fullscreen.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_view_only_button_2d_fullscreen.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_view_only_button_2d_fullscreen.setObjectName("page_rad_view_only_button_2d_fullscreen")
        self.horizontalLayout_2.addWidget(self.page_rad_view_only_button_2d_fullscreen)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.page_rad_view_only_button_back = QtWidgets.QPushButton(self.page_rad_view_only)
        self.page_rad_view_only_button_back.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_view_only_button_back.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_view_only_button_back.setObjectName("page_rad_view_only_button_back")
        self.gridLayout_4.addWidget(self.page_rad_view_only_button_back, 7, 0, 1, 1)
        self.page_rad_view_only_button_diagnose = QtWidgets.QPushButton(self.page_rad_view_only)
        self.page_rad_view_only_button_diagnose.setEnabled(False)
        self.page_rad_view_only_button_diagnose.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_view_only_button_diagnose.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_view_only_button_diagnose.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.page_rad_view_only_button_diagnose.setObjectName("page_rad_view_only_button_diagnose")
        self.gridLayout_4.addWidget(self.page_rad_view_only_button_diagnose, 7, 2, 1, 1)
        self.page_rad_view_only_2d_view_frame = QtWidgets.QFrame(self.page_rad_view_only)
        self.page_rad_view_only_2d_view_frame.setMinimumSize(QtCore.QSize(400, 400))
        self.page_rad_view_only_2d_view_frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.page_rad_view_only_2d_view_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.page_rad_view_only_2d_view_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_rad_view_only_2d_view_frame.setObjectName("page_rad_view_only_2d_view_frame")
        self.page_rad_view_only_2d_view_frame_grid = QtWidgets.QGridLayout(self.page_rad_view_only_2d_view_frame)
        self.page_rad_view_only_2d_view_frame_grid.setContentsMargins(0, 0, 0, 0)
        self.page_rad_view_only_2d_view_frame_grid.setObjectName("page_rad_view_only_2d_view_frame_grid")
        self.page_rad_view_only_2d_view = QtWidgets.QWidget(self.page_rad_view_only_2d_view_frame)
        self.page_rad_view_only_2d_view.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.page_rad_view_only_2d_view.setObjectName("page_rad_view_only_2d_view")
        self.page_rad_view_only_2d_view_frame_grid.addWidget(self.page_rad_view_only_2d_view, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.page_rad_view_only_2d_view_frame, 2, 0, 2, 2)
        rad.addWidget(self.page_rad_view_only)
        self.page_rad_diagnose = QtWidgets.QWidget()
        self.page_rad_diagnose.setObjectName("page_rad_diagnose")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.page_rad_diagnose)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.page_rad_diagnose_2d_view_frame = QtWidgets.QFrame(self.page_rad_diagnose)
        self.page_rad_diagnose_2d_view_frame.setMinimumSize(QtCore.QSize(400, 400))
        self.page_rad_diagnose_2d_view_frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.page_rad_diagnose_2d_view_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.page_rad_diagnose_2d_view_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_rad_diagnose_2d_view_frame.setObjectName("page_rad_diagnose_2d_view_frame")
        self.page_rad_diagnose_2d_view_frame_grid = QtWidgets.QGridLayout(self.page_rad_diagnose_2d_view_frame)
        self.page_rad_diagnose_2d_view_frame_grid.setContentsMargins(0, 0, 0, 0)
        self.page_rad_diagnose_2d_view_frame_grid.setObjectName("page_rad_diagnose_2d_view_frame_grid")
        self.page_rad_diagnose_2d_view = QtWidgets.QWidget(self.page_rad_diagnose_2d_view_frame)
        self.page_rad_diagnose_2d_view.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.page_rad_diagnose_2d_view.setObjectName("page_rad_diagnose_2d_view")
        self.page_rad_diagnose_2d_view_frame_grid.addWidget(self.page_rad_diagnose_2d_view, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.page_rad_diagnose_2d_view_frame, 4, 2, 2, 1)
        self.page_rad_diagnose_button_back = QtWidgets.QPushButton(self.page_rad_diagnose)
        self.page_rad_diagnose_button_back.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_diagnose_button_back.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_diagnose_button_back.setObjectName("page_rad_diagnose_button_back")
        self.gridLayout_10.addWidget(self.page_rad_diagnose_button_back, 6, 2, 1, 1)
        self.page_rad_diagnose_3d_view_frame = QtWidgets.QFrame(self.page_rad_diagnose)
        self.page_rad_diagnose_3d_view_frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.page_rad_diagnose_3d_view_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.page_rad_diagnose_3d_view_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_rad_diagnose_3d_view_frame.setObjectName("page_rad_diagnose_3d_view_frame")
        self.page_rad_diagnose_3d_view_frame_grid = QtWidgets.QGridLayout(self.page_rad_diagnose_3d_view_frame)
        self.page_rad_diagnose_3d_view_frame_grid.setContentsMargins(0, 0, 0, 0)
        self.page_rad_diagnose_3d_view_frame_grid.setObjectName("page_rad_diagnose_3d_view_frame_grid")
        self.page_rad_diagnose_3d_view = QtWidgets.QWidget(self.page_rad_diagnose_3d_view_frame)
        self.page_rad_diagnose_3d_view.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.page_rad_diagnose_3d_view.setObjectName("page_rad_diagnose_3d_view")
        self.page_rad_diagnose_3d_view_frame_grid.addWidget(self.page_rad_diagnose_3d_view, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.page_rad_diagnose_3d_view_frame, 4, 5, 1, 1)
        self.page_rad_diagnose_button_preview_report = QtWidgets.QPushButton(self.page_rad_diagnose)
        self.page_rad_diagnose_button_preview_report.setMinimumSize(QtCore.QSize(125, 0))
        self.page_rad_diagnose_button_preview_report.setMaximumSize(QtCore.QSize(125, 16777215))
        self.page_rad_diagnose_button_preview_report.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.page_rad_diagnose_button_preview_report.setObjectName("page_rad_diagnose_button_preview_report")
        self.gridLayout_10.addWidget(self.page_rad_diagnose_button_preview_report, 6, 5, 1, 1)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.page_rad_diagnose_button_2d_fullscreen = QtWidgets.QPushButton(self.page_rad_diagnose)
        self.page_rad_diagnose_button_2d_fullscreen.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_diagnose_button_2d_fullscreen.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_diagnose_button_2d_fullscreen.setObjectName("page_rad_diagnose_button_2d_fullscreen")
        self.gridLayout_12.addWidget(self.page_rad_diagnose_button_2d_fullscreen, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem5, 0, 1, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_12, 2, 2, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.page_rad_diagnose_button_logout = QtWidgets.QPushButton(self.page_rad_diagnose)
        self.page_rad_diagnose_button_logout.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_diagnose_button_logout.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_diagnose_button_logout.setObjectName("page_rad_diagnose_button_logout")
        self.gridLayout_9.addWidget(self.page_rad_diagnose_button_logout, 0, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem6, 0, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_9, 0, 5, 1, 1)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.page_rad_diagnose_button_3d_fullscreen = QtWidgets.QPushButton(self.page_rad_diagnose)
        self.page_rad_diagnose_button_3d_fullscreen.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_diagnose_button_3d_fullscreen.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_diagnose_button_3d_fullscreen.setObjectName("page_rad_diagnose_button_3d_fullscreen")
        self.gridLayout_11.addWidget(self.page_rad_diagnose_button_3d_fullscreen, 0, 2, 1, 1)
        self.page_rad_diagnose_button_hide_3d = QtWidgets.QPushButton(self.page_rad_diagnose)
        self.page_rad_diagnose_button_hide_3d.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_diagnose_button_hide_3d.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_diagnose_button_hide_3d.setObjectName("page_rad_diagnose_button_hide_3d")
        self.gridLayout_11.addWidget(self.page_rad_diagnose_button_hide_3d, 0, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem7, 0, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_11, 2, 5, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem8, 4, 3, 1, 1)
        self.page_rad_diagnose_button_add_annotation = QtWidgets.QPushButton(self.page_rad_diagnose)
        self.page_rad_diagnose_button_add_annotation.setMinimumSize(QtCore.QSize(125, 0))
        self.page_rad_diagnose_button_add_annotation.setMaximumSize(QtCore.QSize(125, 16777215))
        self.page_rad_diagnose_button_add_annotation.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.page_rad_diagnose_button_add_annotation.setObjectName("page_rad_diagnose_button_add_annotation")
        self.gridLayout_8.addWidget(self.page_rad_diagnose_button_add_annotation, 4, 4, 1, 1)
        self.page_rad_diagnose_button_2d_zoom_out = QtWidgets.QPushButton(self.page_rad_diagnose)
        self.page_rad_diagnose_button_2d_zoom_out.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_diagnose_button_2d_zoom_out.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_diagnose_button_2d_zoom_out.setObjectName("page_rad_diagnose_button_2d_zoom_out")
        self.gridLayout_8.addWidget(self.page_rad_diagnose_button_2d_zoom_out, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.page_rad_diagnose)
        self.label_2.setObjectName("label_2")
        self.gridLayout_8.addWidget(self.label_2, 2, 2, 1, 1)
        self.page_rad_diagnose_button_2d_zoom_in = QtWidgets.QPushButton(self.page_rad_diagnose)
        self.page_rad_diagnose_button_2d_zoom_in.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_diagnose_button_2d_zoom_in.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_diagnose_button_2d_zoom_in.setObjectName("page_rad_diagnose_button_2d_zoom_in")
        self.gridLayout_8.addWidget(self.page_rad_diagnose_button_2d_zoom_in, 1, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_8.addItem(spacerItem9, 0, 1, 1, 1)
        self.page_rad_diagnose_insert_annotations = QtWidgets.QTextEdit(self.page_rad_diagnose)
        self.page_rad_diagnose_insert_annotations.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.page_rad_diagnose_insert_annotations.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.page_rad_diagnose_insert_annotations.setObjectName("page_rad_diagnose_insert_annotations")
        self.gridLayout_8.addWidget(self.page_rad_diagnose_insert_annotations, 0, 4, 3, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem10, 0, 3, 3, 1)
        self.gridLayout_10.addLayout(self.gridLayout_8, 5, 5, 1, 1)
        rad.addWidget(self.page_rad_diagnose)
        self.page_rad_patient_page = QtWidgets.QWidget()
        self.page_rad_patient_page.setObjectName("page_rad_patient_page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_rad_patient_page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.page_rad_patient_page_scan_info = QtWidgets.QTextBrowser(self.page_rad_patient_page)
        self.page_rad_patient_page_scan_info.setObjectName("page_rad_patient_page_scan_info")
        self.gridLayout_2.addWidget(self.page_rad_patient_page_scan_info, 2, 2, 1, 2)
        self.page_rad_patient_page_patient_infor = QtWidgets.QTextBrowser(self.page_rad_patient_page)
        self.page_rad_patient_page_patient_infor.setObjectName("page_rad_patient_page_patient_infor")
        self.gridLayout_2.addWidget(self.page_rad_patient_page_patient_infor, 1, 1, 2, 1)
        self.page_rad_patient_page_doctors_orders = QtWidgets.QTextBrowser(self.page_rad_patient_page)
        self.page_rad_patient_page_doctors_orders.setObjectName("page_rad_patient_page_doctors_orders")
        self.gridLayout_2.addWidget(self.page_rad_patient_page_doctors_orders, 1, 2, 1, 2)
        self.page_rad_patient_page_button_logout = QtWidgets.QPushButton(self.page_rad_patient_page)
        self.page_rad_patient_page_button_logout.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_patient_page_button_logout.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_patient_page_button_logout.setObjectName("page_rad_patient_page_button_logout")
        self.gridLayout_2.addWidget(self.page_rad_patient_page_button_logout, 0, 5, 1, 1)
        self.page_rad_patient_page_button_back = QtWidgets.QPushButton(self.page_rad_patient_page)
        self.page_rad_patient_page_button_back.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_patient_page_button_back.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_patient_page_button_back.setObjectName("page_rad_patient_page_button_back")
        self.gridLayout_2.addWidget(self.page_rad_patient_page_button_back, 3, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.page_rad_patient_page_button_view_scan = QtWidgets.QPushButton(self.page_rad_patient_page)
        self.page_rad_patient_page_button_view_scan.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_patient_page_button_view_scan.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_patient_page_button_view_scan.setObjectName("page_rad_patient_page_button_view_scan")
        self.gridLayout_3.addWidget(self.page_rad_patient_page_button_view_scan, 0, 2, 1, 1)
        self.page_rad_patient_page_button_diagnose_patient = QtWidgets.QPushButton(self.page_rad_patient_page)
        self.page_rad_patient_page_button_diagnose_patient.setEnabled(False)
        self.page_rad_patient_page_button_diagnose_patient.setMinimumSize(QtCore.QSize(125, 0))
        self.page_rad_patient_page_button_diagnose_patient.setMaximumSize(QtCore.QSize(125, 16777215))
        self.page_rad_patient_page_button_diagnose_patient.setObjectName("page_rad_patient_page_button_diagnose_patient")
        self.gridLayout_3.addWidget(self.page_rad_patient_page_button_diagnose_patient, 0, 3, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem11, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 3, 3, 1, 1)
        self.page_rad_patient_page_button_lock_screen = QtWidgets.QPushButton(self.page_rad_patient_page)
        self.page_rad_patient_page_button_lock_screen.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_patient_page_button_lock_screen.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_patient_page_button_lock_screen.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.page_rad_patient_page_button_lock_screen.setObjectName("page_rad_patient_page_button_lock_screen")
        self.gridLayout_2.addWidget(self.page_rad_patient_page_button_lock_screen, 0, 3, 1, 1)
        rad.addWidget(self.page_rad_patient_page)
        self.page_rad_report = QtWidgets.QWidget()
        self.page_rad_report.setObjectName("page_rad_report")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.page_rad_report)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.page_rad_report_2d_image_frame = QtWidgets.QFrame(self.page_rad_report)
        self.page_rad_report_2d_image_frame.setMinimumSize(QtCore.QSize(300, 300))
        self.page_rad_report_2d_image_frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.page_rad_report_2d_image_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.page_rad_report_2d_image_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_rad_report_2d_image_frame.setObjectName("page_rad_report_2d_image_frame")
        self.page_rad_report_2d_image_frame_grid = QtWidgets.QGridLayout(self.page_rad_report_2d_image_frame)
        self.page_rad_report_2d_image_frame_grid.setObjectName("page_rad_report_2d_image_frame_grid")
        self.page_rad_report_2d_image = QtWidgets.QWidget(self.page_rad_report_2d_image_frame)
        self.page_rad_report_2d_image.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.page_rad_report_2d_image.setObjectName("page_rad_report_2d_image")
        self.page_rad_report_2d_image_frame_grid.addWidget(self.page_rad_report_2d_image, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.page_rad_report_2d_image_frame, 1, 0, 1, 3)
        self.page_rad_report_button_back = QtWidgets.QPushButton(self.page_rad_report)
        self.page_rad_report_button_back.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_report_button_back.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_report_button_back.setObjectName("page_rad_report_button_back")
        self.gridLayout_14.addWidget(self.page_rad_report_button_back, 3, 0, 1, 1)
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_17.addItem(spacerItem12, 3, 3, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem13, 2, 5, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem14, 1, 0, 1, 1)
        self.page_rad_report_button_zoom_out = QtWidgets.QPushButton(self.page_rad_report)
        self.page_rad_report_button_zoom_out.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_report_button_zoom_out.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_report_button_zoom_out.setObjectName("page_rad_report_button_zoom_out")
        self.gridLayout_17.addWidget(self.page_rad_report_button_zoom_out, 2, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.page_rad_report)
        self.label_3.setObjectName("label_3")
        self.gridLayout_17.addWidget(self.label_3, 1, 1, 1, 1)
        self.page_rad_report_button_zoom_in = QtWidgets.QPushButton(self.page_rad_report)
        self.page_rad_report_button_zoom_in.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_report_button_zoom_in.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_report_button_zoom_in.setObjectName("page_rad_report_button_zoom_in")
        self.gridLayout_17.addWidget(self.page_rad_report_button_zoom_in, 1, 3, 1, 1)
        self.page_rad_report_button_surgeon_view = QtWidgets.QPushButton(self.page_rad_report)
        self.page_rad_report_button_surgeon_view.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_report_button_surgeon_view.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_report_button_surgeon_view.setObjectName("page_rad_report_button_surgeon_view")
        self.gridLayout_17.addWidget(self.page_rad_report_button_surgeon_view, 2, 4, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_17.addItem(spacerItem15, 0, 3, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_17, 2, 0, 1, 3)
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.page_rad_report_button_logout = QtWidgets.QPushButton(self.page_rad_report)
        self.page_rad_report_button_logout.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_report_button_logout.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_report_button_logout.setObjectName("page_rad_report_button_logout")
        self.gridLayout_16.addWidget(self.page_rad_report_button_logout, 0, 1, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem16, 0, 0, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_16, 0, 3, 1, 2)
        self.page_rad_report_report_preview = QtWidgets.QTextEdit(self.page_rad_report)
        self.page_rad_report_report_preview.setMinimumSize(QtCore.QSize(500, 0))
        self.page_rad_report_report_preview.setObjectName("page_rad_report_report_preview")
        self.gridLayout_14.addWidget(self.page_rad_report_report_preview, 1, 3, 2, 2)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.page_rad_report_button_fullscreen = QtWidgets.QPushButton(self.page_rad_report)
        self.page_rad_report_button_fullscreen.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_report_button_fullscreen.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_report_button_fullscreen.setObjectName("page_rad_report_button_fullscreen")
        self.gridLayout_15.addWidget(self.page_rad_report_button_fullscreen, 0, 0, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem17, 0, 1, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_15, 0, 0, 1, 2)
        self.page_rad_report_button_send_report = QtWidgets.QPushButton(self.page_rad_report)
        self.page_rad_report_button_send_report.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_report_button_send_report.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_report_button_send_report.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.page_rad_report_button_send_report.setObjectName("page_rad_report_button_send_report")
        self.gridLayout_14.addWidget(self.page_rad_report_button_send_report, 3, 4, 1, 1)
        rad.addWidget(self.page_rad_report)
        self.page_rad_locked = QtWidgets.QWidget()
        self.page_rad_locked.setObjectName("page_rad_locked")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_rad_locked)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem18, 0, 0, 1, 1)
        self.page_rad_locked_insert_password = QtWidgets.QLineEdit(self.page_rad_locked)
        self.page_rad_locked_insert_password.setMinimumSize(QtCore.QSize(200, 0))
        self.page_rad_locked_insert_password.setMaximumSize(QtCore.QSize(200, 16777215))
        self.page_rad_locked_insert_password.setText("")
        self.page_rad_locked_insert_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.page_rad_locked_insert_password.setObjectName("page_rad_locked_insert_password")
        self.gridLayout_7.addWidget(self.page_rad_locked_insert_password, 3, 0, 1, 1)
        self.page_rad_locked_button_login = QtWidgets.QPushButton(self.page_rad_locked)
        self.page_rad_locked_button_login.setMinimumSize(QtCore.QSize(200, 0))
        self.page_rad_locked_button_login.setMaximumSize(QtCore.QSize(200, 16777215))
        self.page_rad_locked_button_login.setObjectName("page_rad_locked_button_login")
        self.gridLayout_7.addWidget(self.page_rad_locked_button_login, 4, 0, 1, 1)
        self.page_rad_incorrect_password = QtWidgets.QLabel(self.page_rad_locked)
        self.page_rad_incorrect_password.setEnabled(True)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.page_rad_incorrect_password.setPalette(palette)
        self.page_rad_incorrect_password.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.page_rad_incorrect_password.setText("")
        self.page_rad_incorrect_password.setAlignment(QtCore.Qt.AlignCenter)
        self.page_rad_incorrect_password.setObjectName("page_rad_incorrect_password")
        self.gridLayout_7.addWidget(self.page_rad_incorrect_password, 2, 0, 1, 1)
        self.page_rad_locked_text = QtWidgets.QTextBrowser(self.page_rad_locked)
        self.page_rad_locked_text.setMaximumSize(QtCore.QSize(200, 100))
        self.page_rad_locked_text.setObjectName("page_rad_locked_text")
        self.gridLayout_7.addWidget(self.page_rad_locked_text, 1, 0, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem19, 5, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_7, 0, 1, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem20, 0, 0, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem21, 0, 2, 1, 1)
        rad.addWidget(self.page_rad_locked)

        self.retranslateUi(rad)
        rad.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(rad)

    def retranslateUi(self, rad):
        _translate = QtCore.QCoreApplication.translate
        rad.setWindowTitle(_translate("rad", "StackedWidget"))
        self.page_rad_home_button_colleagues.setText(_translate("rad", "Colleagues"))
        self.page_rad_home_button_view_profile.setText(_translate("rad", "View Profile"))
        self.page_rad_home_search_bar.setHtml(_translate("rad", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Search</p></body></html>"))
        self.page_rad_home_patient_information.setSortingEnabled(True)
        self.page_rad_home_patient_information.headerItem().setText(0, _translate("rad", "Patient ID"))
        self.page_rad_home_patient_information.headerItem().setText(1, _translate("rad", "Sex"))
        self.page_rad_home_patient_information.headerItem().setText(2, _translate("rad", "Order Date"))
        self.page_rad_home_patient_information.headerItem().setText(3, _translate("rad", "Scan Type"))
        self.page_rad_home_patient_information.headerItem().setText(4, _translate("rad", "Status"))
        self.page_rad_home_patient_information.headerItem().setText(5, _translate("rad", "Order ID"))
        self.page_rad_home_button_logout.setText(_translate("rad", "Logout"))
        self.page_rad_home_button_proceed.setText(_translate("rad", "Proceed"))
        self.page_rad_home_button_lock_screen.setText(_translate("rad", "Lock Screen"))
        self.page_rad_view_only_button_logout.setText(_translate("rad", "Logout"))
        self.label.setText(_translate("rad", "Radiology report goes here"))
        self.page_rad_view_only_button_hide_3d.setText(_translate("rad", "Hide 3D"))
        self.page_rad_view_only_button_3d_fullscreen.setText(_translate("rad", "Fullscreen 3D"))
        self.page_rad_view_only_button_2d_fullscreen.setText(_translate("rad", "Fullscreen 2D"))
        self.page_rad_view_only_button_back.setText(_translate("rad", "Back"))
        self.page_rad_view_only_button_diagnose.setText(_translate("rad", "Diagnose"))
        self.page_rad_diagnose_button_back.setText(_translate("rad", "Back"))
        self.page_rad_diagnose_button_preview_report.setText(_translate("rad", "Preview Report"))
        self.page_rad_diagnose_button_2d_fullscreen.setText(_translate("rad", "Fullscreen 2D"))
        self.page_rad_diagnose_button_logout.setText(_translate("rad", "Logout"))
        self.page_rad_diagnose_button_3d_fullscreen.setText(_translate("rad", "Fullscreen 3D"))
        self.page_rad_diagnose_button_hide_3d.setText(_translate("rad", "Hide 3D"))
        self.page_rad_diagnose_button_add_annotation.setText(_translate("rad", "Add Annotation"))
        self.page_rad_diagnose_button_2d_zoom_out.setText(_translate("rad", "Zoom Out"))
        self.label_2.setText(_translate("rad", "<html><head/><body><p>More tools</p><p>goes here</p></body></html>"))
        self.page_rad_diagnose_button_2d_zoom_in.setText(_translate("rad", "Zoom In"))
        self.page_rad_diagnose_insert_annotations.setHtml(_translate("rad", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.page_rad_diagnose_insert_annotations.setPlaceholderText(_translate("rad", "Insert annotation"))
        self.page_rad_patient_page_scan_info.setHtml(_translate("rad", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Scan information</p></body></html>"))
        self.page_rad_patient_page_patient_infor.setHtml(_translate("rad", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Patient information</p></body></html>"))
        self.page_rad_patient_page_doctors_orders.setHtml(_translate("rad", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Doctors orders</p></body></html>"))
        self.page_rad_patient_page_button_logout.setText(_translate("rad", "Logout"))
        self.page_rad_patient_page_button_back.setText(_translate("rad", "Back"))
        self.page_rad_patient_page_button_view_scan.setText(_translate("rad", "View Scan"))
        self.page_rad_patient_page_button_diagnose_patient.setText(_translate("rad", "Diagnose patient"))
        self.page_rad_patient_page_button_lock_screen.setText(_translate("rad", "Lock Screen"))
        self.page_rad_report_button_back.setText(_translate("rad", "Back"))
        self.page_rad_report_button_zoom_out.setText(_translate("rad", "Zoom Out"))
        self.label_3.setText(_translate("rad", "More tools goes here"))
        self.page_rad_report_button_zoom_in.setText(_translate("rad", "Zoom In"))
        self.page_rad_report_button_surgeon_view.setText(_translate("rad", "Surgeon view"))
        self.page_rad_report_button_logout.setText(_translate("rad", "Logout"))
        self.page_rad_report_report_preview.setHtml(_translate("rad", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.page_rad_report_report_preview.setPlaceholderText(_translate("rad", "A preview of the radiology report goes here"))
        self.page_rad_report_button_fullscreen.setText(_translate("rad", "Fullscreen 2D"))
        self.page_rad_report_button_send_report.setText(_translate("rad", "Send Report"))
        self.page_rad_locked_insert_password.setPlaceholderText(_translate("rad", "Password"))
        self.page_rad_locked_button_login.setText(_translate("rad", "Login"))
        self.page_rad_locked_text.setHtml(_translate("rad", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Screen is locked</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Current user id: 0000</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    rad = QtWidgets.QStackedWidget()
    ui = Ui_rad()
    ui.setupUi(rad)
    rad.show()
    sys.exit(app.exec_())

