# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rad.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_rad(object):
    def setupUi(self, rad):
        rad.setObjectName("rad")
        rad.resize(1366, 813)
        self.page_rad_home = QtWidgets.QWidget()
        self.page_rad_home.setObjectName("page_rad_home")
        self.gridLayout = QtWidgets.QGridLayout(self.page_rad_home)
        self.gridLayout.setObjectName("gridLayout")
        self.page_rad_home_patient_information = QtWidgets.QTreeWidget(self.page_rad_home)
        self.page_rad_home_patient_information.setMinimumSize(QtCore.QSize(371, 0))
        self.page_rad_home_patient_information.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.page_rad_home_patient_information.setObjectName("page_rad_home_patient_information")
        self.gridLayout.addWidget(self.page_rad_home_patient_information, 4, 2, 1, 3)
        self.page_rad_home_search_bar = QtWidgets.QTextEdit(self.page_rad_home)
        self.page_rad_home_search_bar.setMaximumSize(QtCore.QSize(200, 25))
        self.page_rad_home_search_bar.setObjectName("page_rad_home_search_bar")
        self.gridLayout.addWidget(self.page_rad_home_search_bar, 2, 4, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.page_rad_home_button_colleagues = QtWidgets.QToolButton(self.page_rad_home)
        self.page_rad_home_button_colleagues.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_home_button_colleagues.setMaximumSize(QtCore.QSize(100, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/colleagues.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_rad_home_button_colleagues.setIcon(icon)
        self.page_rad_home_button_colleagues.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_rad_home_button_colleagues.setObjectName("page_rad_home_button_colleagues")
        self.horizontalLayout_4.addWidget(self.page_rad_home_button_colleagues)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.page_rad_home_button_view_profile = QtWidgets.QToolButton(self.page_rad_home)
        self.page_rad_home_button_view_profile.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_home_button_view_profile.setMaximumSize(QtCore.QSize(100, 16777215))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/account.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_rad_home_button_view_profile.setIcon(icon1)
        self.page_rad_home_button_view_profile.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_rad_home_button_view_profile.setObjectName("page_rad_home_button_view_profile")
        self.horizontalLayout_4.addWidget(self.page_rad_home_button_view_profile)
        self.page_rad_home_button_logout = QtWidgets.QToolButton(self.page_rad_home)
        self.page_rad_home_button_logout.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_home_button_logout.setMaximumSize(QtCore.QSize(100, 16777215))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_rad_home_button_logout.setIcon(icon2)
        self.page_rad_home_button_logout.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_rad_home_button_logout.setObjectName("page_rad_home_button_logout")
        self.horizontalLayout_4.addWidget(self.page_rad_home_button_logout)
        self.page_rad_home_button_lock_screen = QtWidgets.QToolButton(self.page_rad_home)
        self.page_rad_home_button_lock_screen.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_home_button_lock_screen.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_home_button_lock_screen.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/lock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_rad_home_button_lock_screen.setIcon(icon3)
        self.page_rad_home_button_lock_screen.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_rad_home_button_lock_screen.setObjectName("page_rad_home_button_lock_screen")
        self.horizontalLayout_4.addWidget(self.page_rad_home_button_lock_screen)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 2, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.page_rad_home)
        self.label_4.setStyleSheet("font-size: 20pt;")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 2, 1, 1)
        self.page_rad_home_button_proceed = QtWidgets.QToolButton(self.page_rad_home)
        self.page_rad_home_button_proceed.setEnabled(False)
        self.page_rad_home_button_proceed.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_home_button_proceed.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_home_button_proceed.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_rad_home_button_proceed.setIcon(icon4)
        self.page_rad_home_button_proceed.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_rad_home_button_proceed.setObjectName("page_rad_home_button_proceed")
        self.gridLayout.addWidget(self.page_rad_home_button_proceed, 6, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.page_rad_home)
        self.label_6.setStyleSheet("color: rgb(253, 147, 50);\n"
"font: 30pt;")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        rad.addWidget(self.page_rad_home)
        self.page_rad_view_only = QtWidgets.QWidget()
        self.page_rad_view_only.setObjectName("page_rad_view_only")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_rad_view_only)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.page_rad_view_only_radiology_report_frame = QtWidgets.QFrame(self.page_rad_view_only)
        self.page_rad_view_only_radiology_report_frame.setMinimumSize(QtCore.QSize(200, 300))
        self.page_rad_view_only_radiology_report_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.page_rad_view_only_radiology_report_frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.page_rad_view_only_radiology_report_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.page_rad_view_only_radiology_report_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_rad_view_only_radiology_report_frame.setObjectName("page_rad_view_only_radiology_report_frame")
        self.label = QtWidgets.QLabel(self.page_rad_view_only_radiology_report_frame)
        self.label.setGeometry(QtCore.QRect(100, 100, 201, 101))
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.page_rad_view_only_radiology_report_frame, 1, 2, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.page_rad_view_only_button_back = QtWidgets.QToolButton(self.page_rad_view_only)
        self.page_rad_view_only_button_back.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_view_only_button_back.setMaximumSize(QtCore.QSize(100, 16777215))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_rad_view_only_button_back.setIcon(icon5)
        self.page_rad_view_only_button_back.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_rad_view_only_button_back.setObjectName("page_rad_view_only_button_back")
        self.horizontalLayout_3.addWidget(self.page_rad_view_only_button_back)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.page_rad_view_only_button_hide_link_windows = QtWidgets.QToolButton(self.page_rad_view_only)
        self.page_rad_view_only_button_hide_link_windows.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_view_only_button_hide_link_windows.setMaximumSize(QtCore.QSize(100, 16777215))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/link.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_rad_view_only_button_hide_link_windows.setIcon(icon6)
        self.page_rad_view_only_button_hide_link_windows.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_rad_view_only_button_hide_link_windows.setObjectName("page_rad_view_only_button_hide_link_windows")
        self.horizontalLayout_3.addWidget(self.page_rad_view_only_button_hide_link_windows)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.page_rad_view_only_button_2d_fullscreen = QtWidgets.QToolButton(self.page_rad_view_only)
        self.page_rad_view_only_button_2d_fullscreen.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_view_only_button_2d_fullscreen.setMaximumSize(QtCore.QSize(100, 16777215))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/full_screen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_rad_view_only_button_2d_fullscreen.setIcon(icon7)
        self.page_rad_view_only_button_2d_fullscreen.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_rad_view_only_button_2d_fullscreen.setObjectName("page_rad_view_only_button_2d_fullscreen")
        self.horizontalLayout_3.addWidget(self.page_rad_view_only_button_2d_fullscreen)
        self.page_rad_view_only_button_3d_fullscreen = QtWidgets.QToolButton(self.page_rad_view_only)
        self.page_rad_view_only_button_3d_fullscreen.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_view_only_button_3d_fullscreen.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_view_only_button_3d_fullscreen.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.page_rad_view_only_button_3d_fullscreen.setIcon(icon7)
        self.page_rad_view_only_button_3d_fullscreen.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_rad_view_only_button_3d_fullscreen.setObjectName("page_rad_view_only_button_3d_fullscreen")
        self.horizontalLayout_3.addWidget(self.page_rad_view_only_button_3d_fullscreen)
        self.page_rad_view_only_button_hide_3d = QtWidgets.QToolButton(self.page_rad_view_only)
        self.page_rad_view_only_button_hide_3d.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_view_only_button_hide_3d.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_view_only_button_hide_3d.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/hide.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_rad_view_only_button_hide_3d.setIcon(icon8)
        self.page_rad_view_only_button_hide_3d.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_rad_view_only_button_hide_3d.setObjectName("page_rad_view_only_button_hide_3d")
        self.horizontalLayout_3.addWidget(self.page_rad_view_only_button_hide_3d)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.page_rad_view_only_button_logout = QtWidgets.QToolButton(self.page_rad_view_only)
        self.page_rad_view_only_button_logout.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_view_only_button_logout.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_view_only_button_logout.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.page_rad_view_only_button_logout.setIcon(icon2)
        self.page_rad_view_only_button_logout.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_rad_view_only_button_logout.setObjectName("page_rad_view_only_button_logout")
        self.horizontalLayout_3.addWidget(self.page_rad_view_only_button_logout)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 0, 2, 1, 3)
        self.page_rad_view_only_button_diagnose = QtWidgets.QToolButton(self.page_rad_view_only)
        self.page_rad_view_only_button_diagnose.setEnabled(False)
        self.page_rad_view_only_button_diagnose.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_view_only_button_diagnose.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_view_only_button_diagnose.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons/diagnose.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_rad_view_only_button_diagnose.setIcon(icon9)
        self.page_rad_view_only_button_diagnose.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_rad_view_only_button_diagnose.setObjectName("page_rad_view_only_button_diagnose")
        self.gridLayout_4.addWidget(self.page_rad_view_only_button_diagnose, 6, 4, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.page_rad_view_only_2d_view_frame = QtWidgets.QFrame(self.page_rad_view_only)
        self.page_rad_view_only_2d_view_frame.setMinimumSize(QtCore.QSize(400, 400))
        self.page_rad_view_only_2d_view_frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.page_rad_view_only_2d_view_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.page_rad_view_only_2d_view_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_rad_view_only_2d_view_frame.setObjectName("page_rad_view_only_2d_view_frame")
        self.page_rad_view_only_2d_view_frame_grid = QtWidgets.QGridLayout(self.page_rad_view_only_2d_view_frame)
        self.page_rad_view_only_2d_view_frame_grid.setContentsMargins(0, 0, 0, 0)
        self.page_rad_view_only_2d_view_frame_grid.setObjectName("page_rad_view_only_2d_view_frame_grid")
        self.page_rad_view_only_2d_view = QtWidgets.QWidget(self.page_rad_view_only_2d_view_frame)
        self.page_rad_view_only_2d_view.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.page_rad_view_only_2d_view.setObjectName("page_rad_view_only_2d_view")
        self.page_rad_view_only_2d_view_frame_grid.addWidget(self.page_rad_view_only_2d_view, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.page_rad_view_only_2d_view_frame)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem5)
        self.page_rad_view_only_3d_view_frame = QtWidgets.QFrame(self.page_rad_view_only)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_rad_view_only_3d_view_frame.sizePolicy().hasHeightForWidth())
        self.page_rad_view_only_3d_view_frame.setSizePolicy(sizePolicy)
        self.page_rad_view_only_3d_view_frame.setMinimumSize(QtCore.QSize(200, 200))
        self.page_rad_view_only_3d_view_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.page_rad_view_only_3d_view_frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.page_rad_view_only_3d_view_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.page_rad_view_only_3d_view_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_rad_view_only_3d_view_frame.setObjectName("page_rad_view_only_3d_view_frame")
        self.page_rad_view_only_3d_view_frame_grid = QtWidgets.QGridLayout(self.page_rad_view_only_3d_view_frame)
        self.page_rad_view_only_3d_view_frame_grid.setContentsMargins(0, 0, 0, 0)
        self.page_rad_view_only_3d_view_frame_grid.setObjectName("page_rad_view_only_3d_view_frame_grid")
        self.page_rad_view_only_3d_view = QtWidgets.QWidget(self.page_rad_view_only_3d_view_frame)
        self.page_rad_view_only_3d_view.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.page_rad_view_only_3d_view.setObjectName("page_rad_view_only_3d_view")
        self.page_rad_view_only_3d_view_frame_grid.addWidget(self.page_rad_view_only_3d_view, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.page_rad_view_only_3d_view_frame)
        self.gridLayout_4.addLayout(self.verticalLayout, 1, 3, 1, 2)
        rad.addWidget(self.page_rad_view_only)
        self.page_rad_diagnose = QtWidgets.QWidget()
        self.page_rad_diagnose.setObjectName("page_rad_diagnose")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_rad_diagnose)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.page_rad_diagnose_2d_view_frame = QtWidgets.QFrame(self.page_rad_diagnose)
        self.page_rad_diagnose_2d_view_frame.setMinimumSize(QtCore.QSize(400, 400))
        self.page_rad_diagnose_2d_view_frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.page_rad_diagnose_2d_view_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.page_rad_diagnose_2d_view_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_rad_diagnose_2d_view_frame.setObjectName("page_rad_diagnose_2d_view_frame")
        self.page_rad_diagnose_2d_view_frame_grid = QtWidgets.QGridLayout(self.page_rad_diagnose_2d_view_frame)
        self.page_rad_diagnose_2d_view_frame_grid.setContentsMargins(0, 0, 0, 0)
        self.page_rad_diagnose_2d_view_frame_grid.setObjectName("page_rad_diagnose_2d_view_frame_grid")
        self.page_rad_diagnose_2d_view = QtWidgets.QWidget(self.page_rad_diagnose_2d_view_frame)
        self.page_rad_diagnose_2d_view.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.page_rad_diagnose_2d_view.setObjectName("page_rad_diagnose_2d_view")
        self.page_rad_diagnose_2d_view_frame_grid.addWidget(self.page_rad_diagnose_2d_view, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.page_rad_diagnose_2d_view_frame, 1, 0, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.page_rad_diagnose_button_2d_zoom_in = QtWidgets.QToolButton(self.page_rad_diagnose)
        self.page_rad_diagnose_button_2d_zoom_in.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_diagnose_button_2d_zoom_in.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_diagnose_button_2d_zoom_in.setFocusPolicy(QtCore.Qt.NoFocus)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icons/zoom_in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_rad_diagnose_button_2d_zoom_in.setIcon(icon10)
        self.page_rad_diagnose_button_2d_zoom_in.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_rad_diagnose_button_2d_zoom_in.setObjectName("page_rad_diagnose_button_2d_zoom_in")
        self.gridLayout_9.addWidget(self.page_rad_diagnose_button_2d_zoom_in, 0, 2, 1, 1)
        self.page_rad_diagnose_button_3d_fullscreen = QtWidgets.QToolButton(self.page_rad_diagnose)
        self.page_rad_diagnose_button_3d_fullscreen.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_diagnose_button_3d_fullscreen.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_diagnose_button_3d_fullscreen.setFocusPolicy(QtCore.Qt.NoFocus)
        self.page_rad_diagnose_button_3d_fullscreen.setIcon(icon7)
        self.page_rad_diagnose_button_3d_fullscreen.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_rad_diagnose_button_3d_fullscreen.setObjectName("page_rad_diagnose_button_3d_fullscreen")
        self.gridLayout_9.addWidget(self.page_rad_diagnose_button_3d_fullscreen, 0, 8, 1, 1)
        self.page_rad_diagnose_button_logout = QtWidgets.QToolButton(self.page_rad_diagnose)
        self.page_rad_diagnose_button_logout.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_diagnose_button_logout.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_diagnose_button_logout.setFocusPolicy(QtCore.Qt.NoFocus)
        self.page_rad_diagnose_button_logout.setIcon(icon2)
        self.page_rad_diagnose_button_logout.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_rad_diagnose_button_logout.setObjectName("page_rad_diagnose_button_logout")
        self.gridLayout_9.addWidget(self.page_rad_diagnose_button_logout, 0, 11, 1, 1)
        self.page_rad_diagnose_button_2d_zoom_out = QtWidgets.QToolButton(self.page_rad_diagnose)
        self.page_rad_diagnose_button_2d_zoom_out.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_diagnose_button_2d_zoom_out.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_diagnose_button_2d_zoom_out.setFocusPolicy(QtCore.Qt.NoFocus)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("icons/zoom_out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_rad_diagnose_button_2d_zoom_out.setIcon(icon11)
        self.page_rad_diagnose_button_2d_zoom_out.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_rad_diagnose_button_2d_zoom_out.setObjectName("page_rad_diagnose_button_2d_zoom_out")
        self.gridLayout_9.addWidget(self.page_rad_diagnose_button_2d_zoom_out, 0, 3, 1, 1)
        self.page_rad_diagnose_button_2d_fullscreen = QtWidgets.QToolButton(self.page_rad_diagnose)
        self.page_rad_diagnose_button_2d_fullscreen.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_diagnose_button_2d_fullscreen.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_diagnose_button_2d_fullscreen.setFocusPolicy(QtCore.Qt.NoFocus)
        self.page_rad_diagnose_button_2d_fullscreen.setIcon(icon7)
        self.page_rad_diagnose_button_2d_fullscreen.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_rad_diagnose_button_2d_fullscreen.setObjectName("page_rad_diagnose_button_2d_fullscreen")
        self.gridLayout_9.addWidget(self.page_rad_diagnose_button_2d_fullscreen, 0, 7, 1, 1)
        self.page_rad_diagnose_button_hide_3d = QtWidgets.QToolButton(self.page_rad_diagnose)
        self.page_rad_diagnose_button_hide_3d.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_diagnose_button_hide_3d.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_diagnose_button_hide_3d.setFocusPolicy(QtCore.Qt.NoFocus)
        self.page_rad_diagnose_button_hide_3d.setIcon(icon8)
        self.page_rad_diagnose_button_hide_3d.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_rad_diagnose_button_hide_3d.setObjectName("page_rad_diagnose_button_hide_3d")
        self.gridLayout_9.addWidget(self.page_rad_diagnose_button_hide_3d, 0, 9, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem6, 0, 10, 1, 1)
        self.page_rad_diagnose_button_back = QtWidgets.QToolButton(self.page_rad_diagnose)
        self.page_rad_diagnose_button_back.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_diagnose_button_back.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_diagnose_button_back.setFocusPolicy(QtCore.Qt.NoFocus)
        self.page_rad_diagnose_button_back.setIcon(icon5)
        self.page_rad_diagnose_button_back.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_rad_diagnose_button_back.setObjectName("page_rad_diagnose_button_back")
        self.gridLayout_9.addWidget(self.page_rad_diagnose_button_back, 0, 0, 1, 1)
        self.page_rad_diagnose_button_link_windows = QtWidgets.QToolButton(self.page_rad_diagnose)
        self.page_rad_diagnose_button_link_windows.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_diagnose_button_link_windows.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_diagnose_button_link_windows.setFocusPolicy(QtCore.Qt.NoFocus)
        self.page_rad_diagnose_button_link_windows.setIcon(icon6)
        self.page_rad_diagnose_button_link_windows.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_rad_diagnose_button_link_windows.setObjectName("page_rad_diagnose_button_link_windows")
        self.gridLayout_9.addWidget(self.page_rad_diagnose_button_link_windows, 0, 5, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem7, 0, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem8, 0, 4, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem9, 0, 6, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_9, 0, 0, 1, 3)
        self.page_rad_diagnose_tools = QtWidgets.QToolBox(self.page_rad_diagnose)
        self.page_rad_diagnose_tools.setObjectName("page_rad_diagnose_tools")
        self.page_rad_diagnose__tools_orientation = QtWidgets.QWidget()
        self.page_rad_diagnose__tools_orientation.setGeometry(QtCore.QRect(0, 0, 655, 113))
        self.page_rad_diagnose__tools_orientation.setStyleSheet("background-color: #151a1e;\n"
"color: #4fa08b")
        self.page_rad_diagnose__tools_orientation.setObjectName("page_rad_diagnose__tools_orientation")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.page_rad_diagnose__tools_orientation)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.radio_button_axial = QtWidgets.QRadioButton(self.page_rad_diagnose__tools_orientation)
        self.radio_button_axial.setChecked(True)
        self.radio_button_axial.setObjectName("radio_button_axial")
        self.page_rad_diagnose_radio_group_orientation = QtWidgets.QButtonGroup(rad)
        self.page_rad_diagnose_radio_group_orientation.setObjectName("page_rad_diagnose_radio_group_orientation")
        self.page_rad_diagnose_radio_group_orientation.addButton(self.radio_button_axial)
        self.horizontalLayout_8.addWidget(self.radio_button_axial)
        self.radio_button_sagittal = QtWidgets.QRadioButton(self.page_rad_diagnose__tools_orientation)
        self.radio_button_sagittal.setObjectName("radio_button_sagittal")
        self.page_rad_diagnose_radio_group_orientation.addButton(self.radio_button_sagittal)
        self.horizontalLayout_8.addWidget(self.radio_button_sagittal)
        self.radio_button_coronal = QtWidgets.QRadioButton(self.page_rad_diagnose__tools_orientation)
        self.radio_button_coronal.setObjectName("radio_button_coronal")
        self.page_rad_diagnose_radio_group_orientation.addButton(self.radio_button_coronal)
        self.horizontalLayout_8.addWidget(self.radio_button_coronal)
        self.page_rad_diagnose_tools.addItem(self.page_rad_diagnose__tools_orientation, "")
        self.page_rad_diagnose_tools_tissue = QtWidgets.QWidget()
        self.page_rad_diagnose_tools_tissue.setGeometry(QtCore.QRect(0, 0, 655, 113))
        self.page_rad_diagnose_tools_tissue.setStyleSheet("background-color: #151a1e;\n"
"color: #4fa08b")
        self.page_rad_diagnose_tools_tissue.setObjectName("page_rad_diagnose_tools_tissue")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.page_rad_diagnose_tools_tissue)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.checkBox_All = QtWidgets.QCheckBox(self.page_rad_diagnose_tools_tissue)
        self.checkBox_All.setChecked(True)
        self.checkBox_All.setObjectName("checkBox_All")
        self.page_rad_diagnose_check_group_tissue = QtWidgets.QButtonGroup(rad)
        self.page_rad_diagnose_check_group_tissue.setObjectName("page_rad_diagnose_check_group_tissue")
        self.page_rad_diagnose_check_group_tissue.setExclusive(False)
        self.page_rad_diagnose_check_group_tissue.addButton(self.checkBox_All)
        self.horizontalLayout_9.addWidget(self.checkBox_All)
        self.checkBox_Soft = QtWidgets.QCheckBox(self.page_rad_diagnose_tools_tissue)
        self.checkBox_Soft.setObjectName("checkBox_Soft")
        self.page_rad_diagnose_check_group_tissue.addButton(self.checkBox_Soft)
        self.horizontalLayout_9.addWidget(self.checkBox_Soft)
        self.checkBox_Bone = QtWidgets.QCheckBox(self.page_rad_diagnose_tools_tissue)
        self.checkBox_Bone.setObjectName("checkBox_Bone")
        self.page_rad_diagnose_check_group_tissue.addButton(self.checkBox_Bone)
        self.horizontalLayout_9.addWidget(self.checkBox_Bone)
        self.checkBox_Muscle = QtWidgets.QCheckBox(self.page_rad_diagnose_tools_tissue)
        self.checkBox_Muscle.setObjectName("checkBox_Muscle")
        self.page_rad_diagnose_check_group_tissue.addButton(self.checkBox_Muscle)
        self.horizontalLayout_9.addWidget(self.checkBox_Muscle)
        self.checkBox_Fat = QtWidgets.QCheckBox(self.page_rad_diagnose_tools_tissue)
        self.checkBox_Fat.setObjectName("checkBox_Fat")
        self.page_rad_diagnose_check_group_tissue.addButton(self.checkBox_Fat)
        self.horizontalLayout_9.addWidget(self.checkBox_Fat)
        self.checkBox_Skin = QtWidgets.QCheckBox(self.page_rad_diagnose_tools_tissue)
        self.checkBox_Skin.setStyleSheet("c")
        self.checkBox_Skin.setObjectName("checkBox_Skin")
        self.page_rad_diagnose_check_group_tissue.addButton(self.checkBox_Skin)
        self.horizontalLayout_9.addWidget(self.checkBox_Skin)
        self.page_rad_diagnose_tools.addItem(self.page_rad_diagnose_tools_tissue, "")
        self.page_rad_diagnose_tools_transparency = QtWidgets.QWidget()
        self.page_rad_diagnose_tools_transparency.setGeometry(QtCore.QRect(0, 0, 655, 113))
        self.page_rad_diagnose_tools_transparency.setStyleSheet("background-color: #151a1e;\n"
"color: #4fa08b;")
        self.page_rad_diagnose_tools_transparency.setObjectName("page_rad_diagnose_tools_transparency")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.page_rad_diagnose_tools_transparency)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.page_rad_diagnose_layout_transparency_volume = QtWidgets.QVBoxLayout()
        self.page_rad_diagnose_layout_transparency_volume.setObjectName("page_rad_diagnose_layout_transparency_volume")
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.page_rad_diagnose_layout_transparency_volume.addItem(spacerItem10)
        self.page_rad_diagnose_slider_transparency_volume = QtWidgets.QSlider(self.page_rad_diagnose_tools_transparency)
        self.page_rad_diagnose_slider_transparency_volume.setMaximum(100)
        self.page_rad_diagnose_slider_transparency_volume.setSingleStep(1)
        self.page_rad_diagnose_slider_transparency_volume.setProperty("value", 20)
        self.page_rad_diagnose_slider_transparency_volume.setOrientation(QtCore.Qt.Horizontal)
        self.page_rad_diagnose_slider_transparency_volume.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.page_rad_diagnose_slider_transparency_volume.setObjectName("page_rad_diagnose_slider_transparency_volume")
        self.page_rad_diagnose_layout_transparency_volume.addWidget(self.page_rad_diagnose_slider_transparency_volume)
        self.page_rad_diagnose_label_transparency_volume = QtWidgets.QLabel(self.page_rad_diagnose_tools_transparency)
        self.page_rad_diagnose_label_transparency_volume.setStyleSheet("")
        self.page_rad_diagnose_label_transparency_volume.setAlignment(QtCore.Qt.AlignCenter)
        self.page_rad_diagnose_label_transparency_volume.setObjectName("page_rad_diagnose_label_transparency_volume")
        self.page_rad_diagnose_layout_transparency_volume.addWidget(self.page_rad_diagnose_label_transparency_volume)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.page_rad_diagnose_layout_transparency_volume.addItem(spacerItem11)
        self.horizontalLayout_10.addLayout(self.page_rad_diagnose_layout_transparency_volume)
        self.page_rad_diagnose_layout_transparency_segmentation = QtWidgets.QVBoxLayout()
        self.page_rad_diagnose_layout_transparency_segmentation.setObjectName("page_rad_diagnose_layout_transparency_segmentation")
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.page_rad_diagnose_layout_transparency_segmentation.addItem(spacerItem12)
        self.page_rad_diagnose_slider_transparency_segmentation = QtWidgets.QSlider(self.page_rad_diagnose_tools_transparency)
        self.page_rad_diagnose_slider_transparency_segmentation.setMaximum(100)
        self.page_rad_diagnose_slider_transparency_segmentation.setProperty("value", 33)
        self.page_rad_diagnose_slider_transparency_segmentation.setSliderPosition(33)
        self.page_rad_diagnose_slider_transparency_segmentation.setOrientation(QtCore.Qt.Horizontal)
        self.page_rad_diagnose_slider_transparency_segmentation.setObjectName("page_rad_diagnose_slider_transparency_segmentation")
        self.page_rad_diagnose_layout_transparency_segmentation.addWidget(self.page_rad_diagnose_slider_transparency_segmentation)
        self.page_rad_diagnose_label_transparency_segmentation = QtWidgets.QLabel(self.page_rad_diagnose_tools_transparency)
        self.page_rad_diagnose_label_transparency_segmentation.setStyleSheet("")
        self.page_rad_diagnose_label_transparency_segmentation.setAlignment(QtCore.Qt.AlignCenter)
        self.page_rad_diagnose_label_transparency_segmentation.setObjectName("page_rad_diagnose_label_transparency_segmentation")
        self.page_rad_diagnose_layout_transparency_segmentation.addWidget(self.page_rad_diagnose_label_transparency_segmentation)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.page_rad_diagnose_layout_transparency_segmentation.addItem(spacerItem13)
        self.horizontalLayout_10.addLayout(self.page_rad_diagnose_layout_transparency_segmentation)
        self.page_rad_diagnose_layout_transparency_active = QtWidgets.QVBoxLayout()
        self.page_rad_diagnose_layout_transparency_active.setObjectName("page_rad_diagnose_layout_transparency_active")
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.page_rad_diagnose_layout_transparency_active.addItem(spacerItem14)
        self.page_rad_diagnose_slider_transparency_active = QtWidgets.QSlider(self.page_rad_diagnose_tools_transparency)
        self.page_rad_diagnose_slider_transparency_active.setMaximum(100)
        self.page_rad_diagnose_slider_transparency_active.setProperty("value", 40)
        self.page_rad_diagnose_slider_transparency_active.setOrientation(QtCore.Qt.Horizontal)
        self.page_rad_diagnose_slider_transparency_active.setObjectName("page_rad_diagnose_slider_transparency_active")
        self.page_rad_diagnose_layout_transparency_active.addWidget(self.page_rad_diagnose_slider_transparency_active)
        self.page_rad_diagnose_label_transparency_active = QtWidgets.QLabel(self.page_rad_diagnose_tools_transparency)
        self.page_rad_diagnose_label_transparency_active.setStyleSheet("")
        self.page_rad_diagnose_label_transparency_active.setAlignment(QtCore.Qt.AlignCenter)
        self.page_rad_diagnose_label_transparency_active.setObjectName("page_rad_diagnose_label_transparency_active")
        self.page_rad_diagnose_layout_transparency_active.addWidget(self.page_rad_diagnose_label_transparency_active)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.page_rad_diagnose_layout_transparency_active.addItem(spacerItem15)
        self.horizontalLayout_10.addLayout(self.page_rad_diagnose_layout_transparency_active)
        self.page_rad_diagnose_tools.addItem(self.page_rad_diagnose_tools_transparency, "")
        self.page_rad_diagnose_tools_link = QtWidgets.QWidget()
        self.page_rad_diagnose_tools_link.setGeometry(QtCore.QRect(0, 0, 655, 113))
        self.page_rad_diagnose_tools_link.setStyleSheet("background-color: #151a1e;\n"
"color: #4fa08b;")
        self.page_rad_diagnose_tools_link.setObjectName("page_rad_diagnose_tools_link")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.page_rad_diagnose_tools_link)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.checkBox_slice = QtWidgets.QCheckBox(self.page_rad_diagnose_tools_link)
        self.checkBox_slice.setChecked(True)
        self.checkBox_slice.setObjectName("checkBox_slice")
        self.page_rad_diagnose_check_group_link = QtWidgets.QButtonGroup(rad)
        self.page_rad_diagnose_check_group_link.setObjectName("page_rad_diagnose_check_group_link")
        self.page_rad_diagnose_check_group_link.setExclusive(False)
        self.page_rad_diagnose_check_group_link.addButton(self.checkBox_slice)
        self.horizontalLayout_11.addWidget(self.checkBox_slice)
        self.checkBox_volume = QtWidgets.QCheckBox(self.page_rad_diagnose_tools_link)
        self.checkBox_volume.setChecked(False)
        self.checkBox_volume.setObjectName("checkBox_volume")
        self.page_rad_diagnose_check_group_link.addButton(self.checkBox_volume)
        self.horizontalLayout_11.addWidget(self.checkBox_volume)
        self.page_rad_diagnose_tools.addItem(self.page_rad_diagnose_tools_link, "")
        self.gridLayout_6.addWidget(self.page_rad_diagnose_tools, 2, 1, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.page_rad_diagnose_tab = QtWidgets.QTabWidget(self.page_rad_diagnose)
        self.page_rad_diagnose_tab.setMinimumSize(QtCore.QSize(300, 300))
        self.page_rad_diagnose_tab.setMaximumSize(QtCore.QSize(16777215, 400))
        self.page_rad_diagnose_tab.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.page_rad_diagnose_tab.setTabPosition(QtWidgets.QTabWidget.North)
        self.page_rad_diagnose_tab.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.page_rad_diagnose_tab.setElideMode(QtCore.Qt.ElideNone)
        self.page_rad_diagnose_tab.setUsesScrollButtons(False)
        self.page_rad_diagnose_tab.setDocumentMode(False)
        self.page_rad_diagnose_tab.setTabBarAutoHide(False)
        self.page_rad_diagnose_tab.setObjectName("page_rad_diagnose_tab")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet("")
        self.tab.setObjectName("tab")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.page_rad_diagnose_insert_locations = QtWidgets.QTextEdit(self.tab)
        self.page_rad_diagnose_insert_locations.setMaximumSize(QtCore.QSize(16777215, 300))
        self.page_rad_diagnose_insert_locations.setTabChangesFocus(True)
        self.page_rad_diagnose_insert_locations.setObjectName("page_rad_diagnose_insert_locations")
        self.gridLayout_19.addWidget(self.page_rad_diagnose_insert_locations, 0, 0, 1, 3)
        self.page_rad_diagnose_insert_findings = QtWidgets.QTextEdit(self.tab)
        self.page_rad_diagnose_insert_findings.setMaximumSize(QtCore.QSize(16777215, 300))
        self.page_rad_diagnose_insert_findings.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.page_rad_diagnose_insert_findings.setTabChangesFocus(True)
        self.page_rad_diagnose_insert_findings.setObjectName("page_rad_diagnose_insert_findings")
        self.gridLayout_19.addWidget(self.page_rad_diagnose_insert_findings, 1, 0, 1, 3)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem16, 3, 2, 1, 1)
        self.page_rad_diagnose_button_add_annotation = QtWidgets.QToolButton(self.tab)
        self.page_rad_diagnose_button_add_annotation.setMinimumSize(QtCore.QSize(125, 0))
        self.page_rad_diagnose_button_add_annotation.setMaximumSize(QtCore.QSize(125, 16777215))
        self.page_rad_diagnose_button_add_annotation.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_rad_diagnose_button_add_annotation.setIcon(icon12)
        self.page_rad_diagnose_button_add_annotation.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_rad_diagnose_button_add_annotation.setObjectName("page_rad_diagnose_button_add_annotation")
        self.gridLayout_19.addWidget(self.page_rad_diagnose_button_add_annotation, 3, 1, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem17, 3, 0, 1, 1)
        self.page_rad_diagnose_tab.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_20.setObjectName("gridLayout_20")
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem18, 1, 0, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem19, 1, 2, 1, 1)
        self.page_rad_diagnose_insert_impression = QtWidgets.QTextEdit(self.tab_2)
        self.page_rad_diagnose_insert_impression.setMaximumSize(QtCore.QSize(16777215, 600))
        self.page_rad_diagnose_insert_impression.setTabChangesFocus(True)
        self.page_rad_diagnose_insert_impression.setObjectName("page_rad_diagnose_insert_impression")
        self.gridLayout_20.addWidget(self.page_rad_diagnose_insert_impression, 0, 0, 1, 3)
        self.page_rad_diagnose_button_add_impression = QtWidgets.QToolButton(self.tab_2)
        self.page_rad_diagnose_button_add_impression.setMinimumSize(QtCore.QSize(125, 0))
        self.page_rad_diagnose_button_add_impression.setMaximumSize(QtCore.QSize(125, 16777215))
        self.page_rad_diagnose_button_add_impression.setIcon(icon12)
        self.page_rad_diagnose_button_add_impression.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_rad_diagnose_button_add_impression.setObjectName("page_rad_diagnose_button_add_impression")
        self.gridLayout_20.addWidget(self.page_rad_diagnose_button_add_impression, 1, 1, 1, 1)
        self.page_rad_diagnose_tab.addTab(self.tab_2, "")
        self.gridLayout_8.addWidget(self.page_rad_diagnose_tab, 1, 2, 2, 1)
        self.gridLayout_6.addLayout(self.gridLayout_8, 2, 0, 2, 1)
        self.page_rad_diagnose_3d_view_frame = QtWidgets.QFrame(self.page_rad_diagnose)
        self.page_rad_diagnose_3d_view_frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.page_rad_diagnose_3d_view_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.page_rad_diagnose_3d_view_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_rad_diagnose_3d_view_frame.setObjectName("page_rad_diagnose_3d_view_frame")
        self.page_rad_diagnose_3d_view_frame_grid = QtWidgets.QGridLayout(self.page_rad_diagnose_3d_view_frame)
        self.page_rad_diagnose_3d_view_frame_grid.setContentsMargins(0, 0, 0, 0)
        self.page_rad_diagnose_3d_view_frame_grid.setObjectName("page_rad_diagnose_3d_view_frame_grid")
        self.page_rad_diagnose_3d_view = QtWidgets.QWidget(self.page_rad_diagnose_3d_view_frame)
        self.page_rad_diagnose_3d_view.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.page_rad_diagnose_3d_view.setObjectName("page_rad_diagnose_3d_view")
        self.page_rad_diagnose_3d_view_frame_grid.addWidget(self.page_rad_diagnose_3d_view, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.page_rad_diagnose_3d_view_frame, 1, 1, 1, 1)
        self.page_rad_diagnose_button_preview_report = QtWidgets.QToolButton(self.page_rad_diagnose)
        self.page_rad_diagnose_button_preview_report.setMinimumSize(QtCore.QSize(125, 0))
        self.page_rad_diagnose_button_preview_report.setMaximumSize(QtCore.QSize(125, 16777215))
        self.page_rad_diagnose_button_preview_report.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("icons/view.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_rad_diagnose_button_preview_report.setIcon(icon13)
        self.page_rad_diagnose_button_preview_report.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_rad_diagnose_button_preview_report.setObjectName("page_rad_diagnose_button_preview_report")
        self.gridLayout_6.addWidget(self.page_rad_diagnose_button_preview_report, 3, 1, 1, 1)
        rad.addWidget(self.page_rad_diagnose)
        self.page_rad_patient_page = QtWidgets.QWidget()
        self.page_rad_patient_page.setObjectName("page_rad_patient_page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_rad_patient_page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.page_rad_patient_page_button_logout = QtWidgets.QToolButton(self.page_rad_patient_page)
        self.page_rad_patient_page_button_logout.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_patient_page_button_logout.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_patient_page_button_logout.setIcon(icon2)
        self.page_rad_patient_page_button_logout.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_rad_patient_page_button_logout.setObjectName("page_rad_patient_page_button_logout")
        self.gridLayout_2.addWidget(self.page_rad_patient_page_button_logout, 1, 5, 1, 1)
        self.page_rad_patient_page_scan_info = QtWidgets.QTextBrowser(self.page_rad_patient_page)
        self.page_rad_patient_page_scan_info.setObjectName("page_rad_patient_page_scan_info")
        self.gridLayout_2.addWidget(self.page_rad_patient_page_scan_info, 3, 2, 1, 2)
        self.page_rad_patient_page_patient_infor = QtWidgets.QTextBrowser(self.page_rad_patient_page)
        self.page_rad_patient_page_patient_infor.setObjectName("page_rad_patient_page_patient_infor")
        self.gridLayout_2.addWidget(self.page_rad_patient_page_patient_infor, 2, 1, 2, 1)
        self.page_rad_patient_page_button_back = QtWidgets.QToolButton(self.page_rad_patient_page)
        self.page_rad_patient_page_button_back.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_patient_page_button_back.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_patient_page_button_back.setIcon(icon5)
        self.page_rad_patient_page_button_back.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_rad_patient_page_button_back.setObjectName("page_rad_patient_page_button_back")
        self.gridLayout_2.addWidget(self.page_rad_patient_page_button_back, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.page_rad_patient_page)
        self.label_2.setStyleSheet("color: rgb(253, 147, 50);\n"
"font: 30pt;")
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem20, 0, 1, 1, 1)
        self.page_rad_patient_page_button_diagnose_patient = QtWidgets.QToolButton(self.page_rad_patient_page)
        self.page_rad_patient_page_button_diagnose_patient.setEnabled(False)
        self.page_rad_patient_page_button_diagnose_patient.setMinimumSize(QtCore.QSize(125, 0))
        self.page_rad_patient_page_button_diagnose_patient.setMaximumSize(QtCore.QSize(125, 16777215))
        self.page_rad_patient_page_button_diagnose_patient.setIcon(icon9)
        self.page_rad_patient_page_button_diagnose_patient.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_rad_patient_page_button_diagnose_patient.setObjectName("page_rad_patient_page_button_diagnose_patient")
        self.gridLayout_3.addWidget(self.page_rad_patient_page_button_diagnose_patient, 0, 3, 1, 1)
        self.page_rad_patient_page_button_view_scan = QtWidgets.QToolButton(self.page_rad_patient_page)
        self.page_rad_patient_page_button_view_scan.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_patient_page_button_view_scan.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_patient_page_button_view_scan.setIcon(icon13)
        self.page_rad_patient_page_button_view_scan.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_rad_patient_page_button_view_scan.setObjectName("page_rad_patient_page_button_view_scan")
        self.gridLayout_3.addWidget(self.page_rad_patient_page_button_view_scan, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 4, 3, 1, 1)
        self.page_rad_patient_page_doctors_orders = QtWidgets.QTextBrowser(self.page_rad_patient_page)
        self.page_rad_patient_page_doctors_orders.setObjectName("page_rad_patient_page_doctors_orders")
        self.gridLayout_2.addWidget(self.page_rad_patient_page_doctors_orders, 2, 2, 1, 2)
        self.page_rad_patient_page_button_lock_screen = QtWidgets.QToolButton(self.page_rad_patient_page)
        self.page_rad_patient_page_button_lock_screen.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_patient_page_button_lock_screen.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_patient_page_button_lock_screen.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.page_rad_patient_page_button_lock_screen.setIcon(icon3)
        self.page_rad_patient_page_button_lock_screen.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_rad_patient_page_button_lock_screen.setObjectName("page_rad_patient_page_button_lock_screen")
        self.gridLayout_2.addWidget(self.page_rad_patient_page_button_lock_screen, 1, 3, 1, 1)
        rad.addWidget(self.page_rad_patient_page)
        self.page_rad_report = QtWidgets.QWidget()
        self.page_rad_report.setObjectName("page_rad_report")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.page_rad_report)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.page_rad_report_button_send_report = QtWidgets.QToolButton(self.page_rad_report)
        self.page_rad_report_button_send_report.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_report_button_send_report.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_report_button_send_report.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("icons/send.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_rad_report_button_send_report.setIcon(icon14)
        self.page_rad_report_button_send_report.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_rad_report_button_send_report.setObjectName("page_rad_report_button_send_report")
        self.gridLayout_14.addWidget(self.page_rad_report_button_send_report, 3, 3, 1, 1)
        self.page_rad_report_2d_image_frame = QtWidgets.QFrame(self.page_rad_report)
        self.page_rad_report_2d_image_frame.setMinimumSize(QtCore.QSize(300, 300))
        self.page_rad_report_2d_image_frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.page_rad_report_2d_image_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.page_rad_report_2d_image_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_rad_report_2d_image_frame.setObjectName("page_rad_report_2d_image_frame")
        self.page_rad_report_2d_image_frame_grid = QtWidgets.QGridLayout(self.page_rad_report_2d_image_frame)
        self.page_rad_report_2d_image_frame_grid.setContentsMargins(0, 0, 0, 0)
        self.page_rad_report_2d_image_frame_grid.setObjectName("page_rad_report_2d_image_frame_grid")
        self.page_rad_report_2d_image = QtWidgets.QWidget(self.page_rad_report_2d_image_frame)
        self.page_rad_report_2d_image.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.page_rad_report_2d_image.setObjectName("page_rad_report_2d_image")
        self.page_rad_report_2d_image_frame_grid.addWidget(self.page_rad_report_2d_image, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.page_rad_report_2d_image_frame, 1, 0, 2, 2)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem21, 0, 9, 1, 1)
        self.page_rad_report_button_fullscreen = QtWidgets.QToolButton(self.page_rad_report)
        self.page_rad_report_button_fullscreen.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_report_button_fullscreen.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_report_button_fullscreen.setIcon(icon7)
        self.page_rad_report_button_fullscreen.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_rad_report_button_fullscreen.setObjectName("page_rad_report_button_fullscreen")
        self.gridLayout_15.addWidget(self.page_rad_report_button_fullscreen, 0, 2, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem22, 0, 3, 1, 1)
        self.page_rad_report_button_zoom_in = QtWidgets.QToolButton(self.page_rad_report)
        self.page_rad_report_button_zoom_in.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_report_button_zoom_in.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_report_button_zoom_in.setIcon(icon10)
        self.page_rad_report_button_zoom_in.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_rad_report_button_zoom_in.setObjectName("page_rad_report_button_zoom_in")
        self.gridLayout_15.addWidget(self.page_rad_report_button_zoom_in, 0, 5, 1, 1)
        self.page_rad_report_button_logout = QtWidgets.QToolButton(self.page_rad_report)
        self.page_rad_report_button_logout.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_report_button_logout.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_report_button_logout.setIcon(icon2)
        self.page_rad_report_button_logout.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_rad_report_button_logout.setObjectName("page_rad_report_button_logout")
        self.gridLayout_15.addWidget(self.page_rad_report_button_logout, 0, 10, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem23, 0, 7, 1, 1)
        self.page_rad_report_button_surgeon_view = QtWidgets.QToolButton(self.page_rad_report)
        self.page_rad_report_button_surgeon_view.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_report_button_surgeon_view.setMaximumSize(QtCore.QSize(100, 16777215))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("icons/surgeon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_rad_report_button_surgeon_view.setIcon(icon15)
        self.page_rad_report_button_surgeon_view.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_rad_report_button_surgeon_view.setObjectName("page_rad_report_button_surgeon_view")
        self.gridLayout_15.addWidget(self.page_rad_report_button_surgeon_view, 0, 8, 1, 1)
        self.page_rad_report_button_back = QtWidgets.QToolButton(self.page_rad_report)
        self.page_rad_report_button_back.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_report_button_back.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_report_button_back.setIcon(icon5)
        self.page_rad_report_button_back.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_rad_report_button_back.setObjectName("page_rad_report_button_back")
        self.gridLayout_15.addWidget(self.page_rad_report_button_back, 0, 0, 1, 1)
        self.page_rad_report_button_zoom_out = QtWidgets.QToolButton(self.page_rad_report)
        self.page_rad_report_button_zoom_out.setMinimumSize(QtCore.QSize(100, 0))
        self.page_rad_report_button_zoom_out.setMaximumSize(QtCore.QSize(100, 16777215))
        self.page_rad_report_button_zoom_out.setIcon(icon11)
        self.page_rad_report_button_zoom_out.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_rad_report_button_zoom_out.setObjectName("page_rad_report_button_zoom_out")
        self.gridLayout_15.addWidget(self.page_rad_report_button_zoom_out, 0, 6, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem24, 0, 1, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_15.addItem(spacerItem25, 0, 4, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_15, 0, 0, 1, 4)
        self.page_rad_report_report_preview_frame = QtWidgets.QFrame(self.page_rad_report)
        self.page_rad_report_report_preview_frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.page_rad_report_report_preview_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.page_rad_report_report_preview_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_rad_report_report_preview_frame.setObjectName("page_rad_report_report_preview_frame")
        self.page_rad_report_report_preview_frame_grid = QtWidgets.QGridLayout(self.page_rad_report_report_preview_frame)
        self.page_rad_report_report_preview_frame_grid.setContentsMargins(0, 0, 0, 0)
        self.page_rad_report_report_preview_frame_grid.setObjectName("page_rad_report_report_preview_frame_grid")
        self.page_rad_report_report_preview = QtWidgets.QWidget(self.page_rad_report_report_preview_frame)
        self.page_rad_report_report_preview.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.page_rad_report_report_preview.setObjectName("page_rad_report_report_preview")
        self.page_rad_report_report_preview_frame_grid.addWidget(self.page_rad_report_report_preview, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.page_rad_report_report_preview_frame, 1, 2, 2, 2)
        rad.addWidget(self.page_rad_report)
        self.page_rad_locked = QtWidgets.QWidget()
        self.page_rad_locked.setObjectName("page_rad_locked")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_rad_locked)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem26, 1, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.page_rad_incorrect_password = QtWidgets.QLabel(self.page_rad_locked)
        self.page_rad_incorrect_password.setEnabled(True)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        # palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        # palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        # palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.page_rad_incorrect_password.setPalette(palette)
        self.page_rad_incorrect_password.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.page_rad_incorrect_password.setText("")
        self.page_rad_incorrect_password.setAlignment(QtCore.Qt.AlignCenter)
        self.page_rad_incorrect_password.setObjectName("page_rad_incorrect_password")
        self.gridLayout_7.addWidget(self.page_rad_incorrect_password, 3, 0, 1, 1)
        self.page_rad_locked_insert_password = QtWidgets.QLineEdit(self.page_rad_locked)
        self.page_rad_locked_insert_password.setMinimumSize(QtCore.QSize(200, 0))
        self.page_rad_locked_insert_password.setMaximumSize(QtCore.QSize(200, 16777215))
        self.page_rad_locked_insert_password.setText("")
        self.page_rad_locked_insert_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.page_rad_locked_insert_password.setObjectName("page_rad_locked_insert_password")
        self.gridLayout_7.addWidget(self.page_rad_locked_insert_password, 4, 0, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem27, 6, 0, 1, 1)
        self.page_rad_locked_text = QtWidgets.QTextBrowser(self.page_rad_locked)
        self.page_rad_locked_text.setMaximumSize(QtCore.QSize(200, 100))
        self.page_rad_locked_text.setObjectName("page_rad_locked_text")
        self.gridLayout_7.addWidget(self.page_rad_locked_text, 2, 0, 1, 1)
        self.page_rad_locked_button_login = QtWidgets.QToolButton(self.page_rad_locked)
        self.page_rad_locked_button_login.setMinimumSize(QtCore.QSize(200, 0))
        self.page_rad_locked_button_login.setMaximumSize(QtCore.QSize(200, 16777215))
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("icons/unlock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_rad_locked_button_login.setIcon(icon16)
        self.page_rad_locked_button_login.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_rad_locked_button_login.setObjectName("page_rad_locked_button_login")
        self.gridLayout_7.addWidget(self.page_rad_locked_button_login, 5, 0, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem28, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.page_rad_locked)
        self.label_7.setStyleSheet("color: rgb(253, 147, 50);\n"
"font: 30pt;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_7, 1, 1, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem29, 1, 2, 1, 1)
        rad.addWidget(self.page_rad_locked)

        self.retranslateUi(rad)
        rad.setCurrentIndex(2)
        self.page_rad_diagnose_tools.setCurrentIndex(2)
        self.page_rad_diagnose_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(rad)
        rad.setTabOrder(self.page_rad_diagnose_insert_locations, self.page_rad_diagnose_insert_findings)
        rad.setTabOrder(self.page_rad_diagnose_insert_findings, self.page_rad_diagnose_button_add_annotation)
        rad.setTabOrder(self.page_rad_diagnose_button_add_annotation, self.page_rad_diagnose_tab)
        rad.setTabOrder(self.page_rad_diagnose_tab, self.page_rad_diagnose_insert_impression)
        rad.setTabOrder(self.page_rad_diagnose_insert_impression, self.page_rad_diagnose_button_add_impression)
        rad.setTabOrder(self.page_rad_diagnose_button_add_impression, self.page_rad_patient_page_scan_info)
        rad.setTabOrder(self.page_rad_patient_page_scan_info, self.page_rad_report_button_send_report)
        rad.setTabOrder(self.page_rad_report_button_send_report, self.page_rad_report_button_fullscreen)
        rad.setTabOrder(self.page_rad_report_button_fullscreen, self.page_rad_locked_insert_password)
        rad.setTabOrder(self.page_rad_locked_insert_password, self.page_rad_locked_button_login)
        rad.setTabOrder(self.page_rad_locked_button_login, self.page_rad_locked_text)
        rad.setTabOrder(self.page_rad_locked_text, self.page_rad_home_patient_information)
        rad.setTabOrder(self.page_rad_home_patient_information, self.page_rad_home_button_proceed)
        rad.setTabOrder(self.page_rad_home_button_proceed, self.page_rad_home_search_bar)
        rad.setTabOrder(self.page_rad_home_search_bar, self.page_rad_view_only_button_diagnose)
        rad.setTabOrder(self.page_rad_view_only_button_diagnose, self.page_rad_view_only_button_logout)
        rad.setTabOrder(self.page_rad_view_only_button_logout, self.page_rad_patient_page_button_diagnose_patient)
        rad.setTabOrder(self.page_rad_patient_page_button_diagnose_patient, self.page_rad_patient_page_button_view_scan)
        rad.setTabOrder(self.page_rad_patient_page_button_view_scan, self.page_rad_patient_page_patient_infor)
        rad.setTabOrder(self.page_rad_patient_page_patient_infor, self.page_rad_patient_page_doctors_orders)

    def retranslateUi(self, rad):
        _translate = QtCore.QCoreApplication.translate
        rad.setWindowTitle(_translate("rad", "StackedWidget"))
        self.page_rad_home_patient_information.setSortingEnabled(True)
        self.page_rad_home_patient_information.headerItem().setText(0, _translate("rad", "Patient ID"))
        self.page_rad_home_patient_information.headerItem().setText(1, _translate("rad", "Sex"))
        self.page_rad_home_patient_information.headerItem().setText(2, _translate("rad", "Order Date"))
        self.page_rad_home_patient_information.headerItem().setText(3, _translate("rad", "Scan Type"))
        self.page_rad_home_patient_information.headerItem().setText(4, _translate("rad", "Status"))
        self.page_rad_home_patient_information.headerItem().setText(5, _translate("rad", "Order ID"))
        self.page_rad_home_search_bar.setHtml(_translate("rad", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">Search</span></p></body></html>"))
        self.page_rad_home_button_colleagues.setText(_translate("rad", "Colleagues"))
        self.page_rad_home_button_view_profile.setText(_translate("rad", "Profile"))
        self.page_rad_home_button_logout.setText(_translate("rad", "Logout"))
        self.page_rad_home_button_lock_screen.setText(_translate("rad", "Lock Screen"))
        self.label_4.setText(_translate("rad", "Patient Scans"))
        self.page_rad_home_button_proceed.setText(_translate("rad", "Proceed"))
        self.label_6.setText(_translate("rad", "CLARITY"))
        self.label.setText(_translate("rad", "Radiology report goes here"))
        self.page_rad_view_only_button_back.setText(_translate("rad", "Back"))
        self.page_rad_view_only_button_hide_link_windows.setText(_translate("rad", "Activate\n"
"2D-3D Link"))
        self.page_rad_view_only_button_2d_fullscreen.setText(_translate("rad", "Fullscreen 2D"))
        self.page_rad_view_only_button_3d_fullscreen.setText(_translate("rad", "Fullscreen 3D"))
        self.page_rad_view_only_button_hide_3d.setText(_translate("rad", "Hide 3D"))
        self.page_rad_view_only_button_logout.setText(_translate("rad", "Logout"))
        self.page_rad_view_only_button_diagnose.setText(_translate("rad", "Diagnose"))
        self.page_rad_diagnose_button_2d_zoom_in.setText(_translate("rad", "Zoom In"))
        self.page_rad_diagnose_button_3d_fullscreen.setText(_translate("rad", "Fullscreen 3D"))
        self.page_rad_diagnose_button_logout.setText(_translate("rad", "Logout"))
        self.page_rad_diagnose_button_2d_zoom_out.setText(_translate("rad", "Zoom Out"))
        self.page_rad_diagnose_button_2d_fullscreen.setText(_translate("rad", "Fullscreen 2D"))
        self.page_rad_diagnose_button_hide_3d.setText(_translate("rad", "Hide 3D"))
        self.page_rad_diagnose_button_back.setText(_translate("rad", "Back"))
        self.page_rad_diagnose_button_link_windows.setText(_translate("rad", "Activate\n"
"2D-3D Link"))
        self.radio_button_axial.setText(_translate("rad", "AXIAL"))
        self.radio_button_sagittal.setText(_translate("rad", "SAGITTAL"))
        self.radio_button_coronal.setText(_translate("rad", "CORONAL"))
        self.page_rad_diagnose_tools.setItemText(self.page_rad_diagnose_tools.indexOf(self.page_rad_diagnose__tools_orientation), _translate("rad", "2D Orientation"))
        self.checkBox_All.setText(_translate("rad", "ALL"))
        self.checkBox_Soft.setText(_translate("rad", "SOFT"))
        self.checkBox_Bone.setText(_translate("rad", "BONE"))
        self.checkBox_Muscle.setText(_translate("rad", "MUSCLE"))
        self.checkBox_Fat.setText(_translate("rad", "FAT"))
        self.checkBox_Skin.setText(_translate("rad", "SKIN"))
        self.page_rad_diagnose_tools.setItemText(self.page_rad_diagnose_tools.indexOf(self.page_rad_diagnose_tools_tissue), _translate("rad", "3D Tissues"))
        self.page_rad_diagnose_label_transparency_volume.setText(_translate("rad", "3D Volume"))
        self.page_rad_diagnose_label_transparency_segmentation.setText(_translate("rad", "Segmentations"))
        self.page_rad_diagnose_label_transparency_active.setText(_translate("rad", "Active Segment"))
        self.page_rad_diagnose_tools.setItemText(self.page_rad_diagnose_tools.indexOf(self.page_rad_diagnose_tools_transparency), _translate("rad", "3D Transparency"))
        self.checkBox_slice.setText(_translate("rad", "Show 2D Image"))
        self.checkBox_volume.setText(_translate("rad", "Show Full 3D Volume"))
        self.page_rad_diagnose_tools.setItemText(self.page_rad_diagnose_tools.indexOf(self.page_rad_diagnose_tools_link), _translate("rad", "3D Link "))
        self.page_rad_diagnose_insert_locations.setPlaceholderText(_translate("rad", "Insert location"))
        self.page_rad_diagnose_insert_findings.setHtml(_translate("rad", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.page_rad_diagnose_insert_findings.setPlaceholderText(_translate("rad", "Insert findings"))
        self.page_rad_diagnose_button_add_annotation.setText(_translate("rad", "Add Annotation"))
        self.page_rad_diagnose_tab.setTabText(self.page_rad_diagnose_tab.indexOf(self.tab), _translate("rad", "Findings"))
        self.page_rad_diagnose_insert_impression.setPlaceholderText(_translate("rad", "Insert impression"))
        self.page_rad_diagnose_button_add_impression.setText(_translate("rad", "Add Impression"))
        self.page_rad_diagnose_tab.setTabText(self.page_rad_diagnose_tab.indexOf(self.tab_2), _translate("rad", "Impression"))
        self.page_rad_diagnose_button_preview_report.setText(_translate("rad", "Preview Report"))
        self.page_rad_patient_page_button_logout.setText(_translate("rad", "Logout"))
        self.page_rad_patient_page_scan_info.setHtml(_translate("rad", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">Scan information</span></p></body></html>"))
        self.page_rad_patient_page_patient_infor.setHtml(_translate("rad", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">Patient information</span></p></body></html>"))
        self.page_rad_patient_page_button_back.setText(_translate("rad", "Back"))
        self.label_2.setText(_translate("rad", "CLARITY"))
        self.page_rad_patient_page_button_diagnose_patient.setText(_translate("rad", "Diagnose patient"))
        self.page_rad_patient_page_button_view_scan.setText(_translate("rad", "View Scan"))
        self.page_rad_patient_page_doctors_orders.setHtml(_translate("rad", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">Doctors orders</span></p></body></html>"))
        self.page_rad_patient_page_button_lock_screen.setText(_translate("rad", "Lock Screen"))
        self.page_rad_report_button_send_report.setText(_translate("rad", "Send Report"))
        self.page_rad_report_button_fullscreen.setText(_translate("rad", "Fullscreen 2D"))
        self.page_rad_report_button_zoom_in.setText(_translate("rad", "Zoom In"))
        self.page_rad_report_button_logout.setText(_translate("rad", "Logout"))
        self.page_rad_report_button_surgeon_view.setText(_translate("rad", "Surgeon view"))
        self.page_rad_report_button_back.setText(_translate("rad", "Back"))
        self.page_rad_report_button_zoom_out.setText(_translate("rad", "Zoom Out"))
        self.page_rad_locked_insert_password.setPlaceholderText(_translate("rad", "Password"))
        self.page_rad_locked_text.setHtml(_translate("rad", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">Screen is locked</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">Current user id: 0000</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p></body></html>"))
        self.page_rad_locked_button_login.setText(_translate("rad", "Login"))
        self.label_7.setText(_translate("rad", "CLARITY"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    rad = QtWidgets.QStackedWidget()
    ui = Ui_rad()
    ui.setupUi(rad)
    rad.show()
    sys.exit(app.exec_())

