# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rad.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_rad(object):
    def setupUi(self, rad):
        rad.setObjectName("rad")
        rad.resize(763, 598)
        self.page_rad_home = QtWidgets.QWidget()
        self.page_rad_home.setObjectName("page_rad_home")
        self.page_rad_home_button_view_profile = QtWidgets.QPushButton(self.page_rad_home)
        self.page_rad_home_button_view_profile.setGeometry(QtCore.QRect(20, 30, 75, 23))
        self.page_rad_home_button_view_profile.setObjectName("page_rad_home_button_view_profile")
        self.page_rad_home_button_colleagues = QtWidgets.QPushButton(self.page_rad_home)
        self.page_rad_home_button_colleagues.setGeometry(QtCore.QRect(100, 30, 75, 23))
        self.page_rad_home_button_colleagues.setObjectName("page_rad_home_button_colleagues")
        self.page_rad_home_button_logout = QtWidgets.QPushButton(self.page_rad_home)
        self.page_rad_home_button_logout.setGeometry(QtCore.QRect(680, 10, 75, 23))
        self.page_rad_home_button_logout.setObjectName("page_rad_home_button_logout")
        self.page_rad_home_button_lock_screen = QtWidgets.QPushButton(self.page_rad_home)
        self.page_rad_home_button_lock_screen.setGeometry(QtCore.QRect(600, 10, 75, 23))
        self.page_rad_home_button_lock_screen.setObjectName("page_rad_home_button_lock_screen")
        self.page_rad_home_patient_information = QtWidgets.QTreeWidget(self.page_rad_home)
        self.page_rad_home_patient_information.setGeometry(QtCore.QRect(20, 70, 371, 421))
        self.page_rad_home_patient_information.setMinimumSize(QtCore.QSize(371, 0))
        self.page_rad_home_patient_information.setObjectName("page_rad_home_patient_information")
        item_0 = QtWidgets.QTreeWidgetItem(self.page_rad_home_patient_information)
        self.page_rad_home_button_proceed = QtWidgets.QPushButton(self.page_rad_home)
        self.page_rad_home_button_proceed.setEnabled(False)
        self.page_rad_home_button_proceed.setGeometry(QtCore.QRect(320, 500, 75, 23))
        self.page_rad_home_button_proceed.setObjectName("page_rad_home_button_proceed")
        self.page_rad_home_search_bar = QtWidgets.QTextEdit(self.page_rad_home)
        self.page_rad_home_search_bar.setGeometry(QtCore.QRect(280, 40, 111, 31))
        self.page_rad_home_search_bar.setObjectName("page_rad_home_search_bar")
        rad.addWidget(self.page_rad_home)
        self.page_rad_view_only = QtWidgets.QWidget()
        self.page_rad_view_only.setObjectName("page_rad_view_only")
        self.page_rad_view_only_2d_view = QtWidgets.QOpenGLWidget(self.page_rad_view_only)
        self.page_rad_view_only_2d_view.setGeometry(QtCore.QRect(40, 50, 341, 341))
        self.page_rad_view_only_2d_view.setObjectName("page_rad_view_only_2d_view")
        self.page_rad_view_only_3d_view = QtWidgets.QOpenGLWidget(self.page_rad_view_only)
        self.page_rad_view_only_3d_view.setGeometry(QtCore.QRect(410, 50, 300, 200))
        self.page_rad_view_only_3d_view.setObjectName("page_rad_view_only_3d_view")
        self.page_rad_view_only_radiology_report = QtWidgets.QTextBrowser(self.page_rad_view_only)
        self.page_rad_view_only_radiology_report.setGeometry(QtCore.QRect(410, 290, 301, 201))
        self.page_rad_view_only_radiology_report.setObjectName("page_rad_view_only_radiology_report")
        self.page_rad_view_only_button_back = QtWidgets.QPushButton(self.page_rad_view_only)
        self.page_rad_view_only_button_back.setGeometry(QtCore.QRect(10, 560, 75, 23))
        self.page_rad_view_only_button_back.setObjectName("page_rad_view_only_button_back")
        self.page_rad_view_only_button_logout = QtWidgets.QPushButton(self.page_rad_view_only)
        self.page_rad_view_only_button_logout.setGeometry(QtCore.QRect(680, 10, 75, 23))
        self.page_rad_view_only_button_logout.setObjectName("page_rad_view_only_button_logout")
        self.page_rad_view_only_scroll_bar = QtWidgets.QScrollBar(self.page_rad_view_only)
        self.page_rad_view_only_scroll_bar.setGeometry(QtCore.QRect(380, 50, 16, 341))
        self.page_rad_view_only_scroll_bar.setOrientation(QtCore.Qt.Vertical)
        self.page_rad_view_only_scroll_bar.setObjectName("page_rad_view_only_scroll_bar")
        self.page_rad_view_only_button_hide_3d = QtWidgets.QPushButton(self.page_rad_view_only)
        self.page_rad_view_only_button_hide_3d.setGeometry(QtCore.QRect(640, 260, 75, 23))
        self.page_rad_view_only_button_hide_3d.setObjectName("page_rad_view_only_button_hide_3d")
        self.page_rad_view_only_button_diagnose = QtWidgets.QPushButton(self.page_rad_view_only)
        self.page_rad_view_only_button_diagnose.setGeometry(QtCore.QRect(640, 500, 75, 23))
        self.page_rad_view_only_button_diagnose.setObjectName("page_rad_view_only_button_diagnose")
        self.page_rad_view_only_button_fullscreen = QtWidgets.QPushButton(self.page_rad_view_only)
        self.page_rad_view_only_button_fullscreen.setGeometry(QtCore.QRect(560, 500, 75, 23))
        self.page_rad_view_only_button_fullscreen.setObjectName("page_rad_view_only_button_fullscreen")
        self.page_rad_view_only_button_2d_fullscreen = QtWidgets.QPushButton(self.page_rad_view_only)
        self.page_rad_view_only_button_2d_fullscreen.setGeometry(QtCore.QRect(300, 400, 75, 23))
        self.page_rad_view_only_button_2d_fullscreen.setObjectName("page_rad_view_only_button_2d_fullscreen")
        self.page_rad_view_only_button_3d_fullscreen = QtWidgets.QPushButton(self.page_rad_view_only)
        self.page_rad_view_only_button_3d_fullscreen.setGeometry(QtCore.QRect(560, 260, 75, 23))
        self.page_rad_view_only_button_3d_fullscreen.setObjectName("page_rad_view_only_button_3d_fullscreen")
        rad.addWidget(self.page_rad_view_only)
        self.page_rad_diagnose = QtWidgets.QWidget()
        self.page_rad_diagnose.setObjectName("page_rad_diagnose")
        self.page_rad_diagnose_3d_view = QtWidgets.QOpenGLWidget(self.page_rad_diagnose)
        self.page_rad_diagnose_3d_view.setGeometry(QtCore.QRect(410, 50, 300, 200))
        self.page_rad_diagnose_3d_view.setObjectName("page_rad_diagnose_3d_view")
        self.page_rad_diagnose_button_2d_fullscreen = QtWidgets.QPushButton(self.page_rad_diagnose)
        self.page_rad_diagnose_button_2d_fullscreen.setGeometry(QtCore.QRect(310, 400, 75, 23))
        self.page_rad_diagnose_button_2d_fullscreen.setObjectName("page_rad_diagnose_button_2d_fullscreen")
        self.page_rad_diagnose_button_logout = QtWidgets.QPushButton(self.page_rad_diagnose)
        self.page_rad_diagnose_button_logout.setGeometry(QtCore.QRect(680, 10, 75, 23))
        self.page_rad_diagnose_button_logout.setObjectName("page_rad_diagnose_button_logout")
        self.page_rad_diagnose_2d_view = QtWidgets.QOpenGLWidget(self.page_rad_diagnose)
        self.page_rad_diagnose_2d_view.setGeometry(QtCore.QRect(40, 50, 341, 341))
        self.page_rad_diagnose_2d_view.setObjectName("page_rad_diagnose_2d_view")
        self.page_rad_diagnose_button_hide_3d = QtWidgets.QPushButton(self.page_rad_diagnose)
        self.page_rad_diagnose_button_hide_3d.setGeometry(QtCore.QRect(640, 260, 75, 23))
        self.page_rad_diagnose_button_hide_3d.setObjectName("page_rad_diagnose_button_hide_3d")
        self.page_rad_diagnose_button_3d_fullscreen = QtWidgets.QPushButton(self.page_rad_diagnose)
        self.page_rad_diagnose_button_3d_fullscreen.setGeometry(QtCore.QRect(560, 260, 75, 23))
        self.page_rad_diagnose_button_3d_fullscreen.setObjectName("page_rad_diagnose_button_3d_fullscreen")
        self.page_rad_diagnose_2d_scroll = QtWidgets.QScrollBar(self.page_rad_diagnose)
        self.page_rad_diagnose_2d_scroll.setGeometry(QtCore.QRect(380, 50, 16, 341))
        self.page_rad_diagnose_2d_scroll.setOrientation(QtCore.Qt.Vertical)
        self.page_rad_diagnose_2d_scroll.setObjectName("page_rad_diagnose_2d_scroll")
        self.page_rad_diagnose_button_back = QtWidgets.QPushButton(self.page_rad_diagnose)
        self.page_rad_diagnose_button_back.setGeometry(QtCore.QRect(10, 560, 75, 23))
        self.page_rad_diagnose_button_back.setObjectName("page_rad_diagnose_button_back")
        self.page_rad_diagnose_button_preview_report = QtWidgets.QPushButton(self.page_rad_diagnose)
        self.page_rad_diagnose_button_preview_report.setGeometry(QtCore.QRect(624, 500, 91, 23))
        self.page_rad_diagnose_button_preview_report.setObjectName("page_rad_diagnose_button_preview_report")
        self.page_rad_diagnose_toolbar_help = QtWidgets.QTextBrowser(self.page_rad_diagnose)
        self.page_rad_diagnose_toolbar_help.setGeometry(QtCore.QRect(40, 390, 161, 51))
        self.page_rad_diagnose_toolbar_help.setObjectName("page_rad_diagnose_toolbar_help")
        self.page_rad_diagnose_button_2d_zoom_in = QtWidgets.QPushButton(self.page_rad_diagnose)
        self.page_rad_diagnose_button_2d_zoom_in.setGeometry(QtCore.QRect(220, 400, 75, 23))
        self.page_rad_diagnose_button_2d_zoom_in.setObjectName("page_rad_diagnose_button_2d_zoom_in")
        self.page_rad_diagnose_button_2d_zoom_out = QtWidgets.QPushButton(self.page_rad_diagnose)
        self.page_rad_diagnose_button_2d_zoom_out.setGeometry(QtCore.QRect(220, 430, 75, 23))
        self.page_rad_diagnose_button_2d_zoom_out.setObjectName("page_rad_diagnose_button_2d_zoom_out")
        self.page_rad_diagnose_insert_annotations = QtWidgets.QTextEdit(self.page_rad_diagnose)
        self.page_rad_diagnose_insert_annotations.setGeometry(QtCore.QRect(413, 290, 301, 201))
        self.page_rad_diagnose_insert_annotations.setObjectName("page_rad_diagnose_insert_annotations")
        rad.addWidget(self.page_rad_diagnose)
        self.page_rad_patient_page = QtWidgets.QWidget()
        self.page_rad_patient_page.setObjectName("page_rad_patient_page")
        self.page_rad_patient_page_view_scan = QtWidgets.QTextBrowser(self.page_rad_patient_page)
        self.page_rad_patient_page_view_scan.setGeometry(QtCore.QRect(30, 50, 311, 441))
        self.page_rad_patient_page_view_scan.setObjectName("page_rad_patient_page_view_scan")
        self.page_rad_patient_page_view_doctors_orders = QtWidgets.QTextBrowser(self.page_rad_patient_page)
        self.page_rad_patient_page_view_doctors_orders.setGeometry(QtCore.QRect(360, 50, 311, 231))
        self.page_rad_patient_page_view_doctors_orders.setObjectName("page_rad_patient_page_view_doctors_orders")
        self.page_rad_patient_page_view_scan_info = QtWidgets.QTextBrowser(self.page_rad_patient_page)
        self.page_rad_patient_page_view_scan_info.setGeometry(QtCore.QRect(360, 290, 311, 201))
        self.page_rad_patient_page_view_scan_info.setObjectName("page_rad_patient_page_view_scan_info")
        self.page_rad_patient_page_button_lock_screen = QtWidgets.QPushButton(self.page_rad_patient_page)
        self.page_rad_patient_page_button_lock_screen.setGeometry(QtCore.QRect(600, 10, 75, 23))
        self.page_rad_patient_page_button_lock_screen.setObjectName("page_rad_patient_page_button_lock_screen")
        self.page_rad_patient_page_button_logout = QtWidgets.QPushButton(self.page_rad_patient_page)
        self.page_rad_patient_page_button_logout.setGeometry(QtCore.QRect(680, 10, 75, 23))
        self.page_rad_patient_page_button_logout.setObjectName("page_rad_patient_page_button_logout")
        self.page_rad_patient_page_button_back = QtWidgets.QPushButton(self.page_rad_patient_page)
        self.page_rad_patient_page_button_back.setGeometry(QtCore.QRect(10, 560, 75, 23))
        self.page_rad_patient_page_button_back.setObjectName("page_rad_patient_page_button_back")
        self.page_rad_patient_page_button_diagnose_patient = QtWidgets.QPushButton(self.page_rad_patient_page)
        self.page_rad_patient_page_button_diagnose_patient.setGeometry(QtCore.QRect(570, 500, 101, 23))
        self.page_rad_patient_page_button_diagnose_patient.setObjectName("page_rad_patient_page_button_diagnose_patient")
        self.page_rad_patient_page_button_view_scan = QtWidgets.QPushButton(self.page_rad_patient_page)
        self.page_rad_patient_page_button_view_scan.setGeometry(QtCore.QRect(490, 500, 75, 23))
        self.page_rad_patient_page_button_view_scan.setObjectName("page_rad_patient_page_button_view_scan")
        rad.addWidget(self.page_rad_patient_page)
        self.page_rad_report = QtWidgets.QWidget()
        self.page_rad_report.setObjectName("page_rad_report")
        self.page_rad_report_button_zoom_in = QtWidgets.QPushButton(self.page_rad_report)
        self.page_rad_report_button_zoom_in.setGeometry(QtCore.QRect(220, 400, 75, 23))
        self.page_rad_report_button_zoom_in.setObjectName("page_rad_report_button_zoom_in")
        self.page_rad_report_button_back = QtWidgets.QPushButton(self.page_rad_report)
        self.page_rad_report_button_back.setGeometry(QtCore.QRect(10, 560, 75, 23))
        self.page_rad_report_button_back.setObjectName("page_rad_report_button_back")
        self.page_rad_report_report_edit = QtWidgets.QTextEdit(self.page_rad_report)
        self.page_rad_report_report_edit.setGeometry(QtCore.QRect(410, 50, 301, 341))
        self.page_rad_report_report_edit.setObjectName("page_rad_report_report_edit")
        self.page_rad_report_button_fullscreen = QtWidgets.QPushButton(self.page_rad_report)
        self.page_rad_report_button_fullscreen.setGeometry(QtCore.QRect(310, 400, 75, 23))
        self.page_rad_report_button_fullscreen.setObjectName("page_rad_report_button_fullscreen")
        self.page_rad_report_button_logout = QtWidgets.QPushButton(self.page_rad_report)
        self.page_rad_report_button_logout.setGeometry(QtCore.QRect(680, 10, 75, 23))
        self.page_rad_report_button_logout.setObjectName("page_rad_report_button_logout")
        self.page_rad_report_button_zoom_out = QtWidgets.QPushButton(self.page_rad_report)
        self.page_rad_report_button_zoom_out.setGeometry(QtCore.QRect(220, 430, 75, 23))
        self.page_rad_report_button_zoom_out.setObjectName("page_rad_report_button_zoom_out")
        self.page_rad_report_2d_image = QtWidgets.QOpenGLWidget(self.page_rad_report)
        self.page_rad_report_2d_image.setGeometry(QtCore.QRect(40, 50, 341, 341))
        self.page_rad_report_2d_image.setObjectName("page_rad_report_2d_image")
        self.page_rad_report_toolbar_help = QtWidgets.QTextBrowser(self.page_rad_report)
        self.page_rad_report_toolbar_help.setGeometry(QtCore.QRect(40, 390, 161, 51))
        self.page_rad_report_toolbar_help.setObjectName("page_rad_report_toolbar_help")
        self.page_rad_report_button_preview_report = QtWidgets.QPushButton(self.page_rad_report)
        self.page_rad_report_button_preview_report.setGeometry(QtCore.QRect(560, 560, 91, 23))
        self.page_rad_report_button_preview_report.setObjectName("page_rad_report_button_preview_report")
        self.page_rad_report_2d_scroll = QtWidgets.QScrollBar(self.page_rad_report)
        self.page_rad_report_2d_scroll.setGeometry(QtCore.QRect(380, 50, 16, 341))
        self.page_rad_report_2d_scroll.setOrientation(QtCore.Qt.Vertical)
        self.page_rad_report_2d_scroll.setObjectName("page_rad_report_2d_scroll")
        self.page_rad_report_button_surgeon_view = QtWidgets.QPushButton(self.page_rad_report)
        self.page_rad_report_button_surgeon_view.setGeometry(QtCore.QRect(460, 560, 91, 23))
        self.page_rad_report_button_surgeon_view.setObjectName("page_rad_report_button_surgeon_view")
        self.page_rad_report_button_send_report = QtWidgets.QPushButton(self.page_rad_report)
        self.page_rad_report_button_send_report.setGeometry(QtCore.QRect(660, 560, 91, 23))
        self.page_rad_report_button_send_report.setObjectName("page_rad_report_button_send_report")
        rad.addWidget(self.page_rad_report)
        self.page_rad_locked = QtWidgets.QWidget()
        self.page_rad_locked.setObjectName("page_rad_locked")
        self.page_rad_locked_button_login = QtWidgets.QPushButton(self.page_rad_locked)
        self.page_rad_locked_button_login.setGeometry(QtCore.QRect(350, 300, 75, 23))
        self.page_rad_locked_button_login.setObjectName("page_rad_locked_button_login")
        self.page_rad_locked_text = QtWidgets.QTextBrowser(self.page_rad_locked)
        self.page_rad_locked_text.setGeometry(QtCore.QRect(310, 190, 161, 161))
        self.page_rad_locked_text.setObjectName("page_rad_locked_text")
        self.page_rad_incorrect_password = QtWidgets.QLabel(self.page_rad_locked)
        self.page_rad_incorrect_password.setEnabled(True)
        self.page_rad_incorrect_password.setGeometry(QtCore.QRect(330, 250, 101, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.page_rad_incorrect_password.setPalette(palette)
        self.page_rad_incorrect_password.setText("")
        self.page_rad_incorrect_password.setObjectName("page_rad_incorrect_password")
        self.page_rad_locked_insert_password = QtWidgets.QLineEdit(self.page_rad_locked)
        self.page_rad_locked_insert_password.setGeometry(QtCore.QRect(330, 270, 113, 20))
        self.page_rad_locked_insert_password.setText("")
        self.page_rad_locked_insert_password.setObjectName("page_rad_locked_insert_password")
        self.page_rad_locked_text.raise_()
        self.page_rad_locked_button_login.raise_()
        self.page_rad_incorrect_password.raise_()
        self.page_rad_locked_insert_password.raise_()
        rad.addWidget(self.page_rad_locked)

        self.retranslateUi(rad)
        rad.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(rad)

    def retranslateUi(self, rad):
        _translate = QtCore.QCoreApplication.translate
        rad.setWindowTitle(_translate("rad", "StackedWidget"))
        self.page_rad_home_button_view_profile.setText(_translate("rad", "View Profile"))
        self.page_rad_home_button_colleagues.setText(_translate("rad", "Colleagues"))
        self.page_rad_home_button_logout.setText(_translate("rad", "Logout"))
        self.page_rad_home_button_lock_screen.setText(_translate("rad", "Lock Screen"))
        self.page_rad_home_patient_information.headerItem().setText(0, _translate("rad", "Patient ID"))
        self.page_rad_home_patient_information.headerItem().setText(1, _translate("rad", "Sex"))
        self.page_rad_home_patient_information.headerItem().setText(2, _translate("rad", "Order Date"))
        self.page_rad_home_patient_information.headerItem().setText(3, _translate("rad", "Scan Type"))
        __sortingEnabled = self.page_rad_home_patient_information.isSortingEnabled()
        self.page_rad_home_patient_information.setSortingEnabled(False)
        self.page_rad_home_patient_information.topLevelItem(0).setText(0, _translate("rad", "0000"))
        self.page_rad_home_patient_information.topLevelItem(0).setText(1, _translate("rad", "M"))
        self.page_rad_home_patient_information.topLevelItem(0).setText(2, _translate("rad", "01-01-2020"))
        self.page_rad_home_patient_information.topLevelItem(0).setText(3, _translate("rad", "MRI"))
        self.page_rad_home_patient_information.setSortingEnabled(__sortingEnabled)
        self.page_rad_home_button_proceed.setText(_translate("rad", "Proceed"))
        self.page_rad_home_search_bar.setHtml(_translate("rad", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Search</p></body></html>"))
        self.page_rad_view_only_radiology_report.setHtml(_translate("rad", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Radiology Report</p></body></html>"))
        self.page_rad_view_only_button_back.setText(_translate("rad", "Back"))
        self.page_rad_view_only_button_logout.setText(_translate("rad", "Logout"))
        self.page_rad_view_only_button_hide_3d.setText(_translate("rad", "Hide 3D"))
        self.page_rad_view_only_button_diagnose.setText(_translate("rad", "Diagnose"))
        self.page_rad_view_only_button_fullscreen.setText(_translate("rad", "Fullscreen"))
        self.page_rad_view_only_button_2d_fullscreen.setText(_translate("rad", "Fullscreen"))
        self.page_rad_view_only_button_3d_fullscreen.setText(_translate("rad", "Fullscreen"))
        self.page_rad_diagnose_button_2d_fullscreen.setText(_translate("rad", "Fullscreen"))
        self.page_rad_diagnose_button_logout.setText(_translate("rad", "Logout"))
        self.page_rad_diagnose_button_hide_3d.setText(_translate("rad", "Hide 3D"))
        self.page_rad_diagnose_button_3d_fullscreen.setText(_translate("rad", "Fullscreen"))
        self.page_rad_diagnose_button_back.setText(_translate("rad", "Back"))
        self.page_rad_diagnose_button_preview_report.setText(_translate("rad", "Preview Report"))
        self.page_rad_diagnose_toolbar_help.setHtml(_translate("rad", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TOOLBAR, NOT SURE HOW TO IMPLEMENT</p></body></html>"))
        self.page_rad_diagnose_button_2d_zoom_in.setText(_translate("rad", "Zoom In"))
        self.page_rad_diagnose_button_2d_zoom_out.setText(_translate("rad", "Zoom Out"))
        self.page_rad_diagnose_insert_annotations.setHtml(_translate("rad", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Insert annotation</p></body></html>"))
        self.page_rad_patient_page_view_scan.setHtml(_translate("rad", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Patient information</p></body></html>"))
        self.page_rad_patient_page_view_doctors_orders.setHtml(_translate("rad", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Doctors orders</p></body></html>"))
        self.page_rad_patient_page_view_scan_info.setHtml(_translate("rad", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Scan information</p></body></html>"))
        self.page_rad_patient_page_button_lock_screen.setText(_translate("rad", "Lock Screen"))
        self.page_rad_patient_page_button_logout.setText(_translate("rad", "Logout"))
        self.page_rad_patient_page_button_back.setText(_translate("rad", "Back"))
        self.page_rad_patient_page_button_diagnose_patient.setText(_translate("rad", "Diagnose patient"))
        self.page_rad_patient_page_button_view_scan.setText(_translate("rad", "View Scan"))
        self.page_rad_report_button_zoom_in.setText(_translate("rad", "Zoom In"))
        self.page_rad_report_button_back.setText(_translate("rad", "Back"))
        self.page_rad_report_report_edit.setHtml(_translate("rad", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Insert annotation</p></body></html>"))
        self.page_rad_report_button_fullscreen.setText(_translate("rad", "Fullscreen"))
        self.page_rad_report_button_logout.setText(_translate("rad", "Logout"))
        self.page_rad_report_button_zoom_out.setText(_translate("rad", "Zoom Out"))
        self.page_rad_report_toolbar_help.setHtml(_translate("rad", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TOOLBAR, NOT SURE HOW TO IMPLEMENT</p></body></html>"))
        self.page_rad_report_button_preview_report.setText(_translate("rad", "Preview Report"))
        self.page_rad_report_button_surgeon_view.setText(_translate("rad", "Surgeon view"))
        self.page_rad_report_button_send_report.setText(_translate("rad", "Send Report"))
        self.page_rad_locked_button_login.setText(_translate("rad", "Login"))
        self.page_rad_locked_text.setHtml(_translate("rad", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Screen is locked</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Current user: Adam Adamsson</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.page_rad_locked_insert_password.setPlaceholderText(_translate("rad", "Password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    rad = QtWidgets.QStackedWidget()
    ui = Ui_rad()
    ui.setupUi(rad)
    rad.show()
    sys.exit(app.exec_())

