# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sur.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_sur(object):
    def setupUi(self, sur):
        sur.setObjectName("sur")
        sur.resize(763, 598)
        self.page_sur_view_edit = QtWidgets.QWidget()
        self.page_sur_view_edit.setObjectName("page_sur_view_edit")
        self.page_sur_view_edit_button_2d_zoom_in = QtWidgets.QPushButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_2d_zoom_in.setGeometry(QtCore.QRect(220, 440, 75, 23))
        self.page_sur_view_edit_button_2d_zoom_in.setObjectName("page_sur_view_edit_button_2d_zoom_in")
        self.page_sur_view_edit_button_hide_3d = QtWidgets.QPushButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_hide_3d.setGeometry(QtCore.QRect(660, 320, 75, 23))
        self.page_sur_view_edit_button_hide_3d.setObjectName("page_sur_view_edit_button_hide_3d")
        self.page_sur_view_edit_button_3d_fullscreen = QtWidgets.QPushButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_3d_fullscreen.setGeometry(QtCore.QRect(660, 290, 75, 23))
        self.page_sur_view_edit_button_3d_fullscreen.setObjectName("page_sur_view_edit_button_3d_fullscreen")
        self.page_sur_view_edit_button_back = QtWidgets.QPushButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_back.setGeometry(QtCore.QRect(10, 570, 75, 23))
        self.page_sur_view_edit_button_back.setObjectName("page_sur_view_edit_button_back")
        self.page_sur_view_edit_insert_annotations = QtWidgets.QTextEdit(self.page_sur_view_edit)
        self.page_sur_view_edit_insert_annotations.setGeometry(QtCore.QRect(423, 390, 301, 131))
        self.page_sur_view_edit_insert_annotations.setObjectName("page_sur_view_edit_insert_annotations")
        self.page_sur_view_edit_button_2d_fullscreen = QtWidgets.QPushButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_2d_fullscreen.setGeometry(QtCore.QRect(300, 440, 75, 23))
        self.page_sur_view_edit_button_2d_fullscreen.setObjectName("page_sur_view_edit_button_2d_fullscreen")
        self.page_sur_view_edit_button_logout = QtWidgets.QPushButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_logout.setGeometry(QtCore.QRect(680, 10, 75, 23))
        self.page_sur_view_edit_button_logout.setObjectName("page_sur_view_edit_button_logout")
        self.page_sur_view_edit_button2d_zoom_out = QtWidgets.QPushButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button2d_zoom_out.setGeometry(QtCore.QRect(220, 470, 75, 23))
        self.page_sur_view_edit_button2d_zoom_out.setObjectName("page_sur_view_edit_button2d_zoom_out")
        self.page_sur_view_edit_2d_view = QtWidgets.QOpenGLWidget(self.page_sur_view_edit)
        self.page_sur_view_edit_2d_view.setGeometry(QtCore.QRect(50, 80, 341, 351))
        self.page_sur_view_edit_2d_view.setObjectName("page_sur_view_edit_2d_view")
        self.page_sur_view_edit_toolbar_help = QtWidgets.QTextBrowser(self.page_sur_view_edit)
        self.page_sur_view_edit_toolbar_help.setGeometry(QtCore.QRect(50, 440, 161, 51))
        self.page_sur_view_edit_toolbar_help.setObjectName("page_sur_view_edit_toolbar_help")
        self.page_sur_view_edit_3d_view = QtWidgets.QOpenGLWidget(self.page_sur_view_edit)
        self.page_sur_view_edit_3d_view.setGeometry(QtCore.QRect(420, 80, 300, 200))
        self.page_sur_view_edit_3d_view.setObjectName("page_sur_view_edit_3d_view")
        self.page_sur_view_edit_button_preview_report = QtWidgets.QPushButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_preview_report.setGeometry(QtCore.QRect(634, 530, 91, 23))
        self.page_sur_view_edit_button_preview_report.setObjectName("page_sur_view_edit_button_preview_report")
        self.page_sur_view_edit_scroll = QtWidgets.QScrollBar(self.page_sur_view_edit)
        self.page_sur_view_edit_scroll.setGeometry(QtCore.QRect(390, 80, 16, 341))
        self.page_sur_view_edit_scroll.setOrientation(QtCore.Qt.Vertical)
        self.page_sur_view_edit_scroll.setObjectName("page_sur_view_edit_scroll")
        self.page_sur_view_edit_button_previous_note = QtWidgets.QPushButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_previous_note.setGeometry(QtCore.QRect(50, 500, 75, 23))
        self.page_sur_view_edit_button_previous_note.setObjectName("page_sur_view_edit_button_previous_note")
        self.page_sur_view_edit_button_2d_previous_slice = QtWidgets.QPushButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_2d_previous_slice.setGeometry(QtCore.QRect(130, 500, 75, 23))
        self.page_sur_view_edit_button_2d_previous_slice.setObjectName("page_sur_view_edit_button_2d_previous_slice")
        self.page_sur_view_edit_button_2d_next_note = QtWidgets.QPushButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_2d_next_note.setGeometry(QtCore.QRect(210, 500, 75, 23))
        self.page_sur_view_edit_button_2d_next_note.setObjectName("page_sur_view_edit_button_2d_next_note")
        self.page_sur_view_edit_button_2d_next_slice = QtWidgets.QPushButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_2d_next_slice.setGeometry(QtCore.QRect(290, 500, 75, 23))
        self.page_sur_view_edit_button_2d_next_slice.setObjectName("page_sur_view_edit_button_2d_next_slice")
        self.page_sur_view_edit_button_2d_play_paus = QtWidgets.QPushButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_2d_play_paus.setGeometry(QtCore.QRect(300, 470, 75, 23))
        self.page_sur_view_edit_button_2d_play_paus.setObjectName("page_sur_view_edit_button_2d_play_paus")
        self.page_sur_view_edit_button_3d_left = QtWidgets.QPushButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_3d_left.setGeometry(QtCore.QRect(420, 290, 75, 23))
        self.page_sur_view_edit_button_3d_left.setObjectName("page_sur_view_edit_button_3d_left")
        self.page_sur_view_edit_button_3d_right = QtWidgets.QPushButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_3d_right.setGeometry(QtCore.QRect(420, 320, 75, 23))
        self.page_sur_view_edit_button_3d_right.setObjectName("page_sur_view_edit_button_3d_right")
        self.page_sur_view_edit_button_3d_up = QtWidgets.QPushButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_3d_up.setGeometry(QtCore.QRect(500, 290, 75, 23))
        self.page_sur_view_edit_button_3d_up.setObjectName("page_sur_view_edit_button_3d_up")
        self.page_sur_view_edit_button_3d_down = QtWidgets.QPushButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_3d_down.setGeometry(QtCore.QRect(500, 320, 75, 23))
        self.page_sur_view_edit_button_3d_down.setObjectName("page_sur_view_edit_button_3d_down")
        self.page_sur_view_edit_3d_zoom_in = QtWidgets.QPushButton(self.page_sur_view_edit)
        self.page_sur_view_edit_3d_zoom_in.setGeometry(QtCore.QRect(580, 290, 75, 23))
        self.page_sur_view_edit_3d_zoom_in.setObjectName("page_sur_view_edit_3d_zoom_in")
        self.page_sur_view_edit_button_3d_zoom_out = QtWidgets.QPushButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_3d_zoom_out.setGeometry(QtCore.QRect(580, 320, 75, 23))
        self.page_sur_view_edit_button_3d_zoom_out.setObjectName("page_sur_view_edit_button_3d_zoom_out")
        self.page_sur_view_edit_3d_tissue_view = QtWidgets.QPushButton(self.page_sur_view_edit)
        self.page_sur_view_edit_3d_tissue_view.setGeometry(QtCore.QRect(660, 50, 75, 23))
        self.page_sur_view_edit_3d_tissue_view.setObjectName("page_sur_view_edit_3d_tissue_view")
        self.page_sur_view_edit_button_3d_fullscreen_2 = QtWidgets.QPushButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_3d_fullscreen_2.setGeometry(QtCore.QRect(500, 50, 75, 23))
        self.page_sur_view_edit_button_3d_fullscreen_2.setObjectName("page_sur_view_edit_button_3d_fullscreen_2")
        self.page_sur_view_edit_button_3d_bone_view = QtWidgets.QPushButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_3d_bone_view.setGeometry(QtCore.QRect(580, 50, 75, 23))
        self.page_sur_view_edit_button_3d_bone_view.setObjectName("page_sur_view_edit_button_3d_bone_view")
        self.page_sur_view_edit_button_3d_toggle_annotations = QtWidgets.QPushButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_3d_toggle_annotations.setGeometry(QtCore.QRect(400, 50, 101, 23))
        self.page_sur_view_edit_button_3d_toggle_annotations.setObjectName("page_sur_view_edit_button_3d_toggle_annotations")
        sur.addWidget(self.page_sur_view_edit)
        self.page_sur_patient_errand = QtWidgets.QWidget()
        self.page_sur_patient_errand.setObjectName("page_sur_patient_errand")
        self.page_sur_patient_errand_button_back = QtWidgets.QPushButton(self.page_sur_patient_errand)
        self.page_sur_patient_errand_button_back.setGeometry(QtCore.QRect(0, 560, 75, 23))
        self.page_sur_patient_errand_button_back.setObjectName("page_sur_patient_errand_button_back")
        self.page_sur_patient_errand_button_logout = QtWidgets.QPushButton(self.page_sur_patient_errand)
        self.page_sur_patient_errand_button_logout.setGeometry(QtCore.QRect(670, 0, 75, 23))
        self.page_sur_patient_errand_button_logout.setObjectName("page_sur_patient_errand_button_logout")
        self.page_sur_patient_errand_rad_report = QtWidgets.QTextBrowser(self.page_sur_patient_errand)
        self.page_sur_patient_errand_rad_report.setGeometry(QtCore.QRect(50, 100, 301, 391))
        self.page_sur_patient_errand_rad_report.setObjectName("page_sur_patient_errand_rad_report")
        self.page_sur_patient_errand_errand_list = QtWidgets.QTreeWidget(self.page_sur_patient_errand)
        self.page_sur_patient_errand_errand_list.setGeometry(QtCore.QRect(390, 100, 301, 391))
        self.page_sur_patient_errand_errand_list.setObjectName("page_sur_patient_errand_errand_list")
        self.page_sur_patient_errand_search_box = QtWidgets.QTextEdit(self.page_sur_patient_errand)
        self.page_sur_patient_errand_search_box.setGeometry(QtCore.QRect(550, 70, 141, 31))
        self.page_sur_patient_errand_search_box.setObjectName("page_sur_patient_errand_search_box")
        self.page_sur_patient_errand_button_share = QtWidgets.QPushButton(self.page_sur_patient_errand)
        self.page_sur_patient_errand_button_share.setGeometry(QtCore.QRect(430, 500, 75, 23))
        self.page_sur_patient_errand_button_share.setObjectName("page_sur_patient_errand_button_share")
        self.page_sur_patient_errand_button_download = QtWidgets.QPushButton(self.page_sur_patient_errand)
        self.page_sur_patient_errand_button_download.setGeometry(QtCore.QRect(520, 500, 75, 23))
        self.page_sur_patient_errand_button_download.setObjectName("page_sur_patient_errand_button_download")
        self.page_sur_patient_errand_button_view = QtWidgets.QPushButton(self.page_sur_patient_errand)
        self.page_sur_patient_errand_button_view.setGeometry(QtCore.QRect(610, 500, 75, 23))
        self.page_sur_patient_errand_button_view.setObjectName("page_sur_patient_errand_button_view")
        sur.addWidget(self.page_sur_patient_errand)
        self.page_sur_home = QtWidgets.QWidget()
        self.page_sur_home.setObjectName("page_sur_home")
        self.label = QtWidgets.QLabel(self.page_sur_home)
        self.label.setGeometry(QtCore.QRect(220, 170, 201, 181))
        self.label.setObjectName("label")
        sur.addWidget(self.page_sur_home)

        self.retranslateUi(sur)
        sur.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(sur)

    def retranslateUi(self, sur):
        _translate = QtCore.QCoreApplication.translate
        sur.setWindowTitle(_translate("sur", "StackedWidget"))
        self.page_sur_view_edit_button_2d_zoom_in.setText(_translate("sur", "Zoom In"))
        self.page_sur_view_edit_button_hide_3d.setText(_translate("sur", "Hide 3D"))
        self.page_sur_view_edit_button_3d_fullscreen.setText(_translate("sur", "Fullscreen"))
        self.page_sur_view_edit_button_back.setText(_translate("sur", "Back"))
        self.page_sur_view_edit_insert_annotations.setHtml(_translate("sur", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Insert annotation</p></body></html>"))
        self.page_sur_view_edit_button_2d_fullscreen.setText(_translate("sur", "Fullscreen"))
        self.page_sur_view_edit_button_logout.setText(_translate("sur", "Logout"))
        self.page_sur_view_edit_button2d_zoom_out.setText(_translate("sur", "Zoom Out"))
        self.page_sur_view_edit_toolbar_help.setHtml(_translate("sur", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TOOLBAR, NOT SURE HOW TO IMPLEMENT</p></body></html>"))
        self.page_sur_view_edit_button_preview_report.setText(_translate("sur", "Preview Report"))
        self.page_sur_view_edit_button_previous_note.setText(_translate("sur", "Previous Note"))
        self.page_sur_view_edit_button_2d_previous_slice.setText(_translate("sur", "Previous Slice"))
        self.page_sur_view_edit_button_2d_next_note.setText(_translate("sur", "Next Note"))
        self.page_sur_view_edit_button_2d_next_slice.setText(_translate("sur", "Nexts Slice"))
        self.page_sur_view_edit_button_2d_play_paus.setText(_translate("sur", "Play/Paus"))
        self.page_sur_view_edit_button_3d_left.setText(_translate("sur", "Left"))
        self.page_sur_view_edit_button_3d_right.setText(_translate("sur", "Right"))
        self.page_sur_view_edit_button_3d_up.setText(_translate("sur", "Up"))
        self.page_sur_view_edit_button_3d_down.setText(_translate("sur", "Down"))
        self.page_sur_view_edit_3d_zoom_in.setText(_translate("sur", "Zoom In"))
        self.page_sur_view_edit_button_3d_zoom_out.setText(_translate("sur", "Zoom Out"))
        self.page_sur_view_edit_3d_tissue_view.setText(_translate("sur", "Tissue View"))
        self.page_sur_view_edit_button_3d_fullscreen_2.setText(_translate("sur", "Full Screen"))
        self.page_sur_view_edit_button_3d_bone_view.setText(_translate("sur", "Bone View"))
        self.page_sur_view_edit_button_3d_toggle_annotations.setText(_translate("sur", "Toogle Annotations"))
        self.page_sur_patient_errand_button_back.setText(_translate("sur", "Back"))
        self.page_sur_patient_errand_button_logout.setText(_translate("sur", "Logout"))
        self.page_sur_patient_errand_errand_list.headerItem().setText(0, _translate("sur", "Task"))
        self.page_sur_patient_errand_errand_list.headerItem().setText(1, _translate("sur", "New Column"))
        self.page_sur_patient_errand_errand_list.headerItem().setText(2, _translate("sur", "Date"))
        self.page_sur_patient_errand_errand_list.headerItem().setText(3, _translate("sur", "Scan"))
        self.page_sur_patient_errand_errand_list.headerItem().setText(4, _translate("sur", "Clinic"))
        self.page_sur_patient_errand_search_box.setHtml(_translate("sur", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Search</p></body></html>"))
        self.page_sur_patient_errand_button_share.setText(_translate("sur", "Share"))
        self.page_sur_patient_errand_button_download.setText(_translate("sur", "Download"))
        self.page_sur_patient_errand_button_view.setText(_translate("sur", "View"))
        self.label.setText(_translate("sur", "SAMMA SOM patientens FÖRSTA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    sur = QtWidgets.QStackedWidget()
    ui = Ui_sur()
    ui.setupUi(sur)
    sur.show()
    sys.exit(app.exec_())

