# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sur.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_sur(object):
    def setupUi(self, sur):
        sur.setObjectName("sur")
        sur.resize(1002, 806)
        self.page_sur_view_edit = QtWidgets.QWidget()
        self.page_sur_view_edit.setObjectName("page_sur_view_edit")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_sur_view_edit)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.page_sur_view_edit_button_link_windows = QtWidgets.QToolButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_link_windows.setMinimumSize(QtCore.QSize(0, 0))
        self.page_sur_view_edit_button_link_windows.setMaximumSize(QtCore.QSize(30, 30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/unlink.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_sur_view_edit_button_link_windows.setIcon(icon)
        self.page_sur_view_edit_button_link_windows.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_link_windows.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.page_sur_view_edit_button_link_windows.setObjectName("page_sur_view_edit_button_link_windows")
        self.gridLayout_2.addWidget(self.page_sur_view_edit_button_link_windows, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 2, 8, 2, 1)
        self.page_sur_view_edit_3d_layout = QtWidgets.QGridLayout()
        self.page_sur_view_edit_3d_layout.setObjectName("page_sur_view_edit_3d_layout")
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.page_sur_view_edit_3d_layout.addItem(spacerItem, 0, 1, 1, 1)
        self.page_sur_view_edit_button_3d_fullscreen = QtWidgets.QToolButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_3d_fullscreen.setMinimumSize(QtCore.QSize(0, 0))
        self.page_sur_view_edit_button_3d_fullscreen.setMaximumSize(QtCore.QSize(30, 30))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/full_screen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_sur_view_edit_button_3d_fullscreen.setIcon(icon1)
        self.page_sur_view_edit_button_3d_fullscreen.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_3d_fullscreen.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.page_sur_view_edit_button_3d_fullscreen.setObjectName("page_sur_view_edit_button_3d_fullscreen")
        self.page_sur_view_edit_3d_layout.addWidget(self.page_sur_view_edit_button_3d_fullscreen, 0, 4, 1, 1)
        self.page_sur_view_edit_button_3d_zoom_in = QtWidgets.QToolButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_3d_zoom_in.setMinimumSize(QtCore.QSize(0, 0))
        self.page_sur_view_edit_button_3d_zoom_in.setMaximumSize(QtCore.QSize(30, 30))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/zoom_in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_sur_view_edit_button_3d_zoom_in.setIcon(icon2)
        self.page_sur_view_edit_button_3d_zoom_in.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_3d_zoom_in.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.page_sur_view_edit_button_3d_zoom_in.setObjectName("page_sur_view_edit_button_3d_zoom_in")
        self.page_sur_view_edit_3d_layout.addWidget(self.page_sur_view_edit_button_3d_zoom_in, 0, 3, 1, 1)
        self.page_sur_view_edit_button_3d_zoom_out = QtWidgets.QToolButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_3d_zoom_out.setMinimumSize(QtCore.QSize(0, 0))
        self.page_sur_view_edit_button_3d_zoom_out.setMaximumSize(QtCore.QSize(30, 30))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/zoom_out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_sur_view_edit_button_3d_zoom_out.setIcon(icon3)
        self.page_sur_view_edit_button_3d_zoom_out.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_3d_zoom_out.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.page_sur_view_edit_button_3d_zoom_out.setObjectName("page_sur_view_edit_button_3d_zoom_out")
        self.page_sur_view_edit_3d_layout.addWidget(self.page_sur_view_edit_button_3d_zoom_out, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.page_sur_view_edit_3d_layout.addItem(spacerItem1, 0, 5, 1, 1)
        self.page_sur_view_edit_button_logout = QtWidgets.QToolButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_logout.setMinimumSize(QtCore.QSize(0, 0))
        self.page_sur_view_edit_button_logout.setMaximumSize(QtCore.QSize(105, 30))
        self.page_sur_view_edit_button_logout.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_sur_view_edit_button_logout.setIcon(icon4)
        self.page_sur_view_edit_button_logout.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_logout.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.page_sur_view_edit_button_logout.setObjectName("page_sur_view_edit_button_logout")
        self.page_sur_view_edit_3d_layout.addWidget(self.page_sur_view_edit_button_logout, 0, 6, 1, 1)
        self.page_sur_view_edit_3d_view_frame = QtWidgets.QFrame(self.page_sur_view_edit)
        self.page_sur_view_edit_3d_view_frame.setMinimumSize(QtCore.QSize(300, 250))
        self.page_sur_view_edit_3d_view_frame.setStyleSheet("")
        self.page_sur_view_edit_3d_view_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.page_sur_view_edit_3d_view_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_sur_view_edit_3d_view_frame.setLineWidth(0)
        self.page_sur_view_edit_3d_view_frame.setObjectName("page_sur_view_edit_3d_view_frame")
        self.page_sur_view_edit_3d_view_frame_grid = QtWidgets.QGridLayout(self.page_sur_view_edit_3d_view_frame)
        self.page_sur_view_edit_3d_view_frame_grid.setContentsMargins(0, 0, 0, 0)
        self.page_sur_view_edit_3d_view_frame_grid.setObjectName("page_sur_view_edit_3d_view_frame_grid")
        self.page_sur_view_edit_3d_view = QtWidgets.QWidget(self.page_sur_view_edit_3d_view_frame)
        self.page_sur_view_edit_3d_view.setStyleSheet("")
        self.page_sur_view_edit_3d_view.setObjectName("page_sur_view_edit_3d_view")
        self.page_sur_view_edit_3d_view_frame_grid.addWidget(self.page_sur_view_edit_3d_view, 0, 0, 1, 1)
        self.page_sur_view_edit_3d_layout.addWidget(self.page_sur_view_edit_3d_view_frame, 1, 0, 1, 7)
        self.gridLayout_4.addLayout(self.page_sur_view_edit_3d_layout, 2, 9, 2, 1)
        self.page_sur_view_edit_2d_layout = QtWidgets.QGridLayout()
        self.page_sur_view_edit_2d_layout.setObjectName("page_sur_view_edit_2d_layout")
        self.page_sur_view_edit_button_2d_fullscreen = QtWidgets.QToolButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_2d_fullscreen.setMinimumSize(QtCore.QSize(0, 0))
        self.page_sur_view_edit_button_2d_fullscreen.setMaximumSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_2d_fullscreen.setIcon(icon1)
        self.page_sur_view_edit_button_2d_fullscreen.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_2d_fullscreen.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.page_sur_view_edit_button_2d_fullscreen.setObjectName("page_sur_view_edit_button_2d_fullscreen")
        self.page_sur_view_edit_2d_layout.addWidget(self.page_sur_view_edit_button_2d_fullscreen, 0, 4, 1, 1)
        self.page_sur_view_edit_button_2d_zoom_out = QtWidgets.QToolButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_2d_zoom_out.setMinimumSize(QtCore.QSize(0, 0))
        self.page_sur_view_edit_button_2d_zoom_out.setMaximumSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_2d_zoom_out.setIcon(icon3)
        self.page_sur_view_edit_button_2d_zoom_out.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_2d_zoom_out.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.page_sur_view_edit_button_2d_zoom_out.setObjectName("page_sur_view_edit_button_2d_zoom_out")
        self.page_sur_view_edit_2d_layout.addWidget(self.page_sur_view_edit_button_2d_zoom_out, 0, 2, 1, 1)
        self.page_sur_view_edit_button_2d_zoom_in = QtWidgets.QToolButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_2d_zoom_in.setMinimumSize(QtCore.QSize(0, 0))
        self.page_sur_view_edit_button_2d_zoom_in.setMaximumSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_2d_zoom_in.setIcon(icon2)
        self.page_sur_view_edit_button_2d_zoom_in.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_2d_zoom_in.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.page_sur_view_edit_button_2d_zoom_in.setObjectName("page_sur_view_edit_button_2d_zoom_in")
        self.page_sur_view_edit_2d_layout.addWidget(self.page_sur_view_edit_button_2d_zoom_in, 0, 3, 1, 1)
        self.page_sur_view_edit_2d_view_frame = QtWidgets.QFrame(self.page_sur_view_edit)
        self.page_sur_view_edit_2d_view_frame.setMinimumSize(QtCore.QSize(300, 250))
        self.page_sur_view_edit_2d_view_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.page_sur_view_edit_2d_view_frame.setStyleSheet("")
        self.page_sur_view_edit_2d_view_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.page_sur_view_edit_2d_view_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_sur_view_edit_2d_view_frame.setLineWidth(0)
        self.page_sur_view_edit_2d_view_frame.setObjectName("page_sur_view_edit_2d_view_frame")
        self.page_sur_view_edit_2d_view_frame_grid = QtWidgets.QGridLayout(self.page_sur_view_edit_2d_view_frame)
        self.page_sur_view_edit_2d_view_frame_grid.setContentsMargins(0, 0, 0, 0)
        self.page_sur_view_edit_2d_view_frame_grid.setObjectName("page_sur_view_edit_2d_view_frame_grid")
        self.page_sur_view_edit_2d_view = QtWidgets.QWidget(self.page_sur_view_edit_2d_view_frame)
        self.page_sur_view_edit_2d_view.setStyleSheet("")
        self.page_sur_view_edit_2d_view.setObjectName("page_sur_view_edit_2d_view")
        self.page_sur_view_edit_2d_view_frame_grid.addWidget(self.page_sur_view_edit_2d_view, 0, 0, 1, 1)
        self.page_sur_view_edit_2d_layout.addWidget(self.page_sur_view_edit_2d_view_frame, 1, 1, 1, 5)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.page_sur_view_edit_2d_layout.addItem(spacerItem2, 0, 5, 1, 1)
        self.page_sur_view_edit_2d_slider_color_level = QtWidgets.QSlider(self.page_sur_view_edit)
        self.page_sur_view_edit_2d_slider_color_level.setMinimum(-5000)
        self.page_sur_view_edit_2d_slider_color_level.setMaximum(5000)
        self.page_sur_view_edit_2d_slider_color_level.setSingleStep(100)
        self.page_sur_view_edit_2d_slider_color_level.setPageStep(500)
        self.page_sur_view_edit_2d_slider_color_level.setProperty("value", -170)
        self.page_sur_view_edit_2d_slider_color_level.setOrientation(QtCore.Qt.Horizontal)
        self.page_sur_view_edit_2d_slider_color_level.setInvertedAppearance(True)
        self.page_sur_view_edit_2d_slider_color_level.setInvertedControls(True)
        self.page_sur_view_edit_2d_slider_color_level.setObjectName("page_sur_view_edit_2d_slider_color_level")
        self.page_sur_view_edit_2d_layout.addWidget(self.page_sur_view_edit_2d_slider_color_level, 2, 1, 1, 5)
        self.page_sur_view_edit_2d_slider_color_window = QtWidgets.QSlider(self.page_sur_view_edit)
        self.page_sur_view_edit_2d_slider_color_window.setMinimum(-6000)
        self.page_sur_view_edit_2d_slider_color_window.setMaximum(12000)
        self.page_sur_view_edit_2d_slider_color_window.setSingleStep(100)
        self.page_sur_view_edit_2d_slider_color_window.setPageStep(500)
        self.page_sur_view_edit_2d_slider_color_window.setProperty("value", 1800)
        self.page_sur_view_edit_2d_slider_color_window.setOrientation(QtCore.Qt.Vertical)
        self.page_sur_view_edit_2d_slider_color_window.setObjectName("page_sur_view_edit_2d_slider_color_window")
        self.page_sur_view_edit_2d_layout.addWidget(self.page_sur_view_edit_2d_slider_color_window, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.page_sur_view_edit_2d_layout.addItem(spacerItem3, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.page_sur_view_edit_2d_layout, 2, 7, 2, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.page_sur_view_edit_button_2d_next_note = QtWidgets.QToolButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_2d_next_note.setMinimumSize(QtCore.QSize(0, 0))
        self.page_sur_view_edit_button_2d_next_note.setMaximumSize(QtCore.QSize(30, 30))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/next_note.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_sur_view_edit_button_2d_next_note.setIcon(icon5)
        self.page_sur_view_edit_button_2d_next_note.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_2d_next_note.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.page_sur_view_edit_button_2d_next_note.setObjectName("page_sur_view_edit_button_2d_next_note")
        self.gridLayout_5.addWidget(self.page_sur_view_edit_button_2d_next_note, 0, 4, 1, 1)
        self.page_sur_view_edit_button_2d_previous_slice = QtWidgets.QToolButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_2d_previous_slice.setMinimumSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_2d_previous_slice.setMaximumSize(QtCore.QSize(30, 30))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/previous_slice.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_sur_view_edit_button_2d_previous_slice.setIcon(icon6)
        self.page_sur_view_edit_button_2d_previous_slice.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_2d_previous_slice.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.page_sur_view_edit_button_2d_previous_slice.setObjectName("page_sur_view_edit_button_2d_previous_slice")
        self.gridLayout_5.addWidget(self.page_sur_view_edit_button_2d_previous_slice, 0, 1, 1, 1)
        self.page_sur_view_edit_button_2d_previous_note = QtWidgets.QToolButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_2d_previous_note.setMinimumSize(QtCore.QSize(0, 0))
        self.page_sur_view_edit_button_2d_previous_note.setMaximumSize(QtCore.QSize(30, 30))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/previous_note.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_sur_view_edit_button_2d_previous_note.setIcon(icon7)
        self.page_sur_view_edit_button_2d_previous_note.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_2d_previous_note.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.page_sur_view_edit_button_2d_previous_note.setObjectName("page_sur_view_edit_button_2d_previous_note")
        self.gridLayout_5.addWidget(self.page_sur_view_edit_button_2d_previous_note, 0, 2, 1, 1)
        self.page_sur_view_edit_button_2d_play_pause = QtWidgets.QToolButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_2d_play_pause.setMinimumSize(QtCore.QSize(0, 0))
        self.page_sur_view_edit_button_2d_play_pause.setMaximumSize(QtCore.QSize(30, 30))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/play_pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_sur_view_edit_button_2d_play_pause.setIcon(icon8)
        self.page_sur_view_edit_button_2d_play_pause.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_2d_play_pause.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.page_sur_view_edit_button_2d_play_pause.setObjectName("page_sur_view_edit_button_2d_play_pause")
        self.gridLayout_5.addWidget(self.page_sur_view_edit_button_2d_play_pause, 0, 3, 1, 1)
        self.page_sur_view_edit_report_frame = QtWidgets.QFrame(self.page_sur_view_edit)
        self.page_sur_view_edit_report_frame.setMinimumSize(QtCore.QSize(300, 300))
        self.page_sur_view_edit_report_frame.setMaximumSize(QtCore.QSize(600, 16777215))
        self.page_sur_view_edit_report_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.page_sur_view_edit_report_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_sur_view_edit_report_frame.setLineWidth(0)
        self.page_sur_view_edit_report_frame.setObjectName("page_sur_view_edit_report_frame")
        self.page_sur_view_edit_report_frame_grid = QtWidgets.QGridLayout(self.page_sur_view_edit_report_frame)
        self.page_sur_view_edit_report_frame_grid.setContentsMargins(0, 0, 0, 0)
        self.page_sur_view_edit_report_frame_grid.setObjectName("page_sur_view_edit_report_frame_grid")
        self.page_sur_view_edit_report = QtWidgets.QWidget(self.page_sur_view_edit_report_frame)
        self.page_sur_view_edit_report.setObjectName("page_sur_view_edit_report")
        self.page_sur_view_edit_report_frame_grid.addWidget(self.page_sur_view_edit_report, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.page_sur_view_edit_report_frame, 1, 0, 1, 7)
        self.tabWidget = QtWidgets.QTabWidget(self.page_sur_view_edit)
        self.tabWidget.setMinimumSize(QtCore.QSize(300, 200))
        self.tabWidget.setMaximumSize(QtCore.QSize(600, 300))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_2.setObjectName("textEdit_2")
        self.gridLayout_8.addWidget(self.textEdit_2, 1, 0, 1, 3)
        self.textEdit = QtWidgets.QTextEdit(self.tab)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_8.addWidget(self.textEdit, 0, 0, 1, 3)
        self.toolButton = QtWidgets.QToolButton(self.tab)
        self.toolButton.setMinimumSize(QtCore.QSize(30, 30))
        self.toolButton.setMaximumSize(QtCore.QSize(30, 30))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon9)
        self.toolButton.setIconSize(QtCore.QSize(30, 30))
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout_8.addWidget(self.toolButton, 2, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem4, 2, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem5, 2, 2, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.textEdit_3 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_3.setObjectName("textEdit_3")
        self.gridLayout_10.addWidget(self.textEdit_3, 0, 0, 1, 3)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem6, 1, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem7, 1, 2, 1, 1)
        self.toolButton_2 = QtWidgets.QToolButton(self.tab_2)
        self.toolButton_2.setMinimumSize(QtCore.QSize(30, 30))
        self.toolButton_2.setMaximumSize(QtCore.QSize(30, 30))
        self.toolButton_2.setIcon(icon9)
        self.toolButton_2.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout_10.addWidget(self.toolButton_2, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_5.addWidget(self.tabWidget, 2, 0, 1, 7)
        self.page_sur_view_edit_button_2d_next_slice = QtWidgets.QToolButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_2d_next_slice.setMinimumSize(QtCore.QSize(0, 0))
        self.page_sur_view_edit_button_2d_next_slice.setMaximumSize(QtCore.QSize(30, 30))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icons/next_slice.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_sur_view_edit_button_2d_next_slice.setIcon(icon10)
        self.page_sur_view_edit_button_2d_next_slice.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_2d_next_slice.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.page_sur_view_edit_button_2d_next_slice.setObjectName("page_sur_view_edit_button_2d_next_slice")
        self.gridLayout_5.addWidget(self.page_sur_view_edit_button_2d_next_slice, 0, 5, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem8, 0, 6, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem9, 0, 0, 1, 1)
        self.page_sur_view_edit_button_back = QtWidgets.QToolButton(self.page_sur_view_edit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_sur_view_edit_button_back.sizePolicy().hasHeightForWidth())
        self.page_sur_view_edit_button_back.setSizePolicy(sizePolicy)
        self.page_sur_view_edit_button_back.setMinimumSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_back.setMaximumSize(QtCore.QSize(75, 30))
        self.page_sur_view_edit_button_back.setAutoFillBackground(False)
        self.page_sur_view_edit_button_back.setStyleSheet("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("icons/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_sur_view_edit_button_back.setIcon(icon11)
        self.page_sur_view_edit_button_back.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_back.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.page_sur_view_edit_button_back.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.page_sur_view_edit_button_back.setObjectName("page_sur_view_edit_button_back")
        self.gridLayout_5.addWidget(self.page_sur_view_edit_button_back, 3, 0, 1, 1)
        self.page_sur_view_edit_button_preview_report = QtWidgets.QToolButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_preview_report.setEnabled(False)
        self.page_sur_view_edit_button_preview_report.setMinimumSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_preview_report.setMaximumSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_preview_report.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.page_sur_view_edit_button_preview_report.setStyleSheet("border: none;")
        self.page_sur_view_edit_button_preview_report.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("icons/view.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_sur_view_edit_button_preview_report.setIcon(icon12)
        self.page_sur_view_edit_button_preview_report.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_preview_report.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.page_sur_view_edit_button_preview_report.setObjectName("page_sur_view_edit_button_preview_report")
        self.gridLayout_5.addWidget(self.page_sur_view_edit_button_preview_report, 3, 5, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem10, 3, 1, 1, 4)
        self.gridLayout_4.addLayout(self.gridLayout_5, 2, 6, 2, 1)
        sur.addWidget(self.page_sur_view_edit)
        self.page_sur_patient_errand = QtWidgets.QWidget()
        self.page_sur_patient_errand.setObjectName("page_sur_patient_errand")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_sur_patient_errand)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.page_sur_patient_errand_button_logout = QtWidgets.QToolButton(self.page_sur_patient_errand)
        self.page_sur_patient_errand_button_logout.setMinimumSize(QtCore.QSize(30, 30))
        self.page_sur_patient_errand_button_logout.setMaximumSize(QtCore.QSize(105, 30))
        self.page_sur_patient_errand_button_logout.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.page_sur_patient_errand_button_logout.setIcon(icon4)
        self.page_sur_patient_errand_button_logout.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_patient_errand_button_logout.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.page_sur_patient_errand_button_logout.setObjectName("page_sur_patient_errand_button_logout")
        self.gridLayout_3.addWidget(self.page_sur_patient_errand_button_logout, 0, 5, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.page_sur_patient_errand)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.page_sur_patient_errand_label_name = QtWidgets.QLabel(self.groupBox)
        self.page_sur_patient_errand_label_name.setMinimumSize(QtCore.QSize(0, 30))
        self.page_sur_patient_errand_label_name.setMaximumSize(QtCore.QSize(16777215, 30))
        self.page_sur_patient_errand_label_name.setObjectName("page_sur_patient_errand_label_name")
        self.verticalLayout_2.addWidget(self.page_sur_patient_errand_label_name)
        self.page_sur_patient_errand_label_age = QtWidgets.QLabel(self.groupBox)
        self.page_sur_patient_errand_label_age.setMinimumSize(QtCore.QSize(0, 30))
        self.page_sur_patient_errand_label_age.setMaximumSize(QtCore.QSize(16777215, 30))
        self.page_sur_patient_errand_label_age.setObjectName("page_sur_patient_errand_label_age")
        self.verticalLayout_2.addWidget(self.page_sur_patient_errand_label_age)
        self.page_sur_patient_errand_label_phone_number = QtWidgets.QLabel(self.groupBox)
        self.page_sur_patient_errand_label_phone_number.setMinimumSize(QtCore.QSize(0, 30))
        self.page_sur_patient_errand_label_phone_number.setMaximumSize(QtCore.QSize(16777215, 30))
        self.page_sur_patient_errand_label_phone_number.setObjectName("page_sur_patient_errand_label_phone_number")
        self.verticalLayout_2.addWidget(self.page_sur_patient_errand_label_phone_number)
        self.page_sur_patient_errand_label_address = QtWidgets.QLabel(self.groupBox)
        self.page_sur_patient_errand_label_address.setMinimumSize(QtCore.QSize(0, 30))
        self.page_sur_patient_errand_label_address.setMaximumSize(QtCore.QSize(16777215, 30))
        self.page_sur_patient_errand_label_address.setObjectName("page_sur_patient_errand_label_address")
        self.verticalLayout_2.addWidget(self.page_sur_patient_errand_label_address)
        self.page_sur_patient_errand_label_email = QtWidgets.QLabel(self.groupBox)
        self.page_sur_patient_errand_label_email.setMinimumSize(QtCore.QSize(0, 30))
        self.page_sur_patient_errand_label_email.setMaximumSize(QtCore.QSize(16777215, 30))
        self.page_sur_patient_errand_label_email.setObjectName("page_sur_patient_errand_label_email")
        self.verticalLayout_2.addWidget(self.page_sur_patient_errand_label_email)
        spacerItem11 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem11)
        self.gridLayout_7.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.page_sur_patient_errand_label_profile_picture = QtWidgets.QLabel(self.groupBox)
        self.page_sur_patient_errand_label_profile_picture.setMinimumSize(QtCore.QSize(200, 200))
        self.page_sur_patient_errand_label_profile_picture.setMaximumSize(QtCore.QSize(200, 200))
        self.page_sur_patient_errand_label_profile_picture.setText("")
        self.page_sur_patient_errand_label_profile_picture.setScaledContents(True)
        self.page_sur_patient_errand_label_profile_picture.setObjectName("page_sur_patient_errand_label_profile_picture")
        self.gridLayout_7.addWidget(self.page_sur_patient_errand_label_profile_picture, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 1, 3, 1, 3)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.page_sur_patient_errand_button_download = QtWidgets.QToolButton(self.page_sur_patient_errand)
        self.page_sur_patient_errand_button_download.setEnabled(False)
        self.page_sur_patient_errand_button_download.setMinimumSize(QtCore.QSize(30, 30))
        self.page_sur_patient_errand_button_download.setMaximumSize(QtCore.QSize(30, 30))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("icons/download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_sur_patient_errand_button_download.setIcon(icon13)
        self.page_sur_patient_errand_button_download.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_patient_errand_button_download.setObjectName("page_sur_patient_errand_button_download")
        self.gridLayout_6.addWidget(self.page_sur_patient_errand_button_download, 0, 2, 1, 1)
        self.page_sur_patient_errand_button_view = QtWidgets.QToolButton(self.page_sur_patient_errand)
        self.page_sur_patient_errand_button_view.setEnabled(False)
        self.page_sur_patient_errand_button_view.setMinimumSize(QtCore.QSize(30, 30))
        self.page_sur_patient_errand_button_view.setMaximumSize(QtCore.QSize(30, 30))
        self.page_sur_patient_errand_button_view.setIcon(icon12)
        self.page_sur_patient_errand_button_view.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_patient_errand_button_view.setObjectName("page_sur_patient_errand_button_view")
        self.gridLayout_6.addWidget(self.page_sur_patient_errand_button_view, 0, 5, 1, 1)
        self.page_sur_patient_errand_button_share = QtWidgets.QToolButton(self.page_sur_patient_errand)
        self.page_sur_patient_errand_button_share.setEnabled(False)
        self.page_sur_patient_errand_button_share.setMinimumSize(QtCore.QSize(30, 30))
        self.page_sur_patient_errand_button_share.setMaximumSize(QtCore.QSize(30, 30))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("icons/share.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_sur_patient_errand_button_share.setIcon(icon14)
        self.page_sur_patient_errand_button_share.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_patient_errand_button_share.setObjectName("page_sur_patient_errand_button_share")
        self.gridLayout_6.addWidget(self.page_sur_patient_errand_button_share, 0, 3, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem12, 0, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem13, 0, 4, 1, 1)
        self.page_sur_patient_errand_button_back = QtWidgets.QToolButton(self.page_sur_patient_errand)
        self.page_sur_patient_errand_button_back.setMinimumSize(QtCore.QSize(30, 30))
        self.page_sur_patient_errand_button_back.setMaximumSize(QtCore.QSize(75, 30))
        self.page_sur_patient_errand_button_back.setIcon(icon11)
        self.page_sur_patient_errand_button_back.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_patient_errand_button_back.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.page_sur_patient_errand_button_back.setObjectName("page_sur_patient_errand_button_back")
        self.gridLayout_6.addWidget(self.page_sur_patient_errand_button_back, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_6, 5, 2, 1, 4)
        self.page_sur_patient_errand_label_patients_profile = QtWidgets.QLabel(self.page_sur_patient_errand)
        self.page_sur_patient_errand_label_patients_profile.setMinimumSize(QtCore.QSize(0, 40))
        self.page_sur_patient_errand_label_patients_profile.setMaximumSize(QtCore.QSize(16777215, 40))
        self.page_sur_patient_errand_label_patients_profile.setStyleSheet("font-size: 20pt;")
        self.page_sur_patient_errand_label_patients_profile.setObjectName("page_sur_patient_errand_label_patients_profile")
        self.gridLayout_3.addWidget(self.page_sur_patient_errand_label_patients_profile, 0, 3, 1, 1)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.page_sur_patient_errand_label_patients_scans = QtWidgets.QLabel(self.page_sur_patient_errand)
        self.page_sur_patient_errand_label_patients_scans.setMinimumSize(QtCore.QSize(0, 40))
        self.page_sur_patient_errand_label_patients_scans.setMaximumSize(QtCore.QSize(16777215, 40))
        self.page_sur_patient_errand_label_patients_scans.setStyleSheet("font-size: 20pt;")
        self.page_sur_patient_errand_label_patients_scans.setObjectName("page_sur_patient_errand_label_patients_scans")
        self.gridLayout_11.addWidget(self.page_sur_patient_errand_label_patients_scans, 0, 0, 1, 1)
        self.page_sur_patient_errand_search_box = QtWidgets.QTextEdit(self.page_sur_patient_errand)
        self.page_sur_patient_errand_search_box.setMaximumSize(QtCore.QSize(200, 30))
        self.page_sur_patient_errand_search_box.setObjectName("page_sur_patient_errand_search_box")
        self.gridLayout_11.addWidget(self.page_sur_patient_errand_search_box, 0, 1, 1, 1)
        self.page_sur_patient_errand_errand_list = QtWidgets.QTreeWidget(self.page_sur_patient_errand)
        self.page_sur_patient_errand_errand_list.setObjectName("page_sur_patient_errand_errand_list")
        self.gridLayout_11.addWidget(self.page_sur_patient_errand_errand_list, 1, 0, 1, 2)
        self.gridLayout_3.addLayout(self.gridLayout_11, 2, 3, 1, 3)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.page_sur_patient_errand_label_report = QtWidgets.QLabel(self.page_sur_patient_errand)
        self.page_sur_patient_errand_label_report.setMinimumSize(QtCore.QSize(0, 40))
        self.page_sur_patient_errand_label_report.setMaximumSize(QtCore.QSize(16777215, 40))
        self.page_sur_patient_errand_label_report.setStyleSheet("font-size: 20pt;")
        self.page_sur_patient_errand_label_report.setScaledContents(True)
        self.page_sur_patient_errand_label_report.setWordWrap(False)
        self.page_sur_patient_errand_label_report.setObjectName("page_sur_patient_errand_label_report")
        self.gridLayout_9.addWidget(self.page_sur_patient_errand_label_report, 0, 0, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem14, 0, 1, 1, 1)
        self.page_sur_patient_errand_report_frame = QtWidgets.QFrame(self.page_sur_patient_errand)
        self.page_sur_patient_errand_report_frame.setMinimumSize(QtCore.QSize(500, 0))
        self.page_sur_patient_errand_report_frame.setMaximumSize(QtCore.QSize(4545245, 16777215))
        self.page_sur_patient_errand_report_frame.setStyleSheet("")
        self.page_sur_patient_errand_report_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.page_sur_patient_errand_report_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_sur_patient_errand_report_frame.setLineWidth(0)
        self.page_sur_patient_errand_report_frame.setObjectName("page_sur_patient_errand_report_frame")
        self.page_sur_patient_errand_report_frame_grid = QtWidgets.QGridLayout(self.page_sur_patient_errand_report_frame)
        self.page_sur_patient_errand_report_frame_grid.setContentsMargins(0, 0, 0, 0)
        self.page_sur_patient_errand_report_frame_grid.setObjectName("page_sur_patient_errand_report_frame_grid")
        self.page_sur_patient_errand_report = QtWidgets.QWidget(self.page_sur_patient_errand_report_frame)
        self.page_sur_patient_errand_report.setObjectName("page_sur_patient_errand_report")
        self.page_sur_patient_errand_report_frame_grid.addWidget(self.page_sur_patient_errand_report, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.page_sur_patient_errand_report_frame, 1, 0, 1, 2)
        self.gridLayout_3.addLayout(self.gridLayout_9, 0, 2, 3, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem15, 0, 4, 1, 1)
        sur.addWidget(self.page_sur_patient_errand)
        self.page_sur_home = QtWidgets.QWidget()
        self.page_sur_home.setObjectName("page_sur_home")
        self.gridLayout = QtWidgets.QGridLayout(self.page_sur_home)
        self.gridLayout.setObjectName("gridLayout")
        self.page_sur_home_treatment_list = QtWidgets.QTreeWidget(self.page_sur_home)
        self.page_sur_home_treatment_list.setObjectName("page_sur_home_treatment_list")
        self.gridLayout.addWidget(self.page_sur_home_treatment_list, 3, 1, 1, 3)
        self.page_sur_home_textEdit_search = QtWidgets.QTextEdit(self.page_sur_home)
        self.page_sur_home_textEdit_search.setMaximumSize(QtCore.QSize(200, 25))
        self.page_sur_home_textEdit_search.setObjectName("page_sur_home_textEdit_search")
        self.gridLayout.addWidget(self.page_sur_home_textEdit_search, 2, 3, 1, 1)
        self.page_sur_home_logout = QtWidgets.QToolButton(self.page_sur_home)
        self.page_sur_home_logout.setMinimumSize(QtCore.QSize(30, 30))
        self.page_sur_home_logout.setMaximumSize(QtCore.QSize(105, 30))
        self.page_sur_home_logout.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.page_sur_home_logout.setIcon(icon4)
        self.page_sur_home_logout.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_home_logout.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.page_sur_home_logout.setObjectName("page_sur_home_logout")
        self.gridLayout.addWidget(self.page_sur_home_logout, 0, 3, 1, 1)
        self.page_sur_home_button_colleagues = QtWidgets.QToolButton(self.page_sur_home)
        self.page_sur_home_button_colleagues.setEnabled(False)
        self.page_sur_home_button_colleagues.setMinimumSize(QtCore.QSize(30, 30))
        self.page_sur_home_button_colleagues.setMaximumSize(QtCore.QSize(30, 30))
        self.page_sur_home_button_colleagues.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("icons/colleagues.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_sur_home_button_colleagues.setIcon(icon15)
        self.page_sur_home_button_colleagues.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_home_button_colleagues.setObjectName("page_sur_home_button_colleagues")
        self.gridLayout.addWidget(self.page_sur_home_button_colleagues, 0, 1, 1, 1)
        self.page_sur_home_button_proceed = QtWidgets.QToolButton(self.page_sur_home)
        self.page_sur_home_button_proceed.setEnabled(False)
        self.page_sur_home_button_proceed.setMinimumSize(QtCore.QSize(30, 30))
        self.page_sur_home_button_proceed.setMaximumSize(QtCore.QSize(30, 30))
        self.page_sur_home_button_proceed.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("icons/forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_sur_home_button_proceed.setIcon(icon16)
        self.page_sur_home_button_proceed.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_home_button_proceed.setObjectName("page_sur_home_button_proceed")
        self.gridLayout.addWidget(self.page_sur_home_button_proceed, 4, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.page_sur_home)
        self.label.setStyleSheet("font-size: 20pt;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 1, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem16, 0, 2, 1, 1)
        sur.addWidget(self.page_sur_home)

        self.retranslateUi(sur)
        sur.setCurrentIndex(2)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(sur)

    def retranslateUi(self, sur):
        _translate = QtCore.QCoreApplication.translate
        sur.setWindowTitle(_translate("sur", "StackedWidget"))
        self.page_sur_view_edit_button_link_windows.setToolTip(_translate("sur", "Activate\n"
"2D-3D Link"))
        self.page_sur_view_edit_button_link_windows.setText(_translate("sur", "Activate\n"
"2D-3D Link"))
        self.page_sur_view_edit_button_3d_fullscreen.setToolTip(_translate("sur", "Fullscreen - 2D"))
        self.page_sur_view_edit_button_3d_fullscreen.setText(_translate("sur", "Fullscreen 3D"))
        self.page_sur_view_edit_button_3d_zoom_in.setToolTip(_translate("sur", "Zoom in - 3D"))
        self.page_sur_view_edit_button_3d_zoom_in.setText(_translate("sur", "Zoom In"))
        self.page_sur_view_edit_button_3d_zoom_out.setToolTip(_translate("sur", "Zoom out - 3D"))
        self.page_sur_view_edit_button_3d_zoom_out.setText(_translate("sur", "Zoom Out"))
        self.page_sur_view_edit_button_logout.setToolTip(_translate("sur", "Logout"))
        self.page_sur_view_edit_button_logout.setText(_translate("sur", "   Logout"))
        self.page_sur_view_edit_button_2d_fullscreen.setToolTip(_translate("sur", "Fullscreen - 3D"))
        self.page_sur_view_edit_button_2d_fullscreen.setText(_translate("sur", "Fullscreen 2D"))
        self.page_sur_view_edit_button_2d_zoom_out.setToolTip(_translate("sur", "Zoom out - 2D"))
        self.page_sur_view_edit_button_2d_zoom_out.setText(_translate("sur", "Zoom Out"))
        self.page_sur_view_edit_button_2d_zoom_in.setToolTip(_translate("sur", "Zoom in - 2D"))
        self.page_sur_view_edit_button_2d_zoom_in.setText(_translate("sur", "Zoom In"))
        self.page_sur_view_edit_2d_slider_color_level.setToolTip(_translate("sur", "Change color level"))
        self.page_sur_view_edit_2d_slider_color_window.setToolTip(_translate("sur", "Change window color"))
        self.page_sur_view_edit_button_2d_next_note.setToolTip(_translate("sur", "Go to next finding"))
        self.page_sur_view_edit_button_2d_next_note.setText(_translate("sur", "Next Note"))
        self.page_sur_view_edit_button_2d_previous_slice.setToolTip(_translate("sur", "Go to previous slice"))
        self.page_sur_view_edit_button_2d_previous_slice.setText(_translate("sur", "Previous Slice"))
        self.page_sur_view_edit_button_2d_previous_note.setToolTip(_translate("sur", "Go to previous finding"))
        self.page_sur_view_edit_button_2d_previous_note.setText(_translate("sur", "Previous Note"))
        self.page_sur_view_edit_button_2d_play_pause.setToolTip(_translate("sur", "Play"))
        self.page_sur_view_edit_button_2d_play_pause.setText(_translate("sur", "Play/Pause"))
        self.textEdit_2.setPlaceholderText(_translate("sur", "Insert findings"))
        self.textEdit.setPlaceholderText(_translate("sur", "Insert location"))
        self.toolButton.setToolTip(_translate("sur", "Add finding"))
        self.toolButton.setText(_translate("sur", "Add Annotation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("sur", "Findings"))
        self.textEdit_3.setPlaceholderText(_translate("sur", "Insert impression"))
        self.toolButton_2.setToolTip(_translate("sur", "Add impression"))
        self.toolButton_2.setText(_translate("sur", "Add Impression"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("sur", "Impression"))
        self.page_sur_view_edit_button_2d_next_slice.setToolTip(_translate("sur", "Go to next slice"))
        self.page_sur_view_edit_button_2d_next_slice.setText(_translate("sur", "Next Slice"))
        self.page_sur_view_edit_button_back.setToolTip(_translate("sur", "Go back"))
        self.page_sur_view_edit_button_back.setText(_translate("sur", "Back"))
        self.page_sur_view_edit_button_preview_report.setToolTip(_translate("sur", "Preview Report"))
        self.page_sur_patient_errand_button_logout.setToolTip(_translate("sur", "Logout"))
        self.page_sur_patient_errand_button_logout.setText(_translate("sur", "   Logout"))
        self.page_sur_patient_errand_label_name.setText(_translate("sur", "NAME"))
        self.page_sur_patient_errand_label_age.setText(_translate("sur", "AGE"))
        self.page_sur_patient_errand_label_phone_number.setText(_translate("sur", "PHONE NUMBER"))
        self.page_sur_patient_errand_label_address.setText(_translate("sur", "ADDRESS"))
        self.page_sur_patient_errand_label_email.setText(_translate("sur", "EMAIL"))
        self.page_sur_patient_errand_button_download.setToolTip(_translate("sur", "Download report"))
        self.page_sur_patient_errand_button_download.setText(_translate("sur", "Download"))
        self.page_sur_patient_errand_button_view.setToolTip(_translate("sur", "View scan"))
        self.page_sur_patient_errand_button_view.setText(_translate("sur", "View"))
        self.page_sur_patient_errand_button_share.setToolTip(_translate("sur", "Share patient file"))
        self.page_sur_patient_errand_button_share.setText(_translate("sur", "Share"))
        self.page_sur_patient_errand_button_back.setToolTip(_translate("sur", "Go back"))
        self.page_sur_patient_errand_button_back.setText(_translate("sur", "Back"))
        self.page_sur_patient_errand_label_patients_profile.setText(_translate("sur", "Patient\'s Profile"))
        self.page_sur_patient_errand_label_patients_scans.setText(_translate("sur", "Patient\'s Scans"))
        self.page_sur_patient_errand_search_box.setHtml(_translate("sur", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.page_sur_patient_errand_search_box.setPlaceholderText(_translate("sur", "Search..."))
        self.page_sur_patient_errand_errand_list.headerItem().setText(0, _translate("sur", "ID"))
        self.page_sur_patient_errand_errand_list.headerItem().setText(1, _translate("sur", "Date"))
        self.page_sur_patient_errand_errand_list.headerItem().setText(2, _translate("sur", "Scan"))
        self.page_sur_patient_errand_errand_list.headerItem().setText(3, _translate("sur", "Clinic"))
        self.page_sur_patient_errand_errand_list.headerItem().setText(4, _translate("sur", "Status"))
        self.page_sur_patient_errand_label_report.setText(_translate("sur", "Report"))
        self.page_sur_home_treatment_list.setSortingEnabled(True)
        self.page_sur_home_treatment_list.headerItem().setText(0, _translate("sur", "Surname"))
        self.page_sur_home_treatment_list.headerItem().setText(1, _translate("sur", "First name"))
        self.page_sur_home_treatment_list.headerItem().setText(2, _translate("sur", "Patient ID"))
        self.page_sur_home_treatment_list.headerItem().setText(3, _translate("sur", "Sex"))
        self.page_sur_home_treatment_list.headerItem().setText(4, _translate("sur", "Date ordered"))
        self.page_sur_home_treatment_list.headerItem().setText(5, _translate("sur", "Scan"))
        self.page_sur_home_treatment_list.headerItem().setText(6, _translate("sur", "Status"))
        self.page_sur_home_treatment_list.headerItem().setText(7, _translate("sur", "Order ID"))
        self.page_sur_home_textEdit_search.setHtml(_translate("sur", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Search box</p></body></html>"))
        self.page_sur_home_logout.setToolTip(_translate("sur", "Logout"))
        self.page_sur_home_logout.setText(_translate("sur", "   Logout"))
        self.page_sur_home_button_colleagues.setToolTip(_translate("sur", "Show colleagues"))
        self.page_sur_home_button_colleagues.setText(_translate("sur", "My profile "))
        self.page_sur_home_button_proceed.setToolTip(_translate("sur", "Go to patients page"))
        self.page_sur_home_button_proceed.setText(_translate("sur", "Proceed"))
        self.label.setText(_translate("sur", "My Patients"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    sur = QtWidgets.QStackedWidget()
    ui = Ui_sur()
    ui.setupUi(sur)
    sur.show()
    sys.exit(app.exec_())

