# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sur.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_sur(object):
    def setupUi(self, sur):
        sur.setObjectName("sur")
        sur.resize(1235, 806)
        self.page_sur_view_edit = QtWidgets.QWidget()
        self.page_sur_view_edit.setObjectName("page_sur_view_edit")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_sur_view_edit)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.page_sur_view_edit_button_tools = QtWidgets.QToolButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_tools.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.page_sur_view_edit_button_tools.setStyleSheet("background-color: rgba(255, 255, 255,0)")
        self.page_sur_view_edit_button_tools.setObjectName("page_sur_view_edit_button_tools")
        self.gridLayout_5.addWidget(self.page_sur_view_edit_button_tools, 4, 1, 1, 2)
        self.page_sur_view_edit_button_back = QtWidgets.QToolButton(self.page_sur_view_edit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_sur_view_edit_button_back.sizePolicy().hasHeightForWidth())
        self.page_sur_view_edit_button_back.setSizePolicy(sizePolicy)
        self.page_sur_view_edit_button_back.setMinimumSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_back.setMaximumSize(QtCore.QSize(75, 30))
        self.page_sur_view_edit_button_back.setAutoFillBackground(False)
        self.page_sur_view_edit_button_back.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_sur_view_edit_button_back.setIcon(icon)
        self.page_sur_view_edit_button_back.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_back.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.page_sur_view_edit_button_back.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.page_sur_view_edit_button_back.setObjectName("page_sur_view_edit_button_back")
        self.gridLayout_5.addWidget(self.page_sur_view_edit_button_back, 4, 0, 1, 1)
        self.page_sure_view_edit_tab = QtWidgets.QTabWidget(self.page_sur_view_edit)
        self.page_sure_view_edit_tab.setMinimumSize(QtCore.QSize(300, 200))
        self.page_sure_view_edit_tab.setMaximumSize(QtCore.QSize(600, 300))
        self.page_sure_view_edit_tab.setObjectName("page_sure_view_edit_tab")
        self.page_sure_view_edit_tab_note = QtWidgets.QWidget()
        self.page_sure_view_edit_tab_note.setObjectName("page_sure_view_edit_tab_note")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page_sure_view_edit_tab_note)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.page_sur_view_edit_insert_link = QtWidgets.QTextEdit(self.page_sure_view_edit_tab_note)
        self.page_sur_view_edit_insert_link.setObjectName("page_sur_view_edit_insert_link")
        self.gridLayout_8.addWidget(self.page_sur_view_edit_insert_link, 1, 0, 1, 3)
        self.page_sur_view_edit_insert_note = QtWidgets.QTextEdit(self.page_sure_view_edit_tab_note)
        self.page_sur_view_edit_insert_note.setObjectName("page_sur_view_edit_insert_note")
        self.gridLayout_8.addWidget(self.page_sur_view_edit_insert_note, 0, 0, 1, 3)
        self.page_sur_view_edit_button_add_note = QtWidgets.QToolButton(self.page_sure_view_edit_tab_note)
        self.page_sur_view_edit_button_add_note.setMinimumSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_add_note.setMaximumSize(QtCore.QSize(30, 30))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_sur_view_edit_button_add_note.setIcon(icon1)
        self.page_sur_view_edit_button_add_note.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_add_note.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.page_sur_view_edit_button_add_note.setObjectName("page_sur_view_edit_button_add_note")
        self.gridLayout_8.addWidget(self.page_sur_view_edit_button_add_note, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem1, 2, 2, 1, 1)
        self.page_sure_view_edit_tab.addTab(self.page_sure_view_edit_tab_note, "")
        self.page_sure_view_edit_tab_impression = QtWidgets.QWidget()
        self.page_sure_view_edit_tab_impression.setObjectName("page_sure_view_edit_tab_impression")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.page_sure_view_edit_tab_impression)
        self.gridLayout_10.setObjectName("gridLayout_10")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem3, 1, 2, 1, 1)
        self.page_sur_view_edit_button_add_impression = QtWidgets.QToolButton(self.page_sure_view_edit_tab_impression)
        self.page_sur_view_edit_button_add_impression.setMinimumSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_add_impression.setMaximumSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_add_impression.setIcon(icon1)
        self.page_sur_view_edit_button_add_impression.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_add_impression.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.page_sur_view_edit_button_add_impression.setObjectName("page_sur_view_edit_button_add_impression")
        self.gridLayout_10.addWidget(self.page_sur_view_edit_button_add_impression, 1, 1, 1, 1)
        self.page_sur_view_edit_insert_impression = QtWidgets.QTextEdit(self.page_sure_view_edit_tab_impression)
        self.page_sur_view_edit_insert_impression.setObjectName("page_sur_view_edit_insert_impression")
        self.gridLayout_10.addWidget(self.page_sur_view_edit_insert_impression, 0, 0, 1, 3)
        self.page_sure_view_edit_tab.addTab(self.page_sure_view_edit_tab_impression, "")
        self.gridLayout_5.addWidget(self.page_sure_view_edit_tab, 2, 0, 1, 4)
        self.page_sur_view_edit_button_2d_previous_note = QtWidgets.QToolButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_2d_previous_note.setMinimumSize(QtCore.QSize(0, 0))
        self.page_sur_view_edit_button_2d_previous_note.setMaximumSize(QtCore.QSize(30, 30))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/previous_note.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_sur_view_edit_button_2d_previous_note.setIcon(icon2)
        self.page_sur_view_edit_button_2d_previous_note.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_2d_previous_note.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.page_sur_view_edit_button_2d_previous_note.setObjectName("page_sur_view_edit_button_2d_previous_note")
        self.gridLayout_5.addWidget(self.page_sur_view_edit_button_2d_previous_note, 0, 1, 1, 1)
        self.page_sur_view_edit_report_frame = QtWidgets.QFrame(self.page_sur_view_edit)
        self.page_sur_view_edit_report_frame.setMinimumSize(QtCore.QSize(300, 300))
        self.page_sur_view_edit_report_frame.setMaximumSize(QtCore.QSize(600, 16777215))
        self.page_sur_view_edit_report_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.page_sur_view_edit_report_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_sur_view_edit_report_frame.setLineWidth(0)
        self.page_sur_view_edit_report_frame.setObjectName("page_sur_view_edit_report_frame")
        self.page_sur_view_edit_report_frame_grid = QtWidgets.QGridLayout(self.page_sur_view_edit_report_frame)
        self.page_sur_view_edit_report_frame_grid.setContentsMargins(0, 0, 0, 0)
        self.page_sur_view_edit_report_frame_grid.setObjectName("page_sur_view_edit_report_frame_grid")
        self.page_sur_view_edit_report = QtWidgets.QWidget(self.page_sur_view_edit_report_frame)
        self.page_sur_view_edit_report.setObjectName("page_sur_view_edit_report")
        self.page_sur_view_edit_report_frame_grid.addWidget(self.page_sur_view_edit_report, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.page_sur_view_edit_report_frame, 1, 0, 1, 4)
        self.page_sur_view_edit_button_save_report = QtWidgets.QToolButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_save_report.setEnabled(False)
        self.page_sur_view_edit_button_save_report.setMinimumSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_save_report.setMaximumSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_save_report.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.page_sur_view_edit_button_save_report.setStyleSheet("border: none;")
        self.page_sur_view_edit_button_save_report.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_sur_view_edit_button_save_report.setIcon(icon3)
        self.page_sur_view_edit_button_save_report.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_save_report.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.page_sur_view_edit_button_save_report.setObjectName("page_sur_view_edit_button_save_report")
        self.gridLayout_5.addWidget(self.page_sur_view_edit_button_save_report, 4, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem4, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem5, 0, 3, 1, 1)
        self.page_sur_view_edit_tools = QtWidgets.QToolBox(self.page_sur_view_edit)
        self.page_sur_view_edit_tools.setMaximumSize(QtCore.QSize(16777215, 200))
        self.page_sur_view_edit_tools.setToolTip("")
        self.page_sur_view_edit_tools.setObjectName("page_sur_view_edit_tools")
        self.page_sur_view_edit_tools_orientation = QtWidgets.QWidget()
        self.page_sur_view_edit_tools_orientation.setGeometry(QtCore.QRect(0, 0, 387, 69))
        self.page_sur_view_edit_tools_orientation.setStyleSheet("")
        self.page_sur_view_edit_tools_orientation.setObjectName("page_sur_view_edit_tools_orientation")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.page_sur_view_edit_tools_orientation)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radio_button_axial = QtWidgets.QRadioButton(self.page_sur_view_edit_tools_orientation)
        self.radio_button_axial.setChecked(True)
        self.radio_button_axial.setObjectName("radio_button_axial")
        self.page_sur_view_edit_radio_group_orientation = QtWidgets.QButtonGroup(sur)
        self.page_sur_view_edit_radio_group_orientation.setObjectName("page_sur_view_edit_radio_group_orientation")
        self.page_sur_view_edit_radio_group_orientation.addButton(self.radio_button_axial)
        self.horizontalLayout_3.addWidget(self.radio_button_axial)
        self.radio_button_sagittal = QtWidgets.QRadioButton(self.page_sur_view_edit_tools_orientation)
        self.radio_button_sagittal.setObjectName("radio_button_sagittal")
        self.page_sur_view_edit_radio_group_orientation.addButton(self.radio_button_sagittal)
        self.horizontalLayout_3.addWidget(self.radio_button_sagittal)
        self.radio_button_coronal = QtWidgets.QRadioButton(self.page_sur_view_edit_tools_orientation)
        self.radio_button_coronal.setObjectName("radio_button_coronal")
        self.page_sur_view_edit_radio_group_orientation.addButton(self.radio_button_coronal)
        self.horizontalLayout_3.addWidget(self.radio_button_coronal)
        self.page_sur_view_edit_tools.addItem(self.page_sur_view_edit_tools_orientation, "")
        self.page_sur_view_edit_tools_tissue = QtWidgets.QWidget()
        self.page_sur_view_edit_tools_tissue.setGeometry(QtCore.QRect(0, 0, 433, 69))
        self.page_sur_view_edit_tools_tissue.setStyleSheet("")
        self.page_sur_view_edit_tools_tissue.setObjectName("page_sur_view_edit_tools_tissue")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.page_sur_view_edit_tools_tissue)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_All = QtWidgets.QCheckBox(self.page_sur_view_edit_tools_tissue)
        self.checkBox_All.setChecked(True)
        self.checkBox_All.setObjectName("checkBox_All")
        self.page_sur_view_edit_check_group_tissue = QtWidgets.QButtonGroup(sur)
        self.page_sur_view_edit_check_group_tissue.setObjectName("page_sur_view_edit_check_group_tissue")
        self.page_sur_view_edit_check_group_tissue.setExclusive(False)
        self.page_sur_view_edit_check_group_tissue.addButton(self.checkBox_All)
        self.horizontalLayout_2.addWidget(self.checkBox_All)
        self.checkBox_Soft = QtWidgets.QCheckBox(self.page_sur_view_edit_tools_tissue)
        self.checkBox_Soft.setObjectName("checkBox_Soft")
        self.page_sur_view_edit_check_group_tissue.addButton(self.checkBox_Soft)
        self.horizontalLayout_2.addWidget(self.checkBox_Soft)
        self.checkBox_Bone = QtWidgets.QCheckBox(self.page_sur_view_edit_tools_tissue)
        self.checkBox_Bone.setObjectName("checkBox_Bone")
        self.page_sur_view_edit_check_group_tissue.addButton(self.checkBox_Bone)
        self.horizontalLayout_2.addWidget(self.checkBox_Bone)
        self.checkBox_Muscle = QtWidgets.QCheckBox(self.page_sur_view_edit_tools_tissue)
        self.checkBox_Muscle.setObjectName("checkBox_Muscle")
        self.page_sur_view_edit_check_group_tissue.addButton(self.checkBox_Muscle)
        self.horizontalLayout_2.addWidget(self.checkBox_Muscle)
        self.checkBox_Fat = QtWidgets.QCheckBox(self.page_sur_view_edit_tools_tissue)
        self.checkBox_Fat.setObjectName("checkBox_Fat")
        self.page_sur_view_edit_check_group_tissue.addButton(self.checkBox_Fat)
        self.horizontalLayout_2.addWidget(self.checkBox_Fat)
        self.checkBox_Skin = QtWidgets.QCheckBox(self.page_sur_view_edit_tools_tissue)
        self.checkBox_Skin.setStyleSheet("c")
        self.checkBox_Skin.setObjectName("checkBox_Skin")
        self.page_sur_view_edit_check_group_tissue.addButton(self.checkBox_Skin)
        self.horizontalLayout_2.addWidget(self.checkBox_Skin)
        self.page_sur_view_edit_tools.addItem(self.page_sur_view_edit_tools_tissue, "")
        self.page_sur_view_edit_tools_transparency = QtWidgets.QWidget()
        self.page_sur_view_edit_tools_transparency.setGeometry(QtCore.QRect(0, 0, 416, 73))
        self.page_sur_view_edit_tools_transparency.setStyleSheet("")
        self.page_sur_view_edit_tools_transparency.setObjectName("page_sur_view_edit_tools_transparency")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.page_sur_view_edit_tools_transparency)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.page_sur_view_edit_layout_transparency_volume = QtWidgets.QVBoxLayout()
        self.page_sur_view_edit_layout_transparency_volume.setObjectName("page_sur_view_edit_layout_transparency_volume")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.page_sur_view_edit_layout_transparency_volume.addItem(spacerItem6)
        self.page_sur_view_edit_slider_transparency_volume = QtWidgets.QSlider(self.page_sur_view_edit_tools_transparency)
        self.page_sur_view_edit_slider_transparency_volume.setMaximum(100)
        self.page_sur_view_edit_slider_transparency_volume.setSingleStep(1)
        self.page_sur_view_edit_slider_transparency_volume.setProperty("value", 20)
        self.page_sur_view_edit_slider_transparency_volume.setOrientation(QtCore.Qt.Horizontal)
        self.page_sur_view_edit_slider_transparency_volume.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.page_sur_view_edit_slider_transparency_volume.setObjectName("page_sur_view_edit_slider_transparency_volume")
        self.page_sur_view_edit_layout_transparency_volume.addWidget(self.page_sur_view_edit_slider_transparency_volume)
        self.page_sur_view_edit_label_transparency_volume = QtWidgets.QLabel(self.page_sur_view_edit_tools_transparency)
        self.page_sur_view_edit_label_transparency_volume.setStyleSheet("")
        self.page_sur_view_edit_label_transparency_volume.setAlignment(QtCore.Qt.AlignCenter)
        self.page_sur_view_edit_label_transparency_volume.setObjectName("page_sur_view_edit_label_transparency_volume")
        self.page_sur_view_edit_layout_transparency_volume.addWidget(self.page_sur_view_edit_label_transparency_volume)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.page_sur_view_edit_layout_transparency_volume.addItem(spacerItem7)
        self.horizontalLayout.addLayout(self.page_sur_view_edit_layout_transparency_volume)
        self.page_sur_view_edit_layout_transparency_segmentation = QtWidgets.QVBoxLayout()
        self.page_sur_view_edit_layout_transparency_segmentation.setObjectName("page_sur_view_edit_layout_transparency_segmentation")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.page_sur_view_edit_layout_transparency_segmentation.addItem(spacerItem8)
        self.page_sur_view_edit_slider_transparency_segmentation = QtWidgets.QSlider(self.page_sur_view_edit_tools_transparency)
        self.page_sur_view_edit_slider_transparency_segmentation.setMaximum(100)
        self.page_sur_view_edit_slider_transparency_segmentation.setProperty("value", 33)
        self.page_sur_view_edit_slider_transparency_segmentation.setSliderPosition(33)
        self.page_sur_view_edit_slider_transparency_segmentation.setOrientation(QtCore.Qt.Horizontal)
        self.page_sur_view_edit_slider_transparency_segmentation.setObjectName("page_sur_view_edit_slider_transparency_segmentation")
        self.page_sur_view_edit_layout_transparency_segmentation.addWidget(self.page_sur_view_edit_slider_transparency_segmentation)
        self.page_sur_view_edit_label_transparency_segmentation = QtWidgets.QLabel(self.page_sur_view_edit_tools_transparency)
        self.page_sur_view_edit_label_transparency_segmentation.setStyleSheet("")
        self.page_sur_view_edit_label_transparency_segmentation.setAlignment(QtCore.Qt.AlignCenter)
        self.page_sur_view_edit_label_transparency_segmentation.setObjectName("page_sur_view_edit_label_transparency_segmentation")
        self.page_sur_view_edit_layout_transparency_segmentation.addWidget(self.page_sur_view_edit_label_transparency_segmentation)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.page_sur_view_edit_layout_transparency_segmentation.addItem(spacerItem9)
        self.horizontalLayout.addLayout(self.page_sur_view_edit_layout_transparency_segmentation)
        self.page_sur_view_edit_layout_transparency_active = QtWidgets.QVBoxLayout()
        self.page_sur_view_edit_layout_transparency_active.setObjectName("page_sur_view_edit_layout_transparency_active")
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.page_sur_view_edit_layout_transparency_active.addItem(spacerItem10)
        self.page_sur_view_edit_slider_transparency_active = QtWidgets.QSlider(self.page_sur_view_edit_tools_transparency)
        self.page_sur_view_edit_slider_transparency_active.setMaximum(100)
        self.page_sur_view_edit_slider_transparency_active.setProperty("value", 40)
        self.page_sur_view_edit_slider_transparency_active.setOrientation(QtCore.Qt.Horizontal)
        self.page_sur_view_edit_slider_transparency_active.setObjectName("page_sur_view_edit_slider_transparency_active")
        self.page_sur_view_edit_layout_transparency_active.addWidget(self.page_sur_view_edit_slider_transparency_active)
        self.page_sur_view_edit_label_transparency_active = QtWidgets.QLabel(self.page_sur_view_edit_tools_transparency)
        self.page_sur_view_edit_label_transparency_active.setStyleSheet("")
        self.page_sur_view_edit_label_transparency_active.setAlignment(QtCore.Qt.AlignCenter)
        self.page_sur_view_edit_label_transparency_active.setObjectName("page_sur_view_edit_label_transparency_active")
        self.page_sur_view_edit_layout_transparency_active.addWidget(self.page_sur_view_edit_label_transparency_active)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.page_sur_view_edit_layout_transparency_active.addItem(spacerItem11)
        self.horizontalLayout.addLayout(self.page_sur_view_edit_layout_transparency_active)
        self.page_sur_view_edit_tools.addItem(self.page_sur_view_edit_tools_transparency, "")
        self.page_sur_view_edit_tools_link = QtWidgets.QWidget()
        self.page_sur_view_edit_tools_link.setGeometry(QtCore.QRect(0, 0, 433, 69))
        self.page_sur_view_edit_tools_link.setStyleSheet("")
        self.page_sur_view_edit_tools_link.setObjectName("page_sur_view_edit_tools_link")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.page_sur_view_edit_tools_link)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBox = QtWidgets.QCheckBox(self.page_sur_view_edit_tools_link)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.page_sur_view_edit_check_group_link = QtWidgets.QButtonGroup(sur)
        self.page_sur_view_edit_check_group_link.setObjectName("page_sur_view_edit_check_group_link")
        self.page_sur_view_edit_check_group_link.setExclusive(False)
        self.page_sur_view_edit_check_group_link.addButton(self.checkBox)
        self.horizontalLayout_4.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.page_sur_view_edit_tools_link)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.page_sur_view_edit_check_group_link.addButton(self.checkBox_2)
        self.horizontalLayout_4.addWidget(self.checkBox_2)
        self.page_sur_view_edit_tools.addItem(self.page_sur_view_edit_tools_link, "")
        self.gridLayout_5.addWidget(self.page_sur_view_edit_tools, 3, 0, 1, 4)
        self.page_sur_view_edit_button_2d_next_note = QtWidgets.QToolButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_2d_next_note.setMinimumSize(QtCore.QSize(0, 0))
        self.page_sur_view_edit_button_2d_next_note.setMaximumSize(QtCore.QSize(30, 30))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/next_note.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_sur_view_edit_button_2d_next_note.setIcon(icon4)
        self.page_sur_view_edit_button_2d_next_note.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_2d_next_note.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.page_sur_view_edit_button_2d_next_note.setObjectName("page_sur_view_edit_button_2d_next_note")
        self.gridLayout_5.addWidget(self.page_sur_view_edit_button_2d_next_note, 0, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_5, 0, 0, 4, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.page_sur_view_edit_button_link_windows = QtWidgets.QToolButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_link_windows.setMinimumSize(QtCore.QSize(0, 0))
        self.page_sur_view_edit_button_link_windows.setMaximumSize(QtCore.QSize(30, 30))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/unlink.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_sur_view_edit_button_link_windows.setIcon(icon5)
        self.page_sur_view_edit_button_link_windows.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_link_windows.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.page_sur_view_edit_button_link_windows.setObjectName("page_sur_view_edit_button_link_windows")
        self.gridLayout_2.addWidget(self.page_sur_view_edit_button_link_windows, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 1, 8, 3, 1)
        self.page_sur_view_edit_2d_layout = QtWidgets.QGridLayout()
        self.page_sur_view_edit_2d_layout.setObjectName("page_sur_view_edit_2d_layout")
        self.page_sur_view_edit_2d_slider_color_level = QtWidgets.QSlider(self.page_sur_view_edit)
        self.page_sur_view_edit_2d_slider_color_level.setMinimum(-5000)
        self.page_sur_view_edit_2d_slider_color_level.setMaximum(5000)
        self.page_sur_view_edit_2d_slider_color_level.setSingleStep(100)
        self.page_sur_view_edit_2d_slider_color_level.setPageStep(500)
        self.page_sur_view_edit_2d_slider_color_level.setProperty("value", -170)
        self.page_sur_view_edit_2d_slider_color_level.setOrientation(QtCore.Qt.Horizontal)
        self.page_sur_view_edit_2d_slider_color_level.setInvertedAppearance(True)
        self.page_sur_view_edit_2d_slider_color_level.setInvertedControls(True)
        self.page_sur_view_edit_2d_slider_color_level.setObjectName("page_sur_view_edit_2d_slider_color_level")
        self.page_sur_view_edit_2d_layout.addWidget(self.page_sur_view_edit_2d_slider_color_level, 2, 1, 1, 5)
        self.page_sur_view_edit_2d_view_frame = QtWidgets.QFrame(self.page_sur_view_edit)
        self.page_sur_view_edit_2d_view_frame.setMinimumSize(QtCore.QSize(350, 250))
        self.page_sur_view_edit_2d_view_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.page_sur_view_edit_2d_view_frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.page_sur_view_edit_2d_view_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.page_sur_view_edit_2d_view_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_sur_view_edit_2d_view_frame.setLineWidth(0)
        self.page_sur_view_edit_2d_view_frame.setObjectName("page_sur_view_edit_2d_view_frame")
        self.page_sur_view_edit_2d_view_frame_grid = QtWidgets.QGridLayout(self.page_sur_view_edit_2d_view_frame)
        self.page_sur_view_edit_2d_view_frame_grid.setContentsMargins(0, 0, 0, 0)
        self.page_sur_view_edit_2d_view_frame_grid.setSpacing(0)
        self.page_sur_view_edit_2d_view_frame_grid.setObjectName("page_sur_view_edit_2d_view_frame_grid")
        self.page_sur_view_edit_button_2d_zoom_out = QtWidgets.QToolButton(self.page_sur_view_edit_2d_view_frame)
        self.page_sur_view_edit_button_2d_zoom_out.setMinimumSize(QtCore.QSize(0, 0))
        self.page_sur_view_edit_button_2d_zoom_out.setMaximumSize(QtCore.QSize(30, 30))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/zoom_out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_sur_view_edit_button_2d_zoom_out.setIcon(icon6)
        self.page_sur_view_edit_button_2d_zoom_out.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_2d_zoom_out.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.page_sur_view_edit_button_2d_zoom_out.setObjectName("page_sur_view_edit_button_2d_zoom_out")
        self.page_sur_view_edit_2d_view_frame_grid.addWidget(self.page_sur_view_edit_button_2d_zoom_out, 0, 0, 1, 1)
        self.page_sur_view_edit_button_2d_zoom_in = QtWidgets.QToolButton(self.page_sur_view_edit_2d_view_frame)
        self.page_sur_view_edit_button_2d_zoom_in.setMinimumSize(QtCore.QSize(0, 0))
        self.page_sur_view_edit_button_2d_zoom_in.setMaximumSize(QtCore.QSize(30, 30))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/zoom_in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_sur_view_edit_button_2d_zoom_in.setIcon(icon7)
        self.page_sur_view_edit_button_2d_zoom_in.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_2d_zoom_in.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.page_sur_view_edit_button_2d_zoom_in.setObjectName("page_sur_view_edit_button_2d_zoom_in")
        self.page_sur_view_edit_2d_view_frame_grid.addWidget(self.page_sur_view_edit_button_2d_zoom_in, 0, 1, 1, 1)
        self.page_sur_view_edit_button_2d_fullscreen = QtWidgets.QToolButton(self.page_sur_view_edit_2d_view_frame)
        self.page_sur_view_edit_button_2d_fullscreen.setMinimumSize(QtCore.QSize(0, 0))
        self.page_sur_view_edit_button_2d_fullscreen.setMaximumSize(QtCore.QSize(30, 30))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/full_screen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_sur_view_edit_button_2d_fullscreen.setIcon(icon8)
        self.page_sur_view_edit_button_2d_fullscreen.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_2d_fullscreen.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.page_sur_view_edit_button_2d_fullscreen.setObjectName("page_sur_view_edit_button_2d_fullscreen")
        self.page_sur_view_edit_2d_view_frame_grid.addWidget(self.page_sur_view_edit_button_2d_fullscreen, 0, 3, 1, 1)
        self.page_sur_view_edit_button_2d_previous_slice = QtWidgets.QToolButton(self.page_sur_view_edit_2d_view_frame)
        self.page_sur_view_edit_button_2d_previous_slice.setMinimumSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_2d_previous_slice.setMaximumSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_2d_previous_slice.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons/previous_slice.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_sur_view_edit_button_2d_previous_slice.setIcon(icon9)
        self.page_sur_view_edit_button_2d_previous_slice.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_2d_previous_slice.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.page_sur_view_edit_button_2d_previous_slice.setObjectName("page_sur_view_edit_button_2d_previous_slice")
        self.page_sur_view_edit_2d_view_frame_grid.addWidget(self.page_sur_view_edit_button_2d_previous_slice, 0, 5, 1, 1)
        self.page_sur_view_edit_button_2d_next_slice = QtWidgets.QToolButton(self.page_sur_view_edit_2d_view_frame)
        self.page_sur_view_edit_button_2d_next_slice.setMinimumSize(QtCore.QSize(0, 0))
        self.page_sur_view_edit_button_2d_next_slice.setMaximumSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_2d_next_slice.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icons/next_slice.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_sur_view_edit_button_2d_next_slice.setIcon(icon10)
        self.page_sur_view_edit_button_2d_next_slice.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_2d_next_slice.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.page_sur_view_edit_button_2d_next_slice.setObjectName("page_sur_view_edit_button_2d_next_slice")
        self.page_sur_view_edit_2d_view_frame_grid.addWidget(self.page_sur_view_edit_button_2d_next_slice, 0, 7, 1, 1)
        self.page_sur_view_edit_button_2d_play_pause = QtWidgets.QToolButton(self.page_sur_view_edit_2d_view_frame)
        self.page_sur_view_edit_button_2d_play_pause.setMinimumSize(QtCore.QSize(0, 0))
        self.page_sur_view_edit_button_2d_play_pause.setMaximumSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_2d_play_pause.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_sur_view_edit_button_2d_play_pause.setIcon(icon11)
        self.page_sur_view_edit_button_2d_play_pause.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_2d_play_pause.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.page_sur_view_edit_button_2d_play_pause.setObjectName("page_sur_view_edit_button_2d_play_pause")
        self.page_sur_view_edit_2d_view_frame_grid.addWidget(self.page_sur_view_edit_button_2d_play_pause, 0, 6, 1, 1)
        self.page_sur_view_edit_2d_view = QtWidgets.QWidget(self.page_sur_view_edit_2d_view_frame)
        self.page_sur_view_edit_2d_view.setStyleSheet("")
        self.page_sur_view_edit_2d_view.setObjectName("page_sur_view_edit_2d_view")
        self.page_sur_view_edit_2d_view_frame_grid.addWidget(self.page_sur_view_edit_2d_view, 1, 0, 1, 8)
        self.page_sur_view_edit_button_2d_reset = QtWidgets.QToolButton(self.page_sur_view_edit_2d_view_frame)
        self.page_sur_view_edit_button_2d_reset.setMinimumSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_2d_reset.setMaximumSize(QtCore.QSize(30, 30))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("icons/reset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_sur_view_edit_button_2d_reset.setIcon(icon12)
        self.page_sur_view_edit_button_2d_reset.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_2d_reset.setObjectName("page_sur_view_edit_button_2d_reset")
        self.page_sur_view_edit_2d_view_frame_grid.addWidget(self.page_sur_view_edit_button_2d_reset, 0, 2, 1, 1)
        self.page_sur_view_edit_2d_layout.addWidget(self.page_sur_view_edit_2d_view_frame, 1, 1, 1, 5)
        self.page_sur_view_edit_2d_slider_color_window = QtWidgets.QSlider(self.page_sur_view_edit)
        self.page_sur_view_edit_2d_slider_color_window.setMinimum(-6000)
        self.page_sur_view_edit_2d_slider_color_window.setMaximum(12000)
        self.page_sur_view_edit_2d_slider_color_window.setSingleStep(100)
        self.page_sur_view_edit_2d_slider_color_window.setPageStep(500)
        self.page_sur_view_edit_2d_slider_color_window.setProperty("value", 1800)
        self.page_sur_view_edit_2d_slider_color_window.setOrientation(QtCore.Qt.Vertical)
        self.page_sur_view_edit_2d_slider_color_window.setObjectName("page_sur_view_edit_2d_slider_color_window")
        self.page_sur_view_edit_2d_layout.addWidget(self.page_sur_view_edit_2d_slider_color_window, 1, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.page_sur_view_edit_2d_layout.addItem(spacerItem12, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.page_sur_view_edit_2d_layout, 1, 7, 3, 1)
        self.page_sur_view_edit_button_logout = QtWidgets.QToolButton(self.page_sur_view_edit)
        self.page_sur_view_edit_button_logout.setMinimumSize(QtCore.QSize(0, 0))
        self.page_sur_view_edit_button_logout.setMaximumSize(QtCore.QSize(105, 30))
        self.page_sur_view_edit_button_logout.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("icons/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_sur_view_edit_button_logout.setIcon(icon13)
        self.page_sur_view_edit_button_logout.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_logout.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.page_sur_view_edit_button_logout.setObjectName("page_sur_view_edit_button_logout")
        self.gridLayout_4.addWidget(self.page_sur_view_edit_button_logout, 0, 9, 1, 1)
        self.page_sur_view_edit_3d_layout = QtWidgets.QGridLayout()
        self.page_sur_view_edit_3d_layout.setObjectName("page_sur_view_edit_3d_layout")
        self.page_sur_view_edit_3d_view_frame = QtWidgets.QFrame(self.page_sur_view_edit)
        self.page_sur_view_edit_3d_view_frame.setMinimumSize(QtCore.QSize(350, 250))
        self.page_sur_view_edit_3d_view_frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.page_sur_view_edit_3d_view_frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.page_sur_view_edit_3d_view_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.page_sur_view_edit_3d_view_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_sur_view_edit_3d_view_frame.setLineWidth(0)
        self.page_sur_view_edit_3d_view_frame.setObjectName("page_sur_view_edit_3d_view_frame")
        self.page_sur_view_edit_3d_view_frame_grid = QtWidgets.QGridLayout(self.page_sur_view_edit_3d_view_frame)
        self.page_sur_view_edit_3d_view_frame_grid.setContentsMargins(0, 0, 0, 0)
        self.page_sur_view_edit_3d_view_frame_grid.setSpacing(0)
        self.page_sur_view_edit_3d_view_frame_grid.setObjectName("page_sur_view_edit_3d_view_frame_grid")
        self.page_sur_view_edit_button_3d_zoom_out = QtWidgets.QToolButton(self.page_sur_view_edit_3d_view_frame)
        self.page_sur_view_edit_button_3d_zoom_out.setMinimumSize(QtCore.QSize(0, 0))
        self.page_sur_view_edit_button_3d_zoom_out.setMaximumSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_3d_zoom_out.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.page_sur_view_edit_button_3d_zoom_out.setIcon(icon6)
        self.page_sur_view_edit_button_3d_zoom_out.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_3d_zoom_out.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.page_sur_view_edit_button_3d_zoom_out.setObjectName("page_sur_view_edit_button_3d_zoom_out")
        self.page_sur_view_edit_3d_view_frame_grid.addWidget(self.page_sur_view_edit_button_3d_zoom_out, 0, 0, 1, 1)
        self.page_sur_view_edit_button_3d_fullscreen = QtWidgets.QToolButton(self.page_sur_view_edit_3d_view_frame)
        self.page_sur_view_edit_button_3d_fullscreen.setMinimumSize(QtCore.QSize(0, 0))
        self.page_sur_view_edit_button_3d_fullscreen.setMaximumSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_3d_fullscreen.setIcon(icon8)
        self.page_sur_view_edit_button_3d_fullscreen.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_3d_fullscreen.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.page_sur_view_edit_button_3d_fullscreen.setObjectName("page_sur_view_edit_button_3d_fullscreen")
        self.page_sur_view_edit_3d_view_frame_grid.addWidget(self.page_sur_view_edit_button_3d_fullscreen, 0, 3, 1, 1)
        self.page_sur_view_edit_button_3d_zoom_in = QtWidgets.QToolButton(self.page_sur_view_edit_3d_view_frame)
        self.page_sur_view_edit_button_3d_zoom_in.setMinimumSize(QtCore.QSize(0, 0))
        self.page_sur_view_edit_button_3d_zoom_in.setMaximumSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_3d_zoom_in.setIcon(icon7)
        self.page_sur_view_edit_button_3d_zoom_in.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_3d_zoom_in.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.page_sur_view_edit_button_3d_zoom_in.setObjectName("page_sur_view_edit_button_3d_zoom_in")
        self.page_sur_view_edit_3d_view_frame_grid.addWidget(self.page_sur_view_edit_button_3d_zoom_in, 0, 1, 1, 1)
        self.page_sur_view_edit_3d_view = QtWidgets.QWidget(self.page_sur_view_edit_3d_view_frame)
        self.page_sur_view_edit_3d_view.setStyleSheet("")
        self.page_sur_view_edit_3d_view.setObjectName("page_sur_view_edit_3d_view")
        self.page_sur_view_edit_3d_view_frame_grid.addWidget(self.page_sur_view_edit_3d_view, 1, 0, 1, 5)
        self.page_sur_view_edit_button_3d_reset = QtWidgets.QToolButton(self.page_sur_view_edit_3d_view_frame)
        self.page_sur_view_edit_button_3d_reset.setMinimumSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_3d_reset.setMaximumSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_3d_reset.setIcon(icon12)
        self.page_sur_view_edit_button_3d_reset.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_view_edit_button_3d_reset.setObjectName("page_sur_view_edit_button_3d_reset")
        self.page_sur_view_edit_3d_view_frame_grid.addWidget(self.page_sur_view_edit_button_3d_reset, 0, 2, 1, 1)
        self.page_sur_view_edit_3d_layout.addWidget(self.page_sur_view_edit_3d_view_frame, 1, 0, 1, 4)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.page_sur_view_edit_3d_layout.addItem(spacerItem13, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.page_sur_view_edit_3d_layout, 1, 9, 3, 1)
        sur.addWidget(self.page_sur_view_edit)
        self.page_sur_patient_errand = QtWidgets.QWidget()
        self.page_sur_patient_errand.setObjectName("page_sur_patient_errand")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_sur_patient_errand)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.page_sur_patient_errand_button_logout = QtWidgets.QToolButton(self.page_sur_patient_errand)
        self.page_sur_patient_errand_button_logout.setMinimumSize(QtCore.QSize(30, 30))
        self.page_sur_patient_errand_button_logout.setMaximumSize(QtCore.QSize(105, 30))
        self.page_sur_patient_errand_button_logout.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.page_sur_patient_errand_button_logout.setIcon(icon13)
        self.page_sur_patient_errand_button_logout.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_patient_errand_button_logout.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.page_sur_patient_errand_button_logout.setObjectName("page_sur_patient_errand_button_logout")
        self.gridLayout_3.addWidget(self.page_sur_patient_errand_button_logout, 0, 5, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.page_sur_patient_errand)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.page_sur_patient_errand_label_name = QtWidgets.QLabel(self.groupBox)
        self.page_sur_patient_errand_label_name.setMinimumSize(QtCore.QSize(0, 30))
        self.page_sur_patient_errand_label_name.setMaximumSize(QtCore.QSize(16777215, 30))
        self.page_sur_patient_errand_label_name.setObjectName("page_sur_patient_errand_label_name")
        self.verticalLayout_2.addWidget(self.page_sur_patient_errand_label_name)
        self.page_sur_patient_errand_label_age = QtWidgets.QLabel(self.groupBox)
        self.page_sur_patient_errand_label_age.setMinimumSize(QtCore.QSize(0, 30))
        self.page_sur_patient_errand_label_age.setMaximumSize(QtCore.QSize(16777215, 30))
        self.page_sur_patient_errand_label_age.setObjectName("page_sur_patient_errand_label_age")
        self.verticalLayout_2.addWidget(self.page_sur_patient_errand_label_age)
        self.page_sur_patient_errand_label_phone_number = QtWidgets.QLabel(self.groupBox)
        self.page_sur_patient_errand_label_phone_number.setMinimumSize(QtCore.QSize(0, 30))
        self.page_sur_patient_errand_label_phone_number.setMaximumSize(QtCore.QSize(16777215, 30))
        self.page_sur_patient_errand_label_phone_number.setObjectName("page_sur_patient_errand_label_phone_number")
        self.verticalLayout_2.addWidget(self.page_sur_patient_errand_label_phone_number)
        self.page_sur_patient_errand_label_address = QtWidgets.QLabel(self.groupBox)
        self.page_sur_patient_errand_label_address.setMinimumSize(QtCore.QSize(0, 30))
        self.page_sur_patient_errand_label_address.setMaximumSize(QtCore.QSize(16777215, 30))
        self.page_sur_patient_errand_label_address.setObjectName("page_sur_patient_errand_label_address")
        self.verticalLayout_2.addWidget(self.page_sur_patient_errand_label_address)
        self.page_sur_patient_errand_label_email = QtWidgets.QLabel(self.groupBox)
        self.page_sur_patient_errand_label_email.setMinimumSize(QtCore.QSize(0, 30))
        self.page_sur_patient_errand_label_email.setMaximumSize(QtCore.QSize(16777215, 30))
        self.page_sur_patient_errand_label_email.setObjectName("page_sur_patient_errand_label_email")
        self.verticalLayout_2.addWidget(self.page_sur_patient_errand_label_email)
        spacerItem14 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem14)
        self.gridLayout_7.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.page_sur_patient_errand_label_profile_picture = QtWidgets.QLabel(self.groupBox)
        self.page_sur_patient_errand_label_profile_picture.setMinimumSize(QtCore.QSize(200, 200))
        self.page_sur_patient_errand_label_profile_picture.setMaximumSize(QtCore.QSize(200, 200))
        self.page_sur_patient_errand_label_profile_picture.setText("")
        self.page_sur_patient_errand_label_profile_picture.setScaledContents(True)
        self.page_sur_patient_errand_label_profile_picture.setObjectName("page_sur_patient_errand_label_profile_picture")
        self.gridLayout_7.addWidget(self.page_sur_patient_errand_label_profile_picture, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 1, 3, 1, 3)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.page_sur_patient_errand_button_back = QtWidgets.QToolButton(self.page_sur_patient_errand)
        self.page_sur_patient_errand_button_back.setMinimumSize(QtCore.QSize(30, 30))
        self.page_sur_patient_errand_button_back.setMaximumSize(QtCore.QSize(75, 30))
        self.page_sur_patient_errand_button_back.setIcon(icon)
        self.page_sur_patient_errand_button_back.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_patient_errand_button_back.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.page_sur_patient_errand_button_back.setObjectName("page_sur_patient_errand_button_back")
        self.gridLayout_6.addWidget(self.page_sur_patient_errand_button_back, 0, 0, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem15, 0, 4, 1, 1)
        self.page_sur_patient_errand_button_view = QtWidgets.QToolButton(self.page_sur_patient_errand)
        self.page_sur_patient_errand_button_view.setEnabled(False)
        self.page_sur_patient_errand_button_view.setMinimumSize(QtCore.QSize(30, 30))
        self.page_sur_patient_errand_button_view.setMaximumSize(QtCore.QSize(30, 30))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("icons/view.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_sur_patient_errand_button_view.setIcon(icon14)
        self.page_sur_patient_errand_button_view.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_patient_errand_button_view.setObjectName("page_sur_patient_errand_button_view")
        self.gridLayout_6.addWidget(self.page_sur_patient_errand_button_view, 0, 5, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem16, 0, 1, 1, 1)
        self.page_sur_patient_errand_button_download = QtWidgets.QToolButton(self.page_sur_patient_errand)
        self.page_sur_patient_errand_button_download.setEnabled(False)
        self.page_sur_patient_errand_button_download.setMinimumSize(QtCore.QSize(30, 30))
        self.page_sur_patient_errand_button_download.setMaximumSize(QtCore.QSize(30, 30))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("icons/download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_sur_patient_errand_button_download.setIcon(icon15)
        self.page_sur_patient_errand_button_download.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_patient_errand_button_download.setObjectName("page_sur_patient_errand_button_download")
        self.gridLayout_6.addWidget(self.page_sur_patient_errand_button_download, 0, 2, 1, 1)
        self.page_sur_patient_errand_progress_bar = QtWidgets.QProgressBar(self.page_sur_patient_errand)
        self.page_sur_patient_errand_progress_bar.setProperty("value", 24)
        self.page_sur_patient_errand_progress_bar.setObjectName("page_sur_patient_errand_progress_bar")
        self.gridLayout_6.addWidget(self.page_sur_patient_errand_progress_bar, 0, 3, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_6, 5, 2, 1, 4)
        self.page_sur_patient_errand_label_patients_profile = QtWidgets.QLabel(self.page_sur_patient_errand)
        self.page_sur_patient_errand_label_patients_profile.setMinimumSize(QtCore.QSize(0, 40))
        self.page_sur_patient_errand_label_patients_profile.setMaximumSize(QtCore.QSize(16777215, 40))
        self.page_sur_patient_errand_label_patients_profile.setStyleSheet("font-size: 20pt;")
        self.page_sur_patient_errand_label_patients_profile.setObjectName("page_sur_patient_errand_label_patients_profile")
        self.gridLayout_3.addWidget(self.page_sur_patient_errand_label_patients_profile, 0, 3, 1, 1)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.page_sur_patient_errand_errand_list = QtWidgets.QTreeWidget(self.page_sur_patient_errand)
        self.page_sur_patient_errand_errand_list.setObjectName("page_sur_patient_errand_errand_list")
        self.gridLayout_11.addWidget(self.page_sur_patient_errand_errand_list, 1, 0, 1, 2)
        self.page_sur_patient_errand_label_patients_scans = QtWidgets.QLabel(self.page_sur_patient_errand)
        self.page_sur_patient_errand_label_patients_scans.setMinimumSize(QtCore.QSize(0, 40))
        self.page_sur_patient_errand_label_patients_scans.setMaximumSize(QtCore.QSize(16777215, 40))
        self.page_sur_patient_errand_label_patients_scans.setStyleSheet("font-size: 20pt;")
        self.page_sur_patient_errand_label_patients_scans.setObjectName("page_sur_patient_errand_label_patients_scans")
        self.gridLayout_11.addWidget(self.page_sur_patient_errand_label_patients_scans, 0, 0, 1, 1)
        self.page_sur_patient_errand_search_box = QtWidgets.QTextEdit(self.page_sur_patient_errand)
        self.page_sur_patient_errand_search_box.setMaximumSize(QtCore.QSize(200, 30))
        self.page_sur_patient_errand_search_box.setObjectName("page_sur_patient_errand_search_box")
        self.gridLayout_11.addWidget(self.page_sur_patient_errand_search_box, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_11, 2, 3, 1, 3)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.page_sur_patient_errand_label_report = QtWidgets.QLabel(self.page_sur_patient_errand)
        self.page_sur_patient_errand_label_report.setMinimumSize(QtCore.QSize(0, 40))
        self.page_sur_patient_errand_label_report.setMaximumSize(QtCore.QSize(16777215, 40))
        self.page_sur_patient_errand_label_report.setStyleSheet("font-size: 20pt;")
        self.page_sur_patient_errand_label_report.setScaledContents(True)
        self.page_sur_patient_errand_label_report.setWordWrap(False)
        self.page_sur_patient_errand_label_report.setObjectName("page_sur_patient_errand_label_report")
        self.gridLayout_9.addWidget(self.page_sur_patient_errand_label_report, 0, 0, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem17, 0, 1, 1, 1)
        self.page_sur_patient_errand_report_frame = QtWidgets.QFrame(self.page_sur_patient_errand)
        self.page_sur_patient_errand_report_frame.setMinimumSize(QtCore.QSize(500, 0))
        self.page_sur_patient_errand_report_frame.setMaximumSize(QtCore.QSize(4545245, 16777215))
        self.page_sur_patient_errand_report_frame.setStyleSheet("")
        self.page_sur_patient_errand_report_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.page_sur_patient_errand_report_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_sur_patient_errand_report_frame.setLineWidth(0)
        self.page_sur_patient_errand_report_frame.setObjectName("page_sur_patient_errand_report_frame")
        self.page_sur_patient_errand_report_frame_grid = QtWidgets.QGridLayout(self.page_sur_patient_errand_report_frame)
        self.page_sur_patient_errand_report_frame_grid.setContentsMargins(0, 0, 0, 0)
        self.page_sur_patient_errand_report_frame_grid.setObjectName("page_sur_patient_errand_report_frame_grid")
        self.page_sur_patient_errand_report = QtWidgets.QWidget(self.page_sur_patient_errand_report_frame)
        self.page_sur_patient_errand_report.setObjectName("page_sur_patient_errand_report")
        self.page_sur_patient_errand_report_frame_grid.addWidget(self.page_sur_patient_errand_report, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.page_sur_patient_errand_report_frame, 1, 0, 1, 2)
        self.gridLayout_3.addLayout(self.gridLayout_9, 0, 2, 3, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem18, 0, 4, 1, 1)
        sur.addWidget(self.page_sur_patient_errand)
        self.page_sur_home = QtWidgets.QWidget()
        self.page_sur_home.setObjectName("page_sur_home")
        self.gridLayout = QtWidgets.QGridLayout(self.page_sur_home)
        self.gridLayout.setObjectName("gridLayout")
        self.page_sur_home_treatment_list = QtWidgets.QTreeWidget(self.page_sur_home)
        self.page_sur_home_treatment_list.setObjectName("page_sur_home_treatment_list")
        self.gridLayout.addWidget(self.page_sur_home_treatment_list, 3, 1, 1, 3)
        self.page_sur_home_textEdit_search = QtWidgets.QTextEdit(self.page_sur_home)
        self.page_sur_home_textEdit_search.setMaximumSize(QtCore.QSize(200, 25))
        self.page_sur_home_textEdit_search.setObjectName("page_sur_home_textEdit_search")
        self.gridLayout.addWidget(self.page_sur_home_textEdit_search, 2, 3, 1, 1)
        self.page_sur_home_logout = QtWidgets.QToolButton(self.page_sur_home)
        self.page_sur_home_logout.setMinimumSize(QtCore.QSize(30, 30))
        self.page_sur_home_logout.setMaximumSize(QtCore.QSize(105, 30))
        self.page_sur_home_logout.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.page_sur_home_logout.setIcon(icon13)
        self.page_sur_home_logout.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_home_logout.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.page_sur_home_logout.setObjectName("page_sur_home_logout")
        self.gridLayout.addWidget(self.page_sur_home_logout, 0, 3, 1, 1)
        self.page_sur_home_button_colleagues = QtWidgets.QToolButton(self.page_sur_home)
        self.page_sur_home_button_colleagues.setEnabled(False)
        self.page_sur_home_button_colleagues.setMinimumSize(QtCore.QSize(30, 30))
        self.page_sur_home_button_colleagues.setMaximumSize(QtCore.QSize(30, 30))
        self.page_sur_home_button_colleagues.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("icons/colleagues.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_sur_home_button_colleagues.setIcon(icon16)
        self.page_sur_home_button_colleagues.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_home_button_colleagues.setObjectName("page_sur_home_button_colleagues")
        self.gridLayout.addWidget(self.page_sur_home_button_colleagues, 0, 1, 1, 1)
        self.page_sur_home_button_proceed = QtWidgets.QToolButton(self.page_sur_home)
        self.page_sur_home_button_proceed.setEnabled(False)
        self.page_sur_home_button_proceed.setMinimumSize(QtCore.QSize(30, 30))
        self.page_sur_home_button_proceed.setMaximumSize(QtCore.QSize(30, 30))
        self.page_sur_home_button_proceed.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("icons/forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_sur_home_button_proceed.setIcon(icon17)
        self.page_sur_home_button_proceed.setIconSize(QtCore.QSize(30, 30))
        self.page_sur_home_button_proceed.setObjectName("page_sur_home_button_proceed")
        self.gridLayout.addWidget(self.page_sur_home_button_proceed, 4, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.page_sur_home)
        self.label.setStyleSheet("font-size: 20pt;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 1, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem19, 0, 2, 1, 1)
        sur.addWidget(self.page_sur_home)

        self.retranslateUi(sur)
        sur.setCurrentIndex(0)
        self.page_sure_view_edit_tab.setCurrentIndex(0)
        self.page_sur_view_edit_tools.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(sur)

    def retranslateUi(self, sur):
        _translate = QtCore.QCoreApplication.translate
        sur.setWindowTitle(_translate("sur", "StackedWidget"))
        self.page_sur_view_edit_button_tools.setToolTip(_translate("sur", "Show advanced functionality for image manipulation"))
        self.page_sur_view_edit_button_tools.setText(_translate("sur", "Show Advanced Tools"))
        self.page_sur_view_edit_button_back.setToolTip(_translate("sur", "Go back to patient page"))
        self.page_sur_view_edit_button_back.setText(_translate("sur", "Back"))
        self.page_sur_view_edit_insert_link.setPlaceholderText(_translate("sur", "Insert weblink or search term for patient"))
        self.page_sur_view_edit_insert_note.setPlaceholderText(_translate("sur", "Insert note to patient about finding"))
        self.page_sur_view_edit_button_add_note.setToolTip(_translate("sur", "Add note or link"))
        self.page_sur_view_edit_button_add_note.setText(_translate("sur", "Add Annotation"))
        self.page_sure_view_edit_tab.setTabText(self.page_sure_view_edit_tab.indexOf(self.page_sure_view_edit_tab_note), _translate("sur", "Note"))
        self.page_sur_view_edit_button_add_impression.setToolTip(_translate("sur", "Add impression"))
        self.page_sur_view_edit_button_add_impression.setText(_translate("sur", "Add Impression"))
        self.page_sur_view_edit_insert_impression.setPlaceholderText(_translate("sur", "Insert impression"))
        self.page_sure_view_edit_tab.setTabText(self.page_sure_view_edit_tab.indexOf(self.page_sure_view_edit_tab_impression), _translate("sur", "Impression"))
        self.page_sur_view_edit_button_2d_previous_note.setToolTip(_translate("sur", "Go to previous finding on the report"))
        self.page_sur_view_edit_button_2d_previous_note.setText(_translate("sur", "Previous Note"))
        self.page_sur_view_edit_button_save_report.setToolTip(_translate("sur", "Save report changes"))
        self.page_sur_view_edit_tools_orientation.setToolTip(_translate("sur", "Change the 2D view image orientation"))
        self.radio_button_axial.setToolTip(_translate("sur", "Top-down view of the scan"))
        self.radio_button_axial.setText(_translate("sur", "AXIAL"))
        self.radio_button_sagittal.setToolTip(_translate("sur", "Left-right view of the scan"))
        self.radio_button_sagittal.setText(_translate("sur", "SAGITTAL"))
        self.radio_button_coronal.setToolTip(_translate("sur", "Front-back view of the scan"))
        self.radio_button_coronal.setText(_translate("sur", "CORONAL"))
        self.page_sur_view_edit_tools.setItemText(self.page_sur_view_edit_tools.indexOf(self.page_sur_view_edit_tools_orientation), _translate("sur", "2D Orientation"))
        self.page_sur_view_edit_tools_tissue.setToolTip(_translate("sur", "Change the type of tissues shown on the scan"))
        self.checkBox_All.setText(_translate("sur", "ALL"))
        self.checkBox_Soft.setText(_translate("sur", "SOFT"))
        self.checkBox_Bone.setText(_translate("sur", "BONE"))
        self.checkBox_Muscle.setText(_translate("sur", "MUSCLE"))
        self.checkBox_Fat.setText(_translate("sur", "FAT"))
        self.checkBox_Skin.setText(_translate("sur", "SKIN"))
        self.page_sur_view_edit_tools.setItemText(self.page_sur_view_edit_tools.indexOf(self.page_sur_view_edit_tools_tissue), _translate("sur", "3D Tissues"))
        self.page_sur_view_edit_tools_transparency.setToolTip(_translate("sur", "Change the transparency of objects of the 3D view"))
        self.page_sur_view_edit_slider_transparency_volume.setToolTip(_translate("sur", "Change the transparency of the 3D volume"))
        self.page_sur_view_edit_label_transparency_volume.setText(_translate("sur", "3D Volume"))
        self.page_sur_view_edit_slider_transparency_segmentation.setToolTip(_translate("sur", "Change the transparency of all segmentations"))
        self.page_sur_view_edit_label_transparency_segmentation.setText(_translate("sur", "Segmentations"))
        self.page_sur_view_edit_slider_transparency_active.setToolTip(_translate("sur", "Change the transparency of the current finding segment"))
        self.page_sur_view_edit_label_transparency_active.setText(_translate("sur", "Active Segment"))
        self.page_sur_view_edit_tools.setItemText(self.page_sur_view_edit_tools.indexOf(self.page_sur_view_edit_tools_transparency), _translate("sur", "3D Transparency"))
        self.page_sur_view_edit_tools_link.setToolTip(_translate("sur", "Select how the linked 2D slice is shown on the 3D view"))
        self.checkBox.setToolTip(_translate("sur", "Show the 2D image slice on the 3D view when linked"))
        self.checkBox.setText(_translate("sur", "Show 2D Image"))
        self.checkBox_2.setToolTip(_translate("sur", "Show the full 3D volume when or crop the volume at the active slice when linked"))
        self.checkBox_2.setText(_translate("sur", "Show Full 3D Volume"))
        self.page_sur_view_edit_tools.setItemText(self.page_sur_view_edit_tools.indexOf(self.page_sur_view_edit_tools_link), _translate("sur", "3D Link "))
        self.page_sur_view_edit_button_2d_next_note.setToolTip(_translate("sur", "Go to next finding on the report"))
        self.page_sur_view_edit_button_2d_next_note.setText(_translate("sur", "Next Note"))
        self.page_sur_view_edit_button_link_windows.setToolTip(_translate("sur", "Toggle link between 2D and 3D views to track slice location"))
        self.page_sur_view_edit_button_link_windows.setText(_translate("sur", "Activate\n"
"2D-3D Link"))
        self.page_sur_view_edit_2d_slider_color_level.setToolTip(_translate("sur", "Slide to change 2D image color level"))
        self.page_sur_view_edit_2d_view_frame.setToolTip(_translate("sur", "Scroll to advance through the images. Right-click and drag to zoom in and out"))
        self.page_sur_view_edit_button_2d_zoom_out.setToolTip(_translate("sur", "Zoom out on 2D view"))
        self.page_sur_view_edit_button_2d_zoom_out.setText(_translate("sur", "Zoom Out"))
        self.page_sur_view_edit_button_2d_zoom_in.setToolTip(_translate("sur", "Zoom in on 2D view"))
        self.page_sur_view_edit_button_2d_zoom_in.setText(_translate("sur", "Zoom In"))
        self.page_sur_view_edit_button_2d_fullscreen.setToolTip(_translate("sur", "Expand 2D view"))
        self.page_sur_view_edit_button_2d_fullscreen.setText(_translate("sur", "2D Full Screen"))
        self.page_sur_view_edit_button_2d_previous_slice.setToolTip(_translate("sur", "Go to previous slice. Hold to keep scrolling"))
        self.page_sur_view_edit_button_2d_previous_slice.setText(_translate("sur", "Previous Slice"))
        self.page_sur_view_edit_button_2d_next_slice.setToolTip(_translate("sur", "Go to next slice. Hold to keep scrolling"))
        self.page_sur_view_edit_button_2d_next_slice.setText(_translate("sur", "Next Slice"))
        self.page_sur_view_edit_button_2d_play_pause.setToolTip(_translate("sur", "Play slice animation"))
        self.page_sur_view_edit_button_2d_play_pause.setText(_translate("sur", "Play Slices"))
        self.page_sur_view_edit_button_2d_reset.setToolTip(_translate("sur", "Reset view - 2D"))
        self.page_sur_view_edit_button_2d_reset.setText(_translate("sur", "..."))
        self.page_sur_view_edit_2d_slider_color_window.setToolTip(_translate("sur", "Slide to change 2D image color window"))
        self.page_sur_view_edit_button_logout.setToolTip(_translate("sur", "Logout"))
        self.page_sur_view_edit_button_logout.setText(_translate("sur", "   Logout"))
        self.page_sur_view_edit_3d_view_frame.setToolTip(_translate("sur", "Click and drag to move the volume. Scroll to zoom in and out of the volume"))
        self.page_sur_view_edit_button_3d_zoom_out.setToolTip(_translate("sur", "Zoom out on 3D view"))
        self.page_sur_view_edit_button_3d_zoom_out.setText(_translate("sur", "Zoom Out"))
        self.page_sur_view_edit_button_3d_fullscreen.setToolTip(_translate("sur", "Expand 3D view"))
        self.page_sur_view_edit_button_3d_fullscreen.setText(_translate("sur", "3D Full Screen"))
        self.page_sur_view_edit_button_3d_zoom_in.setToolTip(_translate("sur", "Zoom in on 3D view"))
        self.page_sur_view_edit_button_3d_zoom_in.setText(_translate("sur", "Zoom In"))
        self.page_sur_view_edit_button_3d_reset.setToolTip(_translate("sur", "Reset view - 3D"))
        self.page_sur_view_edit_button_3d_reset.setText(_translate("sur", "..."))
        self.page_sur_patient_errand_button_logout.setToolTip(_translate("sur", "Logout"))
        self.page_sur_patient_errand_button_logout.setText(_translate("sur", "   Logout"))
        self.page_sur_patient_errand_label_name.setText(_translate("sur", "NAME"))
        self.page_sur_patient_errand_label_age.setText(_translate("sur", "AGE"))
        self.page_sur_patient_errand_label_phone_number.setText(_translate("sur", "PHONE NUMBER"))
        self.page_sur_patient_errand_label_address.setText(_translate("sur", "ADDRESS"))
        self.page_sur_patient_errand_label_email.setText(_translate("sur", "EMAIL"))
        self.page_sur_patient_errand_button_back.setToolTip(_translate("sur", "Go back"))
        self.page_sur_patient_errand_button_back.setText(_translate("sur", "Back"))
        self.page_sur_patient_errand_button_view.setToolTip(_translate("sur", "View scan"))
        self.page_sur_patient_errand_button_view.setText(_translate("sur", "View"))
        self.page_sur_patient_errand_button_download.setToolTip(_translate("sur", "Download report"))
        self.page_sur_patient_errand_button_download.setText(_translate("sur", "Download"))
        self.page_sur_patient_errand_label_patients_profile.setText(_translate("sur", "Patient\'s Profile"))
        self.page_sur_patient_errand_errand_list.setToolTip(_translate("sur", "Double-click on a completed scan to view radiology report"))
        self.page_sur_patient_errand_errand_list.headerItem().setText(0, _translate("sur", "ID"))
        self.page_sur_patient_errand_errand_list.headerItem().setText(1, _translate("sur", "Date"))
        self.page_sur_patient_errand_errand_list.headerItem().setText(2, _translate("sur", "Scan"))
        self.page_sur_patient_errand_errand_list.headerItem().setText(3, _translate("sur", "Clinic"))
        self.page_sur_patient_errand_errand_list.headerItem().setText(4, _translate("sur", "Status"))
        self.page_sur_patient_errand_label_patients_scans.setText(_translate("sur", "Patient\'s Scans"))
        self.page_sur_patient_errand_search_box.setHtml(_translate("sur", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.page_sur_patient_errand_search_box.setPlaceholderText(_translate("sur", "Search..."))
        self.page_sur_patient_errand_label_report.setText(_translate("sur", "Report"))
        self.page_sur_home_treatment_list.setToolTip(_translate("sur", "Double-click on a scan order to see more information"))
        self.page_sur_home_treatment_list.setSortingEnabled(True)
        self.page_sur_home_treatment_list.headerItem().setText(0, _translate("sur", "Surname"))
        self.page_sur_home_treatment_list.headerItem().setText(1, _translate("sur", "First name"))
        self.page_sur_home_treatment_list.headerItem().setText(2, _translate("sur", "Patient ID"))
        self.page_sur_home_treatment_list.headerItem().setText(3, _translate("sur", "Sex"))
        self.page_sur_home_treatment_list.headerItem().setText(4, _translate("sur", "Date ordered"))
        self.page_sur_home_treatment_list.headerItem().setText(5, _translate("sur", "Scan"))
        self.page_sur_home_treatment_list.headerItem().setText(6, _translate("sur", "Status"))
        self.page_sur_home_treatment_list.headerItem().setText(7, _translate("sur", "Order ID"))
        self.page_sur_home_textEdit_search.setHtml(_translate("sur", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Search box</p></body></html>"))
        self.page_sur_home_logout.setToolTip(_translate("sur", "Logout"))
        self.page_sur_home_logout.setText(_translate("sur", "   Logout"))
        self.page_sur_home_button_colleagues.setToolTip(_translate("sur", "Show colleagues"))
        self.page_sur_home_button_colleagues.setText(_translate("sur", "My profile "))
        self.page_sur_home_button_proceed.setToolTip(_translate("sur", "Go to patients page"))
        self.page_sur_home_button_proceed.setText(_translate("sur", "Proceed"))
        self.label.setText(_translate("sur", "My Patients"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    sur = QtWidgets.QStackedWidget()
    ui = Ui_sur()
    ui.setupUi(sur)
    sur.show()
    sys.exit(app.exec_())

