# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.setWindowModality(QtCore.Qt.NonModal)
        main_window.resize(596, 431)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(main_window.sizePolicy().hasHeightForWidth())
        main_window.setSizePolicy(sizePolicy)
        main_window.setStyleSheet("")
        main_window.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.central_widget = QtWidgets.QWidget(main_window)
        self.central_widget.setStyleSheet("")
        self.central_widget.setObjectName("central_widget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.central_widget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.stacked_main = QtWidgets.QStackedWidget(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stacked_main.sizePolicy().hasHeightForWidth())
        self.stacked_main.setSizePolicy(sizePolicy)
        self.stacked_main.setObjectName("stacked_main")
        self.page_login = QtWidgets.QWidget()
        self.page_login.setObjectName("page_login")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_login)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 6, 3, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.page_login)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_2.addWidget(self.textEdit, 6, 1, 1, 2)
        self.page_login_insert_password = QtWidgets.QLineEdit(self.page_login)
        self.page_login_insert_password.setMaximumSize(QtCore.QSize(200, 16777215))
        self.page_login_insert_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.page_login_insert_password.setClearButtonEnabled(False)
        self.page_login_insert_password.setObjectName("page_login_insert_password")
        self.gridLayout_2.addWidget(self.page_login_insert_password, 3, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 7, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.page_login)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.page_login)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 4, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 0, 1, 1, 4)
        self.page_login_combobox_user_type = QtWidgets.QComboBox(self.page_login)
        self.page_login_combobox_user_type.setMinimumSize(QtCore.QSize(100, 0))
        self.page_login_combobox_user_type.setObjectName("page_login_combobox_user_type")
        self.page_login_combobox_user_type.addItem("")
        self.page_login_combobox_user_type.addItem("")
        self.page_login_combobox_user_type.addItem("")
        self.gridLayout_2.addWidget(self.page_login_combobox_user_type, 4, 1, 1, 1)
        self.page_login_button_login = QtWidgets.QToolButton(self.page_login)
        self.page_login_button_login.setMaximumSize(QtCore.QSize(200, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/unlock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.page_login_button_login.setIcon(icon)
        self.page_login_button_login.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.page_login_button_login.setObjectName("page_login_button_login")
        self.gridLayout_2.addWidget(self.page_login_button_login, 4, 2, 1, 1)
        self.page_login_insert_id = QtWidgets.QLineEdit(self.page_login)
        self.page_login_insert_id.setMaximumSize(QtCore.QSize(200, 16777215))
        self.page_login_insert_id.setObjectName("page_login_insert_id")
        self.gridLayout_2.addWidget(self.page_login_insert_id, 2, 2, 1, 1)
        self.stacked_main.addWidget(self.page_login)
        self.page_rad = QtWidgets.QWidget()
        self.page_rad.setObjectName("page_rad")
        self.gridLayout = QtWidgets.QGridLayout(self.page_rad)
        self.gridLayout.setObjectName("gridLayout")
        self.stacked_rad = QtWidgets.QStackedWidget(self.page_rad)
        self.stacked_rad.setObjectName("stacked_rad")
        self.gridLayout.addWidget(self.stacked_rad, 0, 0, 1, 1)
        self.stacked_main.addWidget(self.page_rad)
        self.page_pat = QtWidgets.QWidget()
        self.page_pat.setObjectName("page_pat")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_pat)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.stacked_pat = QtWidgets.QStackedWidget(self.page_pat)
        self.stacked_pat.setObjectName("stacked_pat")
        self.gridLayout_4.addWidget(self.stacked_pat, 0, 0, 1, 1)
        self.stacked_main.addWidget(self.page_pat)
        self.page_sur = QtWidgets.QWidget()
        self.page_sur.setObjectName("page_sur")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_sur)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.stacked_sur = QtWidgets.QStackedWidget(self.page_sur)
        self.stacked_sur.setObjectName("stacked_sur")
        self.gridLayout_6.addWidget(self.stacked_sur, 0, 0, 1, 1)
        self.stacked_main.addWidget(self.page_sur)
        self.gridLayout_5.addWidget(self.stacked_main, 0, 0, 1, 1)
        main_window.setCentralWidget(self.central_widget)
        self.menu_bar = QtWidgets.QMenuBar(main_window)
        self.menu_bar.setGeometry(QtCore.QRect(0, 0, 596, 21))
        self.menu_bar.setObjectName("menu_bar")
        self.menu_bar_theme = QtWidgets.QMenu(self.menu_bar)
        self.menu_bar_theme.setObjectName("menu_bar_theme")
        main_window.setMenuBar(self.menu_bar)
        self.status_bar = QtWidgets.QStatusBar(main_window)
        self.status_bar.setObjectName("status_bar")
        main_window.setStatusBar(self.status_bar)
        self.menu_bar_theme_button_night_mode = QtWidgets.QAction(main_window)
        self.menu_bar_theme_button_night_mode.setCheckable(True)
        self.menu_bar_theme_button_night_mode.setChecked(True)
        self.menu_bar_theme_button_night_mode.setObjectName("menu_bar_theme_button_night_mode")
        self.menu_bar_theme_button_day_mode = QtWidgets.QAction(main_window)
        self.menu_bar_theme_button_day_mode.setCheckable(True)
        self.menu_bar_theme_button_day_mode.setChecked(False)
        self.menu_bar_theme_button_day_mode.setObjectName("menu_bar_theme_button_day_mode")
        self.menu_bar_theme.addAction(self.menu_bar_theme_button_day_mode)
        self.menu_bar_theme.addAction(self.menu_bar_theme_button_night_mode)
        self.menu_bar.addAction(self.menu_bar_theme.menuAction())

        self.retranslateUi(main_window)
        self.stacked_main.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Clarity"))
        self.textEdit.setHtml(_translate("main_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Patients:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">id: 0000 pw: 0000</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">id: 0001 pw: 0001</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Radiologist:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">id: 0000 pw: 0000</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Surgeon:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">id: 0000 pw: 0000</p></body></html>"))
        self.page_login_insert_password.setText(_translate("main_window", "0000"))
        self.page_login_insert_password.setPlaceholderText(_translate("main_window", "Password"))
        self.label_2.setText(_translate("main_window", "Password:"))
        self.label.setText(_translate("main_window", "User ID:"))
        self.page_login_combobox_user_type.setItemText(0, _translate("main_window", "Patient"))
        self.page_login_combobox_user_type.setItemText(1, _translate("main_window", "Radiologist"))
        self.page_login_combobox_user_type.setItemText(2, _translate("main_window", "Surgeon"))
        self.page_login_button_login.setText(_translate("main_window", "Login"))
        self.page_login_insert_id.setText(_translate("main_window", "0000"))
        self.page_login_insert_id.setPlaceholderText(_translate("main_window", "ID"))
        self.menu_bar_theme.setTitle(_translate("main_window", "Theme"))
        self.menu_bar_theme_button_night_mode.setText(_translate("main_window", "Night mode"))
        self.menu_bar_theme_button_day_mode.setText(_translate("main_window", "Day mode"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QMainWindow()
    ui = Ui_main_window()
    ui.setupUi(main_window)
    main_window.show()
    sys.exit(app.exec_())

